### ISSUE TITLE
[RFC] Migration to github

### ISSUE THREAD

**Issue by rousseldenis** [GrandOrgue/grandorgue#1]
Hi @e9925248 @larspalo,

I've created this repository and made a first migration of SVN original repository embedding the commit history and authors (with github sync when I found it).

I'm waiting your feedback on this to go forward. I hope soon. Thanks

**Comment by rousseldenis** [comment]
@larspalo Could you also adapt Project description in Sourceforge and hide now Github mirror and Svn tabs ?

**Comment by oleg68** [comment]
@rousseldenis @larspalo 

Where are the discussion pages now? A we ready to start discussions here or we continue to dsicuss on sourcefourge?

Can we migrate here the existing discussion pages from SourceForge?

**Comment by rousseldenis** [comment]
> @rousseldenis @larspalo
> 
> Where are the discussion pages now? A we ready to start discussions here or we continue to dsicuss on sourcefourge?
> 
> Can we migrate here the existing discussion pages from SourceForge?

This has to be discussed. But here we do new issues for this repository. Maybe dicussion pages will stay in Sourceforge as this is a paid feature of Github.

**Comment by rousseldenis** [comment]
> > @rousseldenis @larspalo
> > Where are the discussion pages now? A we ready to start discussions here or we continue to dsicuss on sourcefourge?
> > Can we migrate here the existing discussion pages from SourceForge?
> 
> This has to be discussed. But here we do new issues for this repository. Maybe dicussion pages will stay in Sourceforge as this is a paid feature of Github.

Mmmh, I've just checked. It is free. So, we can move discussions here or let them on Sourceforge. We can maybe test them here and see if their features are great or not (I've not tested it yet)

**Comment by larspalo** [comment]
I think there are valuable information still on the discussions here on
Sourceforge so it would be ideal if the content could be migrated somehow,
that's nothing I know how to do yet though - requires some research.

It seems easily enough to change the state of GrandOrgue on Sourceforge to
having moved the project to GitHub, though. I'll go ahead and do that and
change the description too.


Den sön 5 sep. 2021 kl 14:29 skrev Denis Roussel (ACSONE) <
***@***.***>:

**Comment by oleg68** [comment]
> So, we can move discussions here or let them on Sourceforge.
I think it is better to move discussions here and to close ones in SourceForge.

Is it possible to migrate existing discussion from SourceForge to Github?

> We can maybe test them here and see if their features are great or not (I've not tested it yet)
Please take a look at https://github.com/oleg68/GrandOrgue/discussions

**Comment by larspalo** [comment]
I've found out how to export the discussion forum from Sourceforge.
Once the export is complete the next step will be to find out how to
import it into GitHub.

Den sön 5 sep. 2021 kl 20:33 skrev Oleg Samarin ***@***.***>:

**Comment by rousseldenis** [comment]
> I've found out how to export the discussion forum from Sourceforge. Once the export is complete the next step will be to find out how to import it into GitHub. Den sön 5 sep. 2021 kl 20:33 skrev Oleg Samarin ***@***.***>:
> […](#)
> So, we can move discussions here or let them on Sourceforge. I think it is better to move discussions here and to close ones in SourceForge. Is it possible to migrate existing discussion from SourceForge to Github? We can maybe test them here and see if their features are great or not (I've not tested it yet) Please take a look at https://github.com/oleg68/GrandOrgue/discussions — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

I've found this : https://docs.github.com/en/graphql/guides/using-the-graphql-api-for-discussions

So, it should be done through a script based on your export.

**Comment by larspalo** [comment]
The Sourceforge forum is exported as a .json file that's reasonably readable and as a folder structure. The export was set to include the attachments too. I'll read the documentation above and try to find a way to import to GitHub. In the mean time I've tried to set the Sourceforge forum to read only to avoid further changes.

**Comment by rousseldenis** [comment]
> The Sourceforge forum is exported as a .json file that's reasonably readable and as a folder structure. The export was set to include the attachments too. I'll read the documentation above and try to find a way to import to GitHub. In the mean time I've tried to set the Sourceforge forum to read only to avoid further changes.

@larspalo I'm experienced in python scripts, so, if you want to send me the export in PM, I can try to do it on a private repo for testing, then, we validate and I'll do it here.

**Comment by rousseldenis** [comment]
@oleg68 @larspalo What's the flow for publishing on opensuse from the artifacts generated by github actions ?

**Comment by oleg68** [comment]
> What's the flow for publishing on opensuse from the artifacts generated by github actions ?

There is no such flow.

**Comment by rousseldenis** [comment]
> There is no such flow.

For now, but I suppose we can imagine something to publish them (for apt, etc...)

**Comment by larspalo** [comment]
@rousseldenis I've uploaded the export from GO forums in Sourceforge to http://familjenpalo.se/sites/default/files/filer/ourorgan-backup-2021-09-05-185136.zip if it's of interest. I've been reading about the GraphQL API and found out about the GraphiQL in-browser tool. However, it will definitely take a lot of testing for me to get things right - so if you're familiar with it - go ahead and fix the import. Otherwise, I'll explore it more and we'll see who gets it first!

**Comment by rousseldenis** [comment]
> @rousseldenis I've uploaded the export from GO forums in Sourceforge to http://familjenpalo.se/sites/default/files/filer/ourorgan-backup-2021-09-05-185136.zip if it's of interest. I've been reading about the GraphQL API and found out about the GraphiQL in-browser tool. However, it will definitely take a lot of testing for me to get things right - so if you're familiar with it - go ahead and fix the import. Otherwise, I'll explore it more and we'll see who gets it first!

Ok, great. I had a quick look into it and it could be easy to do as the json is clear on the structure. When I have a moment, I'd try

**Comment by oleg68** [comment]
@larspalo Could you update the main page on SourceForge and place the link https://github.com/GrandOrgue/grandorgue there?

**Comment by larspalo** [comment]
Yes, I'll do that now!

**Comment by oleg68** [comment]
Now this repo is private and it is not visible by other people.

Are we ready to make this repostory public?

**Comment by larspalo** [comment]
The only thing that's not fixed is the discussion forum. That still needs attention, but I think everything else could be public.

**Comment by oleg68** [comment]
I think it is not a blocker now because we may import the discussion forum later.

**Comment by larspalo** [comment]
Agree, the import can be done later. Also, if we want to re-organize the categories for the forum, we can do it already now. That maybe should be an issue in itself...

**Comment by oleg68** [comment]
@larspalo @rousseldenis  The migration has finished. May we close this issue?

**Comment by larspalo** [comment]
Yes, I think we can close this and continue with other issues.
