### ISSUE TITLE
First oficial release on Github

### ISSUE THREAD

**Issue by oleg68** [GrandOrgue/grandorgue#10]
@larspalo @rousseldenis 

I think its time to start thinking on the first oficial release that should we issue on github.

What should we include it into? What should we do before it?

I suggest to take neither enchancements nor bugfixes, but make all changes necessary for reflecting moving to github. At least, to change README.md, BUILD.md, INSTALL.md.

Because the application icon caused some misconvinience, maybe we should to change it before the first release. The project icon on github must be the same as in the application.

Of cause, each change must be done with a separate PR and, possible, with a separate issue.

@rousseldenis is there any capability of grouping issues together like ``all issues planned for the first release``?

**Comment by rousseldenis** [comment]
> @rousseldenis is there any capability of grouping issues together like `all issues planned for the first release`?

A simple way is to do tasks with links to PR's here like  :

- [x] Update Build.md- #7
- [ ] Update README.md

**Comment by rousseldenis** [comment]
A further approach (I never used them) is to use Github projects

**Comment by rousseldenis** [comment]
> The project icon on github must be the same as in the application.

I agree that as this will be included in all communications, it should be priority

**Comment by rousseldenis** [comment]
> Of cause, each change must be done with a separate PR and, possible, with a separate issue.

+1

**Comment by oleg68** [comment]
@rousseldenis @larspalo are we ready for the making 0.3.1.2342 now?

**Comment by rousseldenis** [comment]
> @rousseldenis @larspalo are we ready for the making 0.3.1.2342 now?

Yes it is. But, wouldn't it be good to go to 0.3.2 to make release a break from the past ?

**Comment by oleg68** [comment]
I'd like to change the versioning AFTER the first release.

**Comment by rousseldenis** [comment]
> I'd like to change the versioning AFTER the first release.

Ok for me

**Comment by larspalo** [comment]
Ok, and then we should drop the meaningless numbering. The only addition should be what commit number of the official source the build comes from.

**Comment by oleg68** [comment]
@rousseldenis I created #27 about changing the versioning

**Comment by rousseldenis** [comment]
> Ok, and then we should drop the meaningless numbering. The only addition should be what commit number of the official source the build comes from.

I agree with that. Usual release flow could embed a whole set of changes (and so, several commits), so, I'd prefer too simpler numbering as <major>.<minor>.<patch>

**Comment by oleg68** [comment]
@rousseldenis please discuss the numbering at  #27, not here.

**Comment by rousseldenis** [comment]
> @rousseldenis please discuss the numbering at #27, not here.

You did it during my message writing...

**Comment by oleg68** [comment]
https://github.com/GrandOrgue/grandorgue/releases/tag/0.3.1.2342-1
