### ISSUE TITLE
Help from the Settings Dialog is covered by the dialog itself.

### ISSUE THREAD

**Issue by oleg68** [GrandOrgue/grandorgue#1004]
When to press Help from the settings dialog, the opened help window is covered with the dialog window

**Comment by paolo2504** [comment]
Correct. Where is the problem ?

**Comment by oleg68** [comment]
The working window should be on top of all non working windows.

The dialog window is not clickable when the help is open. So it shouldn't cover the help window. Instead the help window should cover the dialog.

**Comment by paolo2504** [comment]
> 

thanks Oleg. To say the truth, i dont experience what you say. I open the Settings dialog, click on Help, its dialog opens over but the below dialog is still clickable , selectable and can be navigated. It can also be closed (help dialog in this case stays open.
go r.3611 Windows 10 64b. This is why i asked which problem.

**Comment by paolo2504** [comment]
https://user-images.githubusercontent.com/50132661/153083340-bcfc1f9f-9a03-4f81-aaa5-b3c51e5179b6.mp4

**Comment by oleg68** [comment]
https://youtu.be/ipLdxJ93LBU

**Comment by oleg68** [comment]
This is the root cause: https://stackoverflow.com/questions/7545804/modeless-parentless-wxdialog-still-always-above-wxframe-window-in-z-order
