### ISSUE TITLE
Three bug with organ packages

### ISSUE THREAD

**Issue by paolo2504** [GrandOrgue/grandorgue#1016]
Today i discovered three bugs all related with organ packages. The first one is the most interesting imho, also because usually Windows is not case sensitive. 
Note: after reviewing this post, I must say that probably the point a. Should not be considered a real bug. Just a particular behaviour of the code; for sure unexpected under Windows. 

a. GO fails to load organ packages if the key "Filename" in organindex.ini is written with medium capital letter (File**N**ame instead of File**n**ame). See below screenshot.
b. File/install organ package always opens the folder defined for “Organ Settings” in Settings.
c. GO on startup always looks in organ packages directory for any organ package (this is good). 
   Problem is it takes so long depending on the number of organ packages present (this is not good). In addition, it seems (still not fully tested) that GO makes these check every time, even for packages already registered (for example, for just 4 organs, not even big ones, it takes minutes and minutes...
d. upon loading new organ packages the messages "organ registered successfully" (or something like that) no longer appears as in the past (if i remember well).

![error filename section organ001](https://user-images.githubusercontent.com/50132661/152651739-e662992e-0432-4fc9-b924-d77e7b2b4b08.jpg)

![immagine](https://user-images.githubusercontent.com/50132661/152651827-14db18ec-de82-4228-8f78-ba74a7746b9b.png)

**Comment by paolo2504** [comment]
Some updates on previous points.
a. / b. Confirmed. Nothing to add. 
c. / d. Could be put together I suppose. 
GO is checking organ packages only first time or when they’re changed. 
however, I would strongly suggest some change on how they’re managed. I mean. 

GO automatically checks the package directory if new packages are found. This is very good feature indeed. 
Problem is that GO does not show any message at all before, during and after operation. 
for example , I loaded the big sampleset Cracov. On my “poor” pc (celeron n3060 8 gb ram) it took 15 minutes to parse definition, load sample and creating cache. Each phase is shown in a dialog (see below).
After converting it to package cracov.orgue, I deleted previous organ and all related files then l odes GO and restarted. 

After launch, GO gets working and after 15 minutes (more or less) organ panel is shown. 
this means that GO properly recognises the new package and loads it. All phases are done without any message.
This is not good. 
suppose someone save many .orgue files.. I did try with 3 big samples (cracov,Friesach,Dudla) and after 50 minutes I had to kill GO as I didn’t know what s going on..

Possible suggestions:
1. Flag in Settings to enable/disable automatic check on startup of new package 
2. show progress dialog during new package loading (“loading sampleset”/“creating cache” exactly as it happens when opening organs from directory.

**Comment by willeke1234** [comment]
a: The Help says in the package format Index file specification "It has the same syntax rules as an organ definition file" and about the Grand Orgue file format "The content is case sensitive.".

c/d: Have you tried to use organ packages outside the directory in the settings? For example: the setting "Organ packages" is a path to an empty directory \D:GOPackages and the packages are in \D:GOSampleSets.

**Comment by paolo2504** [comment]
> a: The Help says in the package format Index file specification "It has the same syntax rules as an organ definition file" and about the Grand Orgue file format "The content is case sensitive.".
> 
> c/d: Have you tried to use organ packages outside the directory in the settings? For example: the setting "Organ packages" is a path to an empty directory \D:GOPackages and the packages are in \D:GOSampleSets.

Question is that Windows is a case-insensitive environment so it’s at least strange this behaviour… I found some other proof on this and I’m going to make another post. 

About external directory… ya, of course no issue arise when saving packages outside samplesets folder; however, this makes “organ package directory setting” nonsense…

**Comment by paolo2504** [comment]
I don't know if this request will be accomplished somehow... For the moment, the workaround i used, as suggested by another contributor in this forum, was not to put organ packages ... in the organ package folder !!
This way, when GO opens doesn't check for new and/or modified organ package.
As GO always opens to the latest used directory: this is fine because this way i get what i desire without risking to have GO stuck for hours on looking at possibly new/changed (big) packages.
Definitely: i set a samplesets and an organ packages directory in Settings but i leave them empty, while i save all my .orgue files outside and use that folder that is never checked !
Here below the only way to understand that GO is still "working" if it finds many organs inside the definied folders.
Again, i still recommend to either have a flag to enable/disable package checking on startup and/or have 'Loading sampleset...' / 'Creating cache file..' dialog shown during load.

![go loading big organ package](https://user-images.githubusercontent.com/50132661/153924311-b857e631-b6e4-4226-8f76-b4d2309cd48a.jpg)

**Comment by oleg68** [comment]
@paolo2504

a. All keys in the index file as well as in the ODF are case sensitive, so we won't fix this.
b. I can not reproduce. `File->Install organ package` opens the file selection dialog at the Samplesets (Organs) directory, not at the `Organ settings`.
c. I agree that not rescanning the packages have already registered if their timestamps have not changed would be a reasonable enchancement. Could you create a separate issue for this?
