### ISSUE TITLE
Filename not compatible with case sensitive systems

### ISSUE THREAD

**Issue by paolo2504** [GrandOrgue/grandorgue#1019]
While 'playing' recently with organ packages i found another strange behaviour that i believe it's worth mention.
Warning errors are generated for files whose case does not correspond exactly with the ODF definition file.
I found this reported in an old post #252 by Lars Palo.
What i found new is that the **warning** errors become **fatal** if the organ is loaded as a packaged organ.
I found this while loading Pekela sampleset found on mps-orgelsite: it gives many warnings but then loads. However, after wavpacking the sampleset and converting it to single file .orgue package, it gives fatal errors and aborts.
I became crazy until i noticed subfolders are written in capital case while the ODF refers to them as propercase.

Windows is case-insensitive OS (as mentioned in post #252) so it would not be an issue. This is true unless the organ is loaded as a package: in this case we get fatal errors and the organ is not successfully loaded. I had to renamse the subfolders in propercase and repackage the sampleset to make it work. Here below some screenshots. Hope this helps.

![Pekela folder original uppercase](https://user-images.githubusercontent.com/50132661/152850376-597894ac-2dbf-4f9b-a93a-95645386e79a.jpg)
![Pekela folder renamed propercase](https://user-images.githubusercontent.com/50132661/152850407-2bc41f7e-ef84-4b47-b2d0-c3e459de2c4c.jpg)
![Pekela error loading package](https://user-images.githubusercontent.com/50132661/152850429-692090ac-a192-44c0-9e98-1be7fc498f2f.jpg)

Fatal errors upon loading organ from package: abort because file doesnt exist.
07/02/2022 14:47:27: 14:47:27: Error: File 'Ped\Subbas16\036-C.wav' does not exists
07/02/2022 14:47:27: 14:47:27: Error: File 'Ped\Subbas16\037-C#.wav' does not exists
07/02/2022 14:47:27: 14:47:27: Error: File 'Ped\Subbas16\038-D.wav' does not exists
............
............

Warning errors upon loading organ from directory: success; files are loaded with warning.
07/02/2022 14:57:16: 14:57:16: Warning: Invalid integer value at section 'Manual000' entry 'Stop001': 001	;Subbas 16
07/02/2022 14:57:16: 14:57:16: Warning: Filename 'Ped\Subbas16\036-C.wav' not compatible with case sensitive systems
07/02/2022 14:57:16: 14:57:16: Warning: Filename 'Ped\Subbas16\037-C#.wav' not compatible with case sensitive systems
07/02/2022 14:57:16: 14:57:16: Warning: Filename 'Ped\Subbas16\038-D.wav' not compatible with case sensitive systems
............
............

**Comment by oleg68** [comment]
The reason why is that the package itself is a case-sensitive system and it is intended to be portable between different systems.

So I'd suggest you put the directories in correct cases.

**Comment by rousseldenis** [comment]
> The reason why is that the package itself is a case-sensitive system and it is intended to be portable between different systems.
> 
> So I'd suggest you put the directories in correct cases.

Yep, I confirm that is normal behaviour

**Comment by paolo2504** [comment]
acknowledge. 
Nevertheless, i think this could be fine in linux systems but it becomes a possible issue in case-insensitive os like Windows.
I mean, nobody should honestly expect a fatal error in Windows due to the case of filename/folders. In windows it doesn't matter how they are written...
