### ISSUE TITLE
Dialog position and sizes not maintained

### ISSUE THREAD

**Issue by paolo2504** [GrandOrgue/grandorgue#1035]
hi developers, this not big issue just a nice to have request maybe.
"Settings" and "Load" dialogs sizes and positions are not maintained. On reopening, they revert to defaults.
Is it possible to save size and position ?
tks.

**Comment by paolo2504** [comment]
Just to show this behaviour...

https://user-images.githubusercontent.com/50132661/154731722-18f00eb1-45e6-4b7d-bae4-fcd871ff41e5.mp4

**Comment by oleg68** [comment]
Not only the organ selection dialog, but the positions of any dialog was never saved. Every time the dialog opens in it's original position.

So this issue is a feature request for saving all dialog positions as well as the panel positions.

**Comment by eturpault** [comment]
With which Linux distribution the dialog position and sizes are maintained with GO v3.13.0-1 ?
Or is this evolution applied to the dialog windows only and not to the panel windows ?
With Ubuntu the panels position and size are not maintained, is it normal ?

**Comment by oleg68** [comment]
@eturpault 

This issue relates only dialogs. Panels arestill maintained asthey were maintained before.

Sizes are maintained in any linux. But saving positions work only with xorg windows manager and doesn't work with wayland due the restriction of this window manager.
