### ISSUE TITLE
Settings, Organs, Down button doesn't work.

### ISSUE THREAD

**Issue by willeke1234** [GrandOrgue/grandorgue#1049]
The down button in the Organs tab of the Settings window doesn't work. The Up button moves the selected organ up but the Down button moves the selection down and the organ doesn't move.

**Comment by paolo2504** [comment]
i confirm the same under windows 10.

In addition i see that Top pushbutton does move organ at the top; however the focus remains on the current selection.
I would expect more logical to move focus at the top.
