### ISSUE TITLE
Known incorrect sRGB profile - which image?

### ISSUE THREAD

**Issue by ahall41** [GrandOrgue/grandorgue#1063]
I'm getting this message from an ODF I have created based on the HW XML. GrandOrgue doesn't tell me which image is causing it (which would be helpful, although everything appears to display correctly).

**Comment by oleg68** [comment]
@ahall41 could you post here the whole message text?

**Comment by ahall41** [comment]
In the Log messages, e.g: `Thu 03 Mar 2022 12:31:51 GMT: 12:31:51: Warning: iCCP: known incorrect sRGB profile`
If you need an example, use [this ODF](https://mps-orgelseite.de/home/filebase/index.php?file/108-go-odf-for-avo-demo-romantic-organ-from-ada-serbia-vojvodina/) with the [Ada](https://hauptwerk-augustine.info/Ada.php) demo set.

**Comment by oleg68** [comment]
Could you copy the ODF here? I can not login to the site.

**Comment by ahall41** [comment]
Sorry, didn't realise you need to.
[Ada.zip](https://github.com/GrandOrgue/grandorgue/files/8178610/Ada.zip)

**Comment by ahall41** [comment]
@oleg68 - Many thanks. At least I now know which images are causing it. Looks like it is being reported by libbpng. To fix the images see [this article](https://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile).
