### ISSUE TITLE
"Empty" divisional setter buttons

### ISSUE THREAD

**Issue by ahall41** [GrandOrgue/grandorgue#1068]
When setting Divisional combinations, if the combination has no associated elements, the button (still) shows as raised when selected. (Compare with General combination store, where the button shows as depressed).

**Comment by oleg68** [comment]
@ahall41 I can not reproduce the problem. Could you provide a video?

**Comment by ahall41** [comment]
Please follow these steps. First you need an ODF without any generals defined (such as [Stiehr Mockers](https://www.jeuxdorgues.com/files/jeuxdorgues2_grandorgue.rar)). The behaviour for setting
- Open the sample set (with "Set to default" settings)
- With default settings, no Divisional or General combination can be selected (either from the console or from the Divisional/General panels)
- Without any stops selected, set General combination 1 (using the Generals panel)
- Now select a few stops
- In the Generals panel, you can now select generals 2 through 50, but they have no effect on the stops. Select General 1 and this will unselect all the stops.
- Open the Divisionals panel. You cannot set an "empty" combination - which is inconsistent.
- Select a few stops and set Divisional 1 (on each manual)
- You can now only select the 1st divisional combination (selecting the others clears the button, but has no effect on the others).
- **On the Generals**, I would expect to be unable to select a combination which isn't defined (as per Divisionals). However this is inconsistent with the sequencer (selecting an undefined sequence will reset all your stops)
- **On the Divisionals**, it should be possible to set an "empty" combination

Incidentally, the console buttons for the Stiehr Mockers ODF appear to be inconsistent in operation too (they appear to unset the selected stops). I assume this is a "feature" of the ODF? I only picked it as an example which doesn't take for ever to download.
