### ISSUE TITLE
Saving settings on unload

### ISSUE THREAD

**Issue by ahall41** [GrandOrgue/grandorgue#1069]
According to Help, for Divisional and General combination store: "All configuration done on this panel can be saved to the current preset number. If not, GrandOrgue always asks to save on sampleset unloading."
This does not happen! You have to always remember to save the settings after making changes.
While the quicker option may be to correct the documentation, it would be better (long term) for GO to prompt (at the least) if any settings have changed?

**Comment by paolo2504** [comment]
True. And agree on long term proposal.
