### ISSUE TITLE
Send MIDI event to Any device

### ISSUE THREAD

**Issue by willeke1234** [GrandOrgue/grandorgue#1097]
GrandOrgue 3.4.2-0 sends a MIDI event to all connected devices if the device is set to Any. The Help says "If a device is selected in the dropdown, GrandOrgue outputs that event only to that device. If no device is selected, GrandOrgue outputs that event to all selected output devices ( in the Midi Devices Tab) connected to the computer.". GrandOrgue 3.6.3-1 still sends the event to all devices but refuses to accept device Any in the Midi Event Editor. I get "Invalid MIDI event. Output device is not selected. Select one, set the type to None or delete this event.". Is this a bug or a feature? If it's a feature then the Help is outdated.

**Comment by oleg68** [comment]
Iyt seems a bug. The capability of sending to all device was broken.
