### ISSUE TITLE
No longer XDG compilant

### ISSUE THREAD

**Issue by dliw** [GrandOrgue/grandorgue#1100]
Since commit https://github.com/GrandOrgue/grandorgue/commit/d3fc0dd2481687463ba89f6dbcb6a81707ef3d98 GrandOrgue no longer follows the xdg standard even if compiled with wx > 3.1. Older settings are not loaded any more.

On Linux cache should be in `~/.cache` and settings in `~/.config`. Everything else can be in the user document folder (as configured). Please restore the old behavior.

**Comment by oleg68** [comment]
This change has been made because it was too difficult for users to clean the cache and settings. You can reconfigure the settings directories as you want.

**Comment by dliw** [comment]
Sorry, but I can not. Configuration will be in `~/GrandOrgueConfig` now, which is not XDG compilant. And this cannot be changed. Also, as mentioned, existing settings in `~/.config` are no longer read.
As for the cache: isn't there a way to clear the cache in the GUI?

Anyway, seems I have to patch the code myself.

**Comment by oleg68** [comment]
> Sorry, but I can not. Configuration will be in `~/GrandOrgueConfig` now, which is not XDG compilant. And this cannot be changed. Also, as mentioned, existing settings in `~/.config` are no longer read. 

GrandOrgueConfig has never been in  ~/.config directory, it always was in the user home directory. The commit you mentioned did not change the placement of the main config file.

> As for the cache: isn't there a way to clear the cache in the GUI?

File->Delete Cache... clears it for one (current) organ. But there is a discussion #955 about reworking some UI including a capability of clearing the cache of several (or for all) organs.

**Comment by dliw** [comment]
Not true. Version 3.1.2337 with wx > 3.1.1 worked as expected. This has changed in commit https://github.com/GrandOrgue/grandorgue/commit/b16a2ee950a606b7d9267779ad64405c843e5c6c (hint: the position of `GOrgueStdPath::InitLocaleDir` has changed).

I will use [this patch](https://github.com/GrandOrgue/grandorgue/files/8365377/fix-xdg.diff.txt) for [this package](https://build.opensuse.org/package/show/multimedia:proaudio/grandorgue), so people don't lose their settings.
