### ISSUE TITLE
Names of temperaments do not get translated

### ISSUE THREAD

**Issue by kerkovits** [GrandOrgue/grandorgue#1104]
Names of temperaments do not get translated regardless of the chosen language. Is this the intentional behaviour?

**Comment by oleg68** [comment]
Yes, it is. Most names are the same in all languages so there is no reason to translate them.

**Comment by willeke1234** [comment]
It looks like a bug to me. The names of the temperaments were translated, are in the .po files and are still translated but before the language setting is read. In `GOrgueApp::OnInit()` the language was set before and is now set after `m_Settings->Load()` where the list of temperaments is created.

**Comment by kerkovits** [comment]
I see the point, but present situation is quite unclear for translators. All names of temperaments are marked by macro `WX_TRANSLATE`, suggesting that they should be translated. If the developers want that this must not get translated, the translation macro should be removed from the source code.

**Comment by rousseldenis** [comment]
> I see the point, but present situation is quite unclear for translators. All names of temperaments are marked by macro `WX_TRANSLATE`, suggesting that they should be translated. If the developers want that this must not get translated, the translation macro should be removed from the source code.

@oleg68 Indeed, temperaments are translatable. Shouldn't this be addressed through #1139. Even if temperament names are equal, some locals could have some specific characters. I see also some that should be translated as 'Kellner's Bach tuning' - 'tuning' is a normal word.

**Comment by rousseldenis** [comment]
@kerkovits @oleg68 Temperaments are well translated in last version. So, nothing to change

See in French:

![image](https://user-images.githubusercontent.com/19529533/182395608-65ecbc94-cdd5-4def-8c67-5eb0febcc5d1.png)

**Comment by kerkovits** [comment]
> @kerkovits @oleg68 Temperaments are well translated in last version. So, nothing to change
> 
> See in French:
> 
> ![image](https://user-images.githubusercontent.com/19529533/182395608-65ecbc94-cdd5-4def-8c67-5eb0febcc5d1.png)

@rousseldenis @oleg68 This makes it even more spurious. This shows that the translated names of temperaments are known by the program, but they are not applied in the main window. Check the submenu Sound/Midi->Temperaments. It is in English. https://github.com/GrandOrgue/grandorgue/pull/1139 would correct this bug by loading the system locale before initializing the temperaments, but it introduces a regression that the language set in the Settings panel is not respected. In my opinion, the locale object should be initialized before loading the predefined temperaments but after reading the configuration files.
