### ISSUE TITLE
ALL Settings lost.... ;-(

### ISSUE THREAD

**Issue by mattrixed** [GrandOrgue/grandorgue#1118]
Was running 3.6.5-3 pre and last night updated to 3.6.5-1 released - updated fine.  Loaded sampleset and all well.

Started up pc and loaded tonight - crashed... not unusual on first start sometimes....

Restarted and error something about missing line.. i should have taken a photo of the error sorry...
And once in everything gone.  All mappings, mutichannel setup All settings everything!  Every single thing reset back to blank start of an install no organs available nothing....

I used to think there was a backup file somewhere located in a folder?  But i can't find it all folders in documents are empty.  And looking in program files theres nothing in there other than normal GO files.

Of course this all happened minutes before i was due on "live" to play for a service....
I quickly loaded up a sampleset mapped the manuals and pedal board and re-created the required outputs for the different outputs going to in room, organ, and mixer for over the air.... thankfully i have a touch screen so was able to adjust stops for the service and get something out....!

Any thoughts before i re-do it all again all the launch pad buttons 50+ every combination i had stored and setting let alone 10+ organs all installed and their settings....?

Regards,
Matt

**Comment by oleg68** [comment]
@mattrixed GrandOrgue stores its configuration file in the `UserDirectory`\AppData\Roaming directory. There config file is named `GrandOrgueConfig`. But it is changed only when you exit with `OK` from the Setting window. If GrandOrgue crashes then it doesn't change it. May be this file gets corrupted in the file system by some reason and it causes GO crashing.

Every time `GrandOrgueConfig` is changed the backup copy `GrandOrgueConfig.last` is created in the same dir. So if you eventually destroy your settings you can restore them by copying from the old file.

Unfortunally now I can nothing do with crashes in the past until #853 is completed. I only can debug the reproducible crashes. Please reopen this issue if GO crashes again.
