### ISSUE TITLE
Reorganise the Organs tab in Settings

### ISSUE THREAD

**Issue by oleg68** [GrandOrgue/grandorgue#1119]
Now (3.6.6) the Organ tab in settings contains two tables quite similar tables that is confusing. There are some ideas of reworking this tab in #955. It is a time to implement them. It should also resolve a lot of issues: #700, #886, #950, #1049.

**Comment by paolo2504** [comment]
Sure. The two tables like they are today are confusing. However I guess it’s not just a matter of reworking/rearranging them. I think   there is something more complex to think.
