### ISSUE TITLE
GO v3+  crashes on startup

### ISSUE THREAD

**Issue by dj3647** [GrandOrgue/grandorgue#1133]
GO v3 and later won't start & crashes immediately (windows 10 64bit).  I think the problem is related to Jack audio.  On version 2330, GO behaves the same way & won't start IF jack is running.  If jack is not running & I'm using another driver, GO works fine.  JackRouter works fine on the previous versions of GO, but not v3.  I can't get any later versions to run at all no matter what I do  Any ideas ???   Thanks!

**Comment by oleg68** [comment]
May be creating the crush dumps is disabled in your system. Please take a look at https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps end enable it.

**Comment by dj3647** [comment]
I added the following to the registry to enable crash dumps...but does not work.  Is this correct for windows 10?  The folder "CrashDumps" still does not appear in "...\AppData\Local".  Also, I could try to add a video of what happens when GO windows 3.6.7 tries to start.  Thanks for the quick responses,

![registry](https://user-images.githubusercontent.com/106124021/170161177-264adfa5-87b7-40c4-a004-c2ceeb1853a2.jpg)

**Comment by willeke1234** [comment]
The macOS version of GrandOrgue 3.6.7 also crashes on startup:

```
dyld: Library not loaded: /usr/local/opt/gcc/lib/gcc/11/libgcc_s.1.1.dylib
  Referenced from: /Volumes/Macintosh HD/Users/willeke/Downloads/GrandOrgue.app/Contents/Frameworks/libgcc_s.1.dylib
  Reason: image not found
```

**Comment by oleg68** [comment]
> The folder "CrashDumps" still does not appear in "...\AppData\Local"

May be it does not crash but exits normally by some reason?

Could you run GrandOrgue.exe from the command line with output redirection

```
GrandOrgue.exe >output.txt 2>err.txt
```

and post here `output.txt` and `err.txt`?

**Comment by oleg68** [comment]
Maybe something is wrong in the grandorgue settings.

Please try to do:
1. Rename the settings file c:\users\`UserName`\AppData\Roaming\GrandOrgueConfig to c:\users\`UserName`\AppData\Roaming\GrandOrgueConfig.save
2. Run GrandOrgue from the scratch. Does it crash?

**Comment by dj3647** [comment]
GO still crashes. I renamed the files "GrandOrgueConfig", "GrandOrgueConfig.last", & "GrandOrgueConfigperftest" as well as the folder GrandOrgueData.  Same results -- GO crashes.  I have created some Virtual Audio Cables in the past (with Reaper, I think) so I could have several audio sources running at the same time in Windows10.  I can't remember the details now....Could this be the cause?

**Comment by oleg68** [comment]
Unfortunally I can do nothing without the crash dump.

Could you post a screen video with this crash?

**Comment by oleg68** [comment]
Please provide a crash dump or at least a video.

**Comment by dj3647** [comment]
Dear Oleg,

I found the solution to Grandorgue crashing (2 years later!).  After upgrading “Jack” to “Jack2 v1.9.22” for Windows 64 bit, I can now run the latest versions of Grandorgue.  Hope this helps others. Thank you for your help.  This is regarding Issue #1133.

Dave
