### ISSUE TITLE
GrandOrgue 3.6.7 on macOS crashes on startup

### ISSUE THREAD

**Issue by willeke1234** [GrandOrgue/grandorgue#1135]
GrandOrgue 3.6.7 on macOS crashes on startup:

```
dyld: Library not loaded: /usr/local/opt/gcc/lib/gcc/11/libgcc_s.1.1.dylib
  Referenced from: /Volumes/Macintosh HD/Users/willeke/Downloads/GrandOrgue.app/Contents/Frameworks/libgcc_s.1.dylib
  Reason: image not found
```

**Comment by oleg68** [comment]
The reason: the new gcc 11.3.0_1 that is used during the build requires the file `libgcc_s.1.1.dylib` that is not packed to the GrandOrgue bundle.

Try to use the workaround: 

1. Create a directory /usr/local/opt/gcc/lib/gcc/11
2. unpack this dylib from [libgcc_s.1.1.zip](https://github.com/GrandOrgue/grandorgue/files/8790879/libgcc_s.1.1.zip) to this directory
3. Grant the executable rights:
```
chmod go+rx /usr/local/opt/gcc/lib/gcc/11/libgcc_s.1.1.dylib
```
4. Run GrandOrgue

I'll try to fix packing the bundle to add this file in the bundle

**Comment by oleg68** [comment]
The root cause of this problem is

1. Changes in `libgcc_s.1.dylib`: now it uses `libgcc_s.1.1.dylib` as `reexport`:

2. A bug in cmake https://gitlab.kitware.com/cmake/cmake/-/issues/23826 that it does not handle `reexport` correctly.

**Comment by oleg68** [comment]
@willeke1234 @vpoguru Could you try [the intermediate build](https://github.com/oleg68/GrandOrgue-official/suites/7702997871/artifacts/322166508)?

**Comment by willeke1234** [comment]
Problem solved, thank you.
