### ISSUE TITLE
GrandOrgue release for Apple chips

### ISSUE THREAD

**Issue by Gabriele993** [GrandOrgue/grandorgue#1142]
Hello everyone!

I am a very happy user of GrandOrgue software. 
I want to ask if there's a version of GrandOrgue in the works
for Apple chips, since it seems that there's only the Intel version
available in the repository. 
Thanks in advance for your patience.
       Gabriele

**Comment by oleg68** [comment]
Unfortunally we aren't able to build Grandorgue for Apple chips due the lack of its support on GitHub. See https://github.com/actions/runner-images/issues/2187 for details.

But any intel version should work on apple chips with `Rosette`.

The last working version is 3.6.6. 

3.6.7 doesn't work on OSx due the #1135 bug.

3.7.0 is comming soon and it works on OSx again.
