### ISSUE TITLE
GrandOrgue crashes immediately on startup under macOS X Ventura

### ISSUE THREAD

**Issue by vpoguru** [GrandOrgue/grandorgue#1150]
GrandOrgue crashes immediately on startup under macOS X Ventura (Beta 4 and earlier). This applies to both processor platforms, Intel and ARM. I also tried two 3.7.0 builds. Same issue.

I attach both crash reports.

[GrandOrgue_CrashReports.zip](https://github.com/GrandOrgue/grandorgue/files/9275577/GrandOrgue_CrashReports.zip)

**Comment by willeke1234** [comment]
Same issue as #1135. If I remove `GrandOrgue.app/Contents/Frameworks/libgcc_s.1.dylib` then GrandOrgue will start (on macOS 10.15).

**Comment by vpoguru** [comment]
Yes, I can confirm that this solves the problem.

**Comment by oleg68** [comment]
Duplicates: #1135
