### ISSUE TITLE
Crescendo pedal removes actual stops

### ISSUE THREAD

**Issue by krgrwrg** [GrandOrgue/grandorgue#1170]
**Problem**
* Crescendo pedal works different like on Hauptwerk. 
* Current behaviour : Instead of adding stops to current preset it changed my preset
* Expected behaviour :
** New stops will be added or removed when crescando value is changing.
** My stops activated before changing of crescendo value will stay unchanged

**Example**
* Crescendo pedal value : 0
* Stops activated : 32/32
* Crescendo pedal value : 1
* Stops activated : 3/32
* Crescendo pedal value : 32
* Stops activated : 32/32
* Crescendo pedal value : 1
* Stops activated : 3/32
* Crescendo pedal value : 0
* Stops activated : 3/32

**Comment by oleg68** [comment]
@larspalo This behavior can be changed, but I'm not sure which behavior is right. What is your opinion? Should crescendo remove only the stops that were only added with it?

**Comment by larspalo** [comment]
The main problem would be that in the real world you can find examples of both behaviors - Crescendos that overrides any current active manual selection, and crescendos respecting any existing manual selection. In my opinion the best solution would be to add another button on the Crescendo pedal that for each selected crescendo (A-D) individually would specify the "override mode" for that (and only that) crescendo.

**Comment by krgrwrg** [comment]
I think correct behaviour is "override mode", because of crescendo pedal is for 'boost volume' by activating more stops than are current set.
In 3.X version of software is changing default behaviour of something what users may using for years wrong decision.
By my opinion, the best solution is to add button "override mode" - disabled by default to keep backward compatibility.

**Comment by oleg68** [comment]
@larspalo @krgrwrg 

Where should I put this button on the Crescendo Panel?

![image](https://user-images.githubusercontent.com/11586506/189518311-f89d716b-be32-4bd7-bc98-ca4844a01bc1.png)

**Comment by oleg68** [comment]
@krgrwrg Could you test the `Override` button on the crescendo panel in the intermediate build https://github.com/oleg68/GrandOrgue-official/actions/runs/3039571990

Does it satisfy your needs?

**Comment by krgrwrg** [comment]
> @krgrwrg Could you test the `Override` button on the crescendo panel in the intermediate build https://github.com/oleg68/GrandOrgue-official/actions/runs/3039571990
> 
> Does it satisfy your needs?

Sorry, i was on vacation without laptop in mountains. I will test this new feature during weekend. Thank you for implementation.

**Comment by krgrwrg** [comment]
> @krgrwrg Could you test the `Override` button on the crescendo panel in the intermediate build https://github.com/oleg68/GrandOrgue-official/actions/runs/3039571990
> 
> Does it satisfy your needs?

I was tested your build just now.
Pedal is working as wanted but i have 2 notes:
* current preset ( general ) is not lighted as active when i using crescendo pedal
** is little bit confusing - i don't know which piston is activated
* when in switch between presets ( generals ) crescendo is ignored, but when i move it up or down, sound is changed.
** when i forgot to move crescendo pedal down before i swap between presets it produced unwanted sounds ( especially when i move it down to zero value ).
