### ISSUE TITLE
Cannot enable reverb

### ISSUE THREAD

**Issue by IonicaBizau** [GrandOrgue/grandorgue#1176]
First of all, thank you for building this amazing project! 🌟 

I would like to set the reverb and I remember once I did it. However, I cannot seem to be able to do that anymore...

I installed GO 3.7.1-1 on my Windows 11 machine:

<img width="445" alt="image" src="https://user-images.githubusercontent.com/2864371/188501028-43e94f10-fb36-4325-ae3c-825ce3ae25c1.png">

**Comment by oleg68** [comment]
This is just a warning, not an error. You can ignore it by pressing on `OK`. After that the reverb should work

**Comment by IonicaBizau** [comment]
Well, but then I am getting the following error:

<img width="431" alt="image" src="https://user-images.githubusercontent.com/2864371/188503491-19cdef82-93c5-4ccf-aa35-2007aee3005a.png">

**Comment by oleg68** [comment]
You have to download a valid impulse response file and to specify it's path for using this feature.

**Comment by IonicaBizau** [comment]
@oleg68 Where should I download it from more exactly? I tried following [this thread](https://github.com/GrandOrgue/grandorgue/issues/983#issuecomment-1025187695), but the reverb is very distorsed... Is there any other impulse response file I can download? Thank you!

**Comment by rousseldenis** [comment]
@IonicaBizau You can check this : https://github.com/GrandOrgue/grandorgue/wiki/Impulse-Responses

You can find also free Impulse Responses from the web. You can test them also and pick the one that fits your needs

**Comment by IonicaBizau** [comment]
@rousseldenis Thank you very much for that! I downloaded those for `Bureå church`, but unfortunatelly the same thing happens: when enabling Convolution Reverb, the sound is distorted.

Is there any alternative for setting up the reverb and not use _Convolution Reverb_?

**Comment by rousseldenis** [comment]
> @rousseldenis Thank you very much for that! I downloaded those for `Bureå church`, but unfortunatelly the same thing happens: when enabling Convolution Reverb, the sound is distorted.
> 
> Is there any alternative for setting up the reverb and not use _Convolution Reverb_?

Usually, sample sets include their own reverberation except of course the 'Dry' ones.

So, usually you don't need it for most sample sets.

Which one do you use ?

Maybe that can also be the GrandOrgue settings for latency

**Comment by IonicaBizau** [comment]
I currently using the `Bureå church` set and it works nicely, but I would like more reverb than it has by default. 

This is a note where the note is clearly distorted (only in the right speaker), when using the inpulse response files:

<img width="914" alt="image" src="https://user-images.githubusercontent.com/2864371/188579703-ac901be9-08f1-47cd-9845-4cf48a545da6.png">

**Comment by IonicaBizau** [comment]
Lowering the volume to around `-20`, or even more depending on the registers I am using seem to work nicely. At some point the reverb is reset, tho... I will keep an eye on it to see when that happens more exactly.

Thank you very much.
