### ISSUE TITLE
How can I make GrandOrgue "remember" my latest configuration?

### ISSUE THREAD

**Issue by IonicaBizau** [GrandOrgue/grandorgue#1177]
Every time when I start Grand Orgue, I have to set up again everything from scratch: manual 1, manual 2, pedalboard, registers.

This takes a lot of time and would like to simply save somehow the configuration and load it whenever I want to play the organ.

[This is my setup](https://ionicabizau.net/blog/43-ive-built-a-digital-organ-and-this-is-what-i-learned), basically three MIDI controllers which are connected to the computer always (so their ID do not really change).

How can I reload the latest config when I start GO? Thanks! 🎹

**Comment by rousseldenis** [comment]
> Every time when I start Grand Orgue, I have to set up again everything from scratch: manual 1, manual 2, pedalboard, registers.
> 
> This takes a lot of time and would like to simply save somehow the configuration and load it whenever I want to play the organ.
> 
> [This is my setup](https://ionicabizau.net/blog/43-ive-built-a-digital-organ-and-this-is-what-i-learned), basically three MIDI controllers which are connected to the computer always (so their ID do not really change).
> 
> How can I reload the latest config when I start GO? Thanks! musical_keyboard

You can do it by menu 'File > Save Settings'.

I suppose you are beginning with GrandOrgue. Is suggest you to go through Help ('Help > Help' menu).

You can also go through wiki : https://github.com/GrandOrgue/grandorgue/wiki

**Comment by IonicaBizau** [comment]
`File > Save` worked indeed! I have been using an older version of GO and did not check this after upgrading. Thank you!
