### ISSUE TITLE
Crescendo pedal

### ISSUE THREAD

**Issue by cadupalmieri** [GrandOrgue/grandorgue#1180]
Some organs has the crescendo pedal function but if you use, the stops on the crescendo level overwrite all the stops selected manual or from a combination, the correct form is the crescendo add the stops plus the stops that already are on.  But if you return the crescendo to a level more weak then the manual or combination set before they desactivate. 

I thinks this is a problem of grand orgue,  and not about the sample Right ?

**Comment by oleg68** [comment]
Duplicates #1170
