### ISSUE TITLE
Export combinations separate from the organ settings

### ISSUE THREAD

**Issue by oleg68** [GrandOrgue/grandorgue#1195]
Now combinations are saved in the same .cmb file as the organ settings. It rases several problems:

1. The menu entries `Import Settings` and `Import Combinations` are the neighbors, so they can be refused. I a user select `Import Settings` by mistake `instead of Import Combinations`, the organ settings will be overriten and it will take a lot of time.
2. The combination file is not human-readable so it cann't be used as a base for setting combinations on a different organ.

The idea is to export combinations only to a separate file in yaml format. Theese files would be stored in a separate folders GrandOrgue/combinations/, separated by organ names for preventing confusing.

**Comment by oleg68** [comment]
@larspalo @rousseldenis 

This in an example of yaml-file with combinations saved:

```
info:
  organ-name: Oleg Home, op. 2
  grandorgue-version: v3.11.0-0.local
  saved-time: Sat 11 Mar 2023 21:10:29 MSK
sequencer:
  001:
    manuals:
      000:
        name: Pedal
        stops:
          001: PrincipalBass 16'
          002: Octavbass 8'
          003: Subbass 16'
          005: Posaune 16'
          007: Dry Gedacktbass 8'
          009: Superoctavbass 4'
          011: Pommer 4'
          017: Untersatz 32'
        couplers:
          002: III/P
          003: II/P
      001:
        name: Hauptwerk
        stops:
          001: Montre 8'
          002: Roerfluit 8'
          005: Mixtura
          006: Principal 8'
          007: Octava 4'
          008: Superoctava 2'
          014: Quinta 2 2/3'
          018: Bordun 16'
          019: Bourdon 8'
      002:
        name: Brustwerk
        stops:
          001: Geigenprincipal 4'
          004: Viola Pomposa 8'
          005: Rohrfloete 4'
          012: Gedackt 8'
          017: Geigenprincipal 8'
          018: Salicette 4'
      003:
        name: Oberwerk
        stops:
          005: Orchesterfloete 4'
          008: Doppel Gedackt 8'
          014: Piccolo 2'
        couplers:
          001: 4' III
  002:
    manuals:
      000:
        name: Pedal
        stops:
          001: PrincipalBass 16'
          002: Octavbass 8'
          003: Subbass 16'
          007: Dry Gedacktbass 8'
          011: Pommer 4'
          017: Untersatz 32'
        couplers:
          003: II/P
      001:
        name: Hauptwerk
        stops:
          001: Montre 8'
          002: Roerfluit 8'
          005: Mixtura
          006: Principal 8'
          007: Octava 4'
          008: Superoctava 2'
          014: Quinta 2 2/3'
          018: Bordun 16'
          019: Bourdon 8'
      002:
        name: Brustwerk
        stops:
          001: Geigenprincipal 4'
          004: Viola Pomposa 8'
          005: Rohrfloete 4'
          012: Gedackt 8'
          017: Geigenprincipal 8'
          018: Salicette 4'
      003:
        name: Oberwerk
        stops:
          005: Orchesterfloete 4'
          008: Doppel Gedackt 8'
          014: Piccolo 2'
        couplers:
          001: 4' III
  003:
    manuals:
      000:
        name: Pedal
        stops:
          001: PrincipalBass 16'
          002: Octavbass 8'
          003: Subbass 16'
          007: Dry Gedacktbass 8'
          011: Pommer 4'
        couplers:
          003: II/P
      001:
        name: Hauptwerk
        stops:
          001: Montre 8'
          002: Roerfluit 8'
          005: Mixtura
          006: Principal 8'
          007: Octava 4'
          008: Superoctava 2'
          012: Viola di Gamba 8'
          014: Quinta 2 2/3'
          016: Gemshorn 8'
          018: Bordun 16'
          019: Bourdon 8'
      002:
        name: Brustwerk
        stops:
          001: Geigenprincipal 4'
          004: Viola Pomposa 8'
          005: Rohrfloete 4'
          012: Gedackt 8'
          017: Geigenprincipal 8'
      003:
        name: Oberwerk
        stops:
          005: Orchesterfloete 4'
          008: Doppel Gedackt 8'
          014: Piccolo 2'
  004:
    manuals:
      000:
        name: Pedal
        stops:
          001: PrincipalBass 16'
          002: Octavbass 8'
          003: Subbass 16'
          007: Dry Gedacktbass 8'
          011: Pommer 4'
        couplers:
          002: III/P
          003: II/P
      001:
        name: Hauptwerk
        stops:
          001: Montre 8'
          002: Roerfluit 8'
          005: Mixtura
          006: Principal 8'
          007: Octava 4'
          008: Superoctava 2'
          012: Viola di Gamba 8'
          014: Quinta 2 2/3'
          016: Gemshorn 8'
          018: Bordun 16'
          019: Bourdon 8'
      002:
        name: Brustwerk
        stops:
          001: Geigenprincipal 4'
          004: Viola Pomposa 8'
          005: Rohrfloete 4'
          006: Nasat 2 2/3'
          011: Prinzipal 2'
          012: Gedackt 8'
          015: Cimbel
          017: Geigenprincipal 8'
        couplers:
          001: III/II
      003:
        name: Oberwerk
        stops:
          005: Orchesterfloete 4'
          008: Doppel Gedackt 8'
          014: Piccolo 2'
  005:
    manuals:
      000:
        name: Pedal
        stops:
          001: PrincipalBass 16'
          002: Octavbass 8'
          003: Subbass 16'
          007: Dry Gedacktbass 8'
          011: Pommer 4'
        couplers:
          001: I/P
          002: III/P
          003: II/P
      001:
        name: Hauptwerk
        stops:
          001: Montre 8'
          002: Roerfluit 8'
          005: Mixtura
          006: Principal 8'
          007: Octava 4'
          008: Superoctava 2'
          012: Viola di Gamba 8'
          014: Quinta 2 2/3'
          016: Gemshorn 8'
          018: Bordun 16'
          019: Bourdon 8'
      002:
        name: Brustwerk
        stops:
          001: Geigenprincipal 4'
          004: Viola Pomposa 8'
          005: Rohrfloete 4'
          006: Nasat 2 2/3'
          011: Prinzipal 2'
          012: Gedackt 8'
          015: Cimbel
          017: Geigenprincipal 8'
        couplers:
          001: III/II
      003:
        name: Oberwerk
        stops:
          005: Orchesterfloete 4'
          008: Doppel Gedackt 8'
          014: Piccolo 2'
  006:
    manuals:
      000:
        name: Pedal
        stops:
          001: PrincipalBass 16'
          002: Octavbass 8'
          003: Subbass 16'
          007: Dry Gedacktbass 8'
          011: Pommer 4'
        couplers:
          002: III/P
          003: II/P
      001:
        name: Hauptwerk
        stops:
          001: Montre 8'
          002: Roerfluit 8'
          006: Principal 8'
          007: Octava 4'
          008: Superoctava 2'
          012: Viola di Gamba 8'
          014: Quinta 2 2/3'
          016: Gemshorn 8'
          019: Bourdon 8'
      002:
        name: Brustwerk
        stops:
          001: Geigenprincipal 4'
          004: Viola Pomposa 8'
          005: Rohrfloete 4'
          012: Gedackt 8'
          017: Geigenprincipal 8'
      003:
        name: Oberwerk
        stops:
          005: Orchesterfloete 4'
          008: Doppel Gedackt 8'
          014: Piccolo 2'
```
Empty combinations are not saved.

Now only the current combination and the sequencer (Combination Setter Panel) are exported. I'm going to adding support of generals, divisionals and crescendos too. When it is ready, I'll create a PR.

Import of such yaml combinations will be a subject of a seprate PR.

**Comment by larspalo** [comment]
I think it's absolutely great to separate the combinations from the settings! Not storing everything (empty values) makes for much neater file content too.

Handling of older type settings/combination files must be allowed still in GO - but possibly converting them to the newer format just like with other older type settings on the fly.

Also keep in mind that the odf can specify separate divisionals and generals that also must continue to be handled somehow and not mixed with the built in versions. Some of them could also be intended as fixed combinations not supposed to be possible to edit by the user.

**Comment by oleg68** [comment]
@larspalo I'm planning to continue reading combinations from ODF/CMB. But I'm also going to improve `Import Combinations` to be able to import from both yaml and cmb. But by default it will be open a file dialog starting from Combinations directory where yaml are exported.

I ask you to look at the syntax of the combination yaml file. Do you agree with it? My intention is to make it human readable and also human amendable. That is why I included not only the ODF-indices of objects, but also their names.

Another possible usage of this file is to print it and to use this paper as a basic for making registration of another organs, including real pipe ones. Of cause, the stop layouts are different, but it is better than to have nothing.

**Comment by larspalo** [comment]
> I ask you to look at the syntax of the combination yaml file. Do you agree with it? My intention is to make it human readable and also human amendable. That is why I included not only the ODF-indices of objects, but also their names.

I don't mind changing to such a layout. Maybe I'd be a little concerned that any string name changes should not completely invalidate a file or make it necessary to search and replace all instances of it. But beyond that, I'm ok with such identification help.

In your short example there's only sequencer: as main combination storage. If also odf: with subsections for it's possibly specific divisionals: and generals: as well as the GO builtin functionalities are included, then their saved combinations could too be migrated into a newer combination storage handling. Or did you have other plans for them?

**Comment by oleg68** [comment]
Yes, I'm going to implement storing generals, divisionals and crescendo in the yaml as well as the sequencer.

**Comment by oleg68** [comment]
@larspalo @rousseldenis  I finished implementing export combination in yaml file. Unfortunally I cann't open a PR because there is a large queue of other unmerged PRs I made changes on top on. But you may get an intermediate build from https://github.com/oleg68/GrandOrgue-official/actions/runs/4456231318 and test it.

There are two big things:
1. The new `Combinations` path in `File->Settings->Paths`.
2. The new menu entry `File->Export Combinations` for this functionality. By default, the yaml file are stored not in the `Combinations` directory, but in it's subdirectory with the same name as the organ name. I made so because the export combinations are appropriate only fo this organ and can not be used with other ones, so It is better not to mix combinations from different organs in the same directory.

Import of yaml combinations has not yet implemented. I'm planning to learn `File->Import Combination` to load combinations from both file formats: `cmb` and `yaml`, but it will be done in a separate PR.

**Comment by oleg68** [comment]
@larspalo @rousseldenis I finished implementing export/import yaml combinations, including adoption of the help.

The export-only version is available at https://github.com/oleg68/GrandOrgue-official/actions/runs/4552011624 and it has been submited as #1195 that is waiting for @rousseldenis approval.

The full featured export+import version is available at https://github.com/oleg68/GrandOrgue-official/actions/runs/4578754856. I'll submit a PR just after approval and merging of #1195.

@rousseldenis could you review and approve #1195 for I could submit the import part?. If it is too large for you, I can try to split it to several smaller parts.
