### ISSUE TITLE
Add capability of loading and saving combinations to the `Combination Setter` panel. 

### ISSUE THREAD

**Issue by oleg68** [GrandOrgue/grandorgue#1196]
Now exporting and importing combinations are possible only with a menu.

It would be more convinient to do it with special controls in the `Combination Setter` panel. Hauprtwerk already has a similar capability.

**Comment by oleg68** [comment]
@larspalo @rousseldenis 

I'm trying to add more controls to the sequencer panel.

What variant is better:
![classic](https://user-images.githubusercontent.com/11586506/231866667-92bf16a5-d10b-496f-a9ef-f3ea31b04101.png)

or

![newui](https://user-images.githubusercontent.com/11586506/231866714-48cbdf6d-91ef-458a-b162-8ccd79874d66.png)?

**Comment by larspalo** [comment]
@oleg68 The first one. Not the green icons please.

**Comment by larspalo** [comment]
Becacuse the icons doesn't actually say what the buttons are doing. An arrow right means what... Right? Whereas the text is immediately obvious to anyone that can read. Not to mention that the icons have a style that doesn't match the existing drawstop (buttons) at all.

**Comment by larspalo** [comment]
@rousseldenis In my opinion, if we want to modernize the built-in graphics, it should be done as new additional bitmaps (and using them inside GO by setting new defaults). But they should all be really thought through so that they will harmonize together in a coherent style.

**Comment by oleg68** [comment]
OK, let's choose the first variant.  I'm finishing working on the issue now. The evaluation build is already abvailable at https://github.com/oleg68/GrandOrgue-official/actions/runs/4693356345 .

As soon I adjust the help, I'll open a PR with it.
