### ISSUE TITLE
[bug]MIDI event editor, SYSEX Hauptwerk 32 byte LCD Value, max. length is 31

### ISSUE THREAD

**Issue by willeke1234** [GrandOrgue/grandorgue#1207]
In the MIDI event editor dialog window, if the Event is "SYSEX Hauptwerk 32 byte LCD Value", the maximum value of the length field is 31 instead of 32.
The maximum length of the SYSEX Hauptwerk 16 Byte String Value is 15 instead of 16.

See also: Possible issue with too short SysEx message for controlling hauptwerk displays? #229

**Comment by willeke1234** [comment]
The max lenght is in GOMidiSender::LengthLimit

**Comment by oleg68** [comment]
@willeke1234 Please create a Pull Request with your changes.
