### ISSUE TITLE
Control organ with a touchscreen

### ISSUE THREAD

**Issue by nebuloss** [GrandOrgue/grandorgue#1208]
When you control organ with a touchscreen, you cannot interact properly with the stop pannel. You have to tap several time on the stop to activate or deactivate it. However other panel such as combination panel works properly.

**Comment by oleg68** [comment]
@nebuloss I cann't reproduce it with the Barton organ that has a separate ``Stop View`` panel: the stops are switched with the first tap.

Other organs have stop buttons on the main GUI panel and they are also switched with the first tap.

Could you provide more information: what organ, what panel?

**Comment by nebuloss** [comment]
I am currently using an organ I built  myself from hauptwerk sample sets.
But I have also this issue with the default organ.
However, because the default organ produces sounds when you activate or deactivate stops, I tested if my tap is detected from grandorgue.
It seems that grandorgue detect each tap because it produces  a short sound. The problem might come from the delay allowed between each tap. I think that grandorgue just quickly activate and deactivate the stop.

**Comment by oleg68** [comment]
@nebuloss What happens when you tap a stop with the demo organ? The sound is produced, but the stop remains deactivated, does'n it?

**Comment by nebuloss** [comment]
When I tap a stop with the demo organ, it does not work most of the time. It remains activated or deactivated but it always produces a sound.
However with a mouse click, it works all the time.
My touch screen works perfectly with other apps in my system. 
(I am running the arm64 debian version of grandorgue)

**Comment by oleg68** [comment]
1. What version of GrandOrgue do you use?
2. What desktop environment do you use (gnome, kde, lxde etc)?
3. Are you running on Wayland or on XOrg?
4. Do you have any midi-attached pistons for displaying and controling the stop state?

**Comment by nebuloss** [comment]
To be clear, I am running grandorgue on raspberry pi 4b with 8GB of RAM and an external soundcard.
I have 2 midi keyboard and a midi pedalboard.
I only use keyboard additional buttons to control registrations.
I have plugged one touchscreen to control the computer.
I flashed raspberry pi os 64 bits on the board. It is based on debian 11 (bullseye) and uses lxde as desktop environment and X11 as window server. 
Because the CPU is an arm cortex A72, I have installed the arm 64 debian package of grandorgue.

**Comment by oleg68** [comment]
@nebuloss Thank you for information.

I managed to reproduce this problem with Raspbery Pi. There are problems somewhere between the touchscreen, lxde desktop and GrandOrgue. I will research more.

There are no such problems with the mate desktop. So I suggest you to use mate as a temporary workaround. mate looks similar to lxde-pi/

1. Install mate desktop: ``sudo apt update && sudo apt install -y mate``.
2. Switch to the mate desktop: ``sudo update-alternatives x-session-manager`` and enter the number of the mate from the list displayed.
3. Logout from the current desktop session and log on to another one.
4. Start Grandorgue and try to enable/disable stops with your touchscreen.

**Comment by oleg68** [comment]
@nebuloss I tried to reproduce this problem on Debian 11/intel with LXDE and LightDm. And I cann't reproduce it: GrandOrgue works correctly with the touchscreen. So this isue is **raspbian-specific**.

**Comment by nebuloss** [comment]
@oleg68 thank you for your workaround.
I have installed mate and it works perfectly now.
This touch issue is still weird because other apps works perfectly on Raspbian lxde.

**Comment by oleg68** [comment]
@nebuloss I submitted a fix for the native Raspbian Desktop. You can try [the intermediate build](https://github.com/oleg68/GrandOrgue-official/actions/runs/3396445842)

**Comment by nebuloss** [comment]
@oleg68 I tested your build on my raspberry pi with lxde desktop. All pannels are now working correctly. Thanks for your work!
