### ISSUE TITLE
Divisional without stops stays pressed

### ISSUE THREAD

**Issue by willeke1234** [GrandOrgue/grandorgue#1212]
Expected behaviour:
The piston of a divisional or general without stops doesn't stay pressed.

Actual behaviour:
The piston of a divisional without stops stays pressed. The piston of a general without stops doesn't stay pressed.

The [Walcker Wildervank sample set](http://www.pbrd.nl/index.php/vo/downloads/summary/3-hw-1-grandorgue-versie/8-walcker-wildervank-volledige-versie) has C divisionals, a divisional GC. They should work like GC, like they did, and not stay pressed.

**Comment by oleg68** [comment]
The intended behaviour is to stay a piston pressed whether the combination has stops or not. So the current behavior of divisionals is correct (it was changed in #1068), but the behavior of generals is not correct.

**Comment by willeke1234** [comment]
Why did the intended behaviour change? How do real pistons work?
Maybe we need a discussion about when a piston stays pressed and when it is released. At least it should be consistent and predictable.
See also #1209

**Comment by oleg68** [comment]
Now the behavior is predictable: when you press the button and it switches the stops, the button became pressed.

#1068 explains why the behavior of divisionals is changed.

**Comment by willeke1234** [comment]
How about GC?

**Comment by oleg68** [comment]
Now GC is not a combination, but only a `resetter`. If you have any ideas about GC, post them at #1220
