### ISSUE TITLE
Program settings, Audio, soundport, descriptions too short

### ISSUE THREAD

**Issue by willeke1234** [GrandOrgue/grandorgue#1216]
In the Program settings window, Audio tab, Sounds port group, the descriptions are too short and not very usefull.

![Schermafbeelding 2022-10-01 om 10 23 09](https://user-images.githubusercontent.com/97431382/193400497-fddf6074-86df-4a70-ad99-a68f4080022d.png)

A new user has no idea what Pa, Rt, R...k and R...re are.

GrandOrgue 3.7.0-1
macOS 10.15.7

**Comment by kerkovits** [comment]
I agree, I had been using GO for 3 years after I found out that these mean portaudio and rtaudio, respectively.

**Comment by oleg68** [comment]
Seems this problem is specific for 10.15. It is not reproduced on 11.
