### ISSUE TITLE
General Cancel

### ISSUE THREAD

**Issue by cadupalmieri** [GrandOrgue/grandorgue#1220]
General Cancel button do not light in the combination panel, and if i program a midi send event it doesn't work. I tested it by sending a midi command to turn on a piston, with button of combinations works, but with the GC don't.

**Comment by oleg68** [comment]
> General Cancel button do not light in the combination panel

It is not intended to light. It only switchs the current stops off.

> if i program a midi send event it doesn't work

Does it work when you press this button with a mouse?

**Comment by cadupalmieri** [comment]
It works if if send midi or mouse, but it doesn’t send midi out, the natural behavior of GC is stay on if all stops are off. Like on viscount consoles

**Comment by oleg68** [comment]
GC never worked in GrandOrgue by the way you want .

@larspalo should we change the behaviour of GC?

**Comment by cadupalmieri** [comment]
Even if it doesn't change the behavior, but at least correct his midi out. Because when you click with the mouse, it does not send midi command
Thanks!

**Comment by oleg68** [comment]
Now buttons send midi events only when their state is changed, but GC never change it's state.

**Comment by cadupalmieri** [comment]
Makes sense, good point to correct.

**Comment by larspalo** [comment]
It's not a definite right or wrong scenario. I've not experienced trouble with binding the GC to any button sending MIDI signals to activate it and having it work. So far I've seen, on real organ consoles, when you press GC all stops are de-activated and you have no visual feedback that the GC is/was pressed in any other way than just that. Basically it would be the same with any empty divisional or general button that could be pressed and depending on the actual console implementation you could have them light up or not...

**Comment by cadupalmieri** [comment]
oh, no problem, but the button GC doesn't send midi comands, if possible to correct it, helps me a lot. what i'm doing  is saving the comb 0 with no stops and using it as GC, because the 0 button sends the midi signal to the console and activate the piston light, but the GC don't send.
