### ISSUE TITLE
The release section of samples will refuse to play if the note is short enough

### ISSUE THREAD

**Issue by ray890** [GrandOrgue/grandorgue#1222]
When a note is played and released, the sample is expected to play its release section before the voice is dropped. However, if the note is released quickly enough, the voice is instantly dropped instead, creating an audible click sound, 

If the note is right under the threshold of triggering this bug, then it will sometimes happen and sometimes not happen.

This will always happen, independently of the organ used, output device, output mode, latency settings, or computer.

This has had an impact with my MIDI Sequences that I have intended to play, and this can also have an impact on keyboard players who play staccato or fast musical scores.

https://user-images.githubusercontent.com/11812575/194974595-f3f88e32-830c-41c8-90ad-0a675d03bedb.mp4

Here's the interesting part about this. If I keep an organ instance open for a very long time (I don't know what triggers this), the bug will not occur with any length of note, but when I restart the organ the bug will return.

**Comment by oleg68** [comment]
1. What is the GrandOrgue version?
2. What sampleset are you using?
3. Is the checkbox File->Settings-> Release Sampling set or not?
4. What are the values of File->Settings->Audio Sample Rates, Samples per buffer?

**Comment by willeke1234** [comment]
I did some debugging, in [GOSoundEngine::ProcessSampler](https://github.com/GrandOrgue/grandorgue/blob/master/src/grandorgue/sound/GOSoundEngine.cpp#L250):

```
if (
  sampler->stop && sampler->stop <= m_CurrentTime
  && sampler->stop - sampler->time <= block_time)
  sampler->pipe = NULL;
```
`sampler->stop - sampler->time` is `block_time` and `sampler->pipe` is set to `NULL`. The release uses this pipe and doesn't play.

**Comment by willeke1234** [comment]
Discussions:
Grand Orgue Sound Glitches #162
Cutoff on very short keypress? #306
Glitching problem #405
Sound breaking up badly with builds/versions above 1694 #494 (recommended reading)
Audio Problems with Large Sample Set #505
Samples will click/pop when organ is fed with short/rapid notes #1120

**Comment by willeke1234** [comment]
Is only the click sound a problem or also the missing release?

**Comment by oleg68** [comment]
Seems this bug has been introduced with 58c0bf31982d907829cfb7aa93d6f707a94a93ed and it is reproduced when the length of the keypress is less than one buffer. So setting a low buffer size is a possible workaround.

**Comment by oleg68** [comment]
@ray890 @willeke1234 could you try [this intermediate build](https://github.com/oleg68/GrandOrgue-official/actions/runs/3922607607).

I've just reverted [this Martin's change](https://github.com/GrandOrgue/grandorgue/commit/58c0bf31982d907829cfb7aa93d6f707a94a93ed). Seems it solves this issue but I'm not sure that it won't bring another issues.

Unfortunally, I could not find any information about the reasond for that change. @larspalo @nickappleton do you remember anything about that Martin's change?
