### ISSUE TITLE
Cache is recomputing after an update

### ISSUE THREAD

**Issue by rousseldenis** [GrandOrgue/grandorgue#1234]
@oleg68 I don't know if there is something changed from past versions, but whenever I update GO (from recent builds), cache is recomputed everytime.

Do you have a clue or is this behaviour normal ?

Thanks

**Comment by oleg68** [comment]
I cann't see a reason for this behavior.

There was a related change in #1185, it modified the hash calculation algorithm. So if the cache was created before #1185, it will recomputed with a newer version.

Does the issue appears only with the Demo Organ or with all organs?

Do you change the filesystem paths of your samplesets?

**Comment by rousseldenis** [comment]
@oleg68 this behavior appears for all organs. Nothing changed in the path.

I will check with the next version what will happen.

Let this issue open

**Comment by oleg68** [comment]
@rousseldenis I've just tested upgrade.

The cache has been created with GrandOrgue 3.8.0, is not recalculated with 3.9.0. 
But if the cache has been created with 3.7.1 or with an earlier version, it is recalculated with 3.9.0.

Si I consider this problem as single-time for upgarding from pre-3.8.0 to a post 3.8.0 version.

**Comment by rousseldenis** [comment]
I confirm this is solved
