### ISSUE TITLE
3.9.0 Error messages in window popup

### ISSUE THREAD

**Issue by Grillzombie** [GrandOrgue/grandorgue#1239]
Thanks for your continued work on GrandOrgue. the new version is running very well for me. 

However, I get an error message window with quite a few error messages when loading my organ. These error messages are annoying, how do I get rid of them? I guess they have no influence on the loading of the sample set? Anyway, I can play normally.

![GOError](https://user-images.githubusercontent.com/97833240/199807409-ea579eb8-9075-414e-8904-e8886ddd756a.PNG)

**Comment by oleg68** [comment]
Do File->Save

Next time you won't get these messages.

**Comment by rousseldenis** [comment]
@oleg68 The solution you propose is a workaround.

But we should in the future do more testing on upgrade process as everyone will have this (I had it too).

At least putting something in the release note that will help user.

**Comment by oleg68** [comment]
@rousseldenis Yes, I agree.

But I missed cases where these settings may occure in CMB files, so I didn't mention it in the Release Notes.

I can enchance the code for getting rid these messages, but this code would be very complex, so I'd leave the current behaviour.

**Comment by rousseldenis** [comment]
> @rousseldenis Yes, I agree.
> 
> But I missed cases where these settings may occure in CMB files, so I didn't mention it in the Release Notes.
> 
> I can enchance the code for getting rid these messages, but this code would be very complex, so I'd leave the current behaviour.

OK, I hope we won't have too much feedback on that as the solution is not obvious for common users
