### ISSUE TITLE
Unhandled exception with r3.9.0.1

### ISSUE THREAD

**Issue by paolo2504** [GrandOrgue/grandorgue#1249]
hi.
Latest release 3.9.0.1 Win64 crashes on loading some , not all, organs returning a fatal error (screenshot below attached).
Previous r3.8.0.1 (as well other prior) does not show the error with those organs.

Note: organ packages that show error are installed properly. Error arise only on load. This happens with most of my organ packages but not all. By interrupting execution GO crashes and closes. Doing "Ignore", loading is canceled and GO remains open. I reverted to r3.8.0.1.

![unhandled exception](https://user-images.githubusercontent.com/50132661/201179079-64e4b1bd-156f-4e44-a03b-97e5f2b18879.jpg)

**Comment by oleg68** [comment]
@paolo2504 could you attach here the crash dump file?

**Comment by paolo2504** [comment]
[CrashDumps.zip](https://github.com/GrandOrgue/grandorgue/files/9991161/CrashDumps.zip)

3 dumps with different package organs...

**Comment by oleg68** [comment]
@paolo2504 Does it always craches on the same packages? Or the packages sometimes are loaded, sometimes - are not?

If the problem is 100% reproducible with a certain package, could you place the smallest package somewhere in the file sharing and send me the link to it?

**Comment by paolo2504** [comment]
Always with same packages. Even tested with previous 3.7.1 no problem. 
packages not showing issue (Friesach for example) are loaded correctly (even if apparently slower).
I’ll post the smallest package I have soon (Carillon beiaard).

**Comment by paolo2504** [comment]
HEre below the smallest orgue package i have. It contains two organs, bith causing crash.
I noted that the exception dialog is shown twice i mean: i clock on abort first, then dialog is shown again, then i click second time on abort, dialog closes and after a second GO closes itself.

 
[CrashDumps.zip](https://github.com/GrandOrgue/grandorgue/files/9995102/CrashDumps.zip)
[beiaard.zip](https://github.com/GrandOrgue/grandorgue/files/9995105/beiaard.zip)

**Comment by oleg68** [comment]
@paolo2504 Thank you, I managed to reproduce this issue.

**Comment by oleg68** [comment]
This problem occures on any organ without a pedal.

**Comment by paolo2504** [comment]
Interesting!

**Comment by oleg68** [comment]
@paolo2504 Could you try [the intermediate build](https://github.com/oleg68/GrandOrgue-official/actions/runs/3452408113)? Does it solves the issue?

**Comment by paolo2504** [comment]
Ya, it does solve the issue. Even tested with other no-pedal package. Thanks.
