### ISSUE TITLE
Organ Settings not working

### ISSUE THREAD

**Issue by mattrixed** [GrandOrgue/grandorgue#1253]
WIN10 - latest
GO 3.9.0 and just tested 3.9.1

Sampleset tested Raszczyce

Unable to adjust anything in Organ Settings specificly noise either by lowing gain or choosing dont load the noises are all still present upon save and reload.

**Comment by paolo2504** [comment]
just tried with build 3.9.1-010: settings are correctly saved (changed gain and set don't load sample channels).
Even with r3.9.0.1 it's ok.

**Comment by mattrixed** [comment]
Loaded up new clean install of WIN11 will try again... and see.  I didn't have time to check that again after trying to just keep running audio cut outs etc...

**Comment by mattrixed** [comment]
Working thankyou - nothing like a clean install....!
