### ISSUE TITLE
Multi output display MAC os

### ISSUE THREAD

**Issue by mattrixed** [GrandOrgue/grandorgue#1255]
Through testing and researching RT asio issiues fired up Mac system and found a bug.

When selecting multiple out audio groups it all works but doesn’t display the extra outputs in the main window still just stereo dual windows….

Mac 10.15.7 latest updates 
GO 3.9.1
….. and yes all works under Mac browser YouTube GO all running at same time no issues!!!! On rt or pa !!  If only windows did also….!

![B87B40AB-887B-4AEB-A343-91F30CA9F194](https://user-images.githubusercontent.com/84826875/201918187-859e7464-5189-4b10-9f5e-17786bfca3c4.jpeg)

**Comment by oleg68** [comment]
I managed to reproduce this wrong behavior.

**Comment by oleg68** [comment]
The workaround: resize the window horisontally to min an then enlarge it.
