### ISSUE TITLE
v3.9.1-1 breaks enclosure with complex MIDI setup

### ISSUE THREAD

**Issue by okafke** [GrandOrgue/grandorgue#1266]
Hello,
my enclosure seems to send MIDI signals in reverse order, because of that I have always used `Detect complex MIDI setup`. In 3.9.0 everything worked fine, but since 3.9.1-1 the enclosure stopped working completely. Maybe this is related to the fix for #1203 which was in that release?
Here is a screenshot of my (previously working) enclosure settings after I used `Detect complex MIDI setup`:

![Screenshot 2022-11-19 222611](https://user-images.githubusercontent.com/65917827/202872210-2b0b0362-eaae-4d0c-b927-a5a048dd9bc1.png)

`Listen for Event` works the same way it did in the old versions, it sets the lower limit to 0 and the upper limit to 127, which makes my enclosure open the wrong way.

**Comment by oleg68** [comment]
You have an incorrect setup: Lower limit must be less then the Upper Limit.

What values are filled when you do `Detect complex MIDI setup`?

**Comment by willeke1234** [comment]
Is this issue caused by the newly added `if (high_value > low_value)` in `GOMidiReceiverEvent::GetNormalisedValue`?

**Comment by okafke** [comment]
> You have an incorrect setup: Lower limit must be less then the Upper limit.
> 
> What values are filled when you do `Detect complex MIDI setup`?

The screenshot shows the values that are filled when I do `Detect complex MIDI setup`. My enclosure seems to send low values when I open it completely and high values when I put my heel to the floor. What would be completely closed on a normal organ is value 127 in my case. The highest value my enclosure can produce seems to be 31. These settings worked in v3.9.0-1.

**Comment by oleg68** [comment]
@okafke Thank you. Seems, you have an **inversed** crescendo with LowValue < HighValue. We haven't predicted esistence of such cases.

**Comment by okafke** [comment]
Thank you! I tested the build from Github Actions and can confirm that it works again.
