### ISSUE TITLE
GrandOrguePerf issue

### ISSUE THREAD

**Issue by rousseldenis** [GrandOrgue/grandorgue#1280]
@oleg68 In my tests peregrinations, I wanted to launch GrandOrguePerfTest.

It seems that all tests are failing.

Do you know if those ones have to be updated or if there is a real performance problem on the current version?

**Comment by oleg68** [comment]
@rousseldenis I think is an incorrect behavior of GrandOrguePerfTest: it marks all mesure results as errors.

@larspalo could tell more.

**Comment by larspalo** [comment]
That the test fail is normal - but they should return a number at what point they fail! You see, the test is about at what point does the output fail, and you get a number at approximate that number of polyphony (for each setting) that you'll start to get xruns.

**Comment by oleg68** [comment]
@larspalo So they are not errors. They should be information messages that at this level of polyphony the error occurs high probably.

**Comment by larspalo** [comment]
@oleg68 Right, the output of perftest is perhaps a bit cryptic, but the bottom line is that the test is done in such a way that the engine is driven until failure - that is the very point of the tool. The limit if found when an error is produced. How this is presented to the user is certainly possible to change.
