### ISSUE TITLE
Categories in the Discussions forum

### ISSUE THREAD

**Issue by larspalo** [GrandOrgue/grandorgue#13]
The discussions forum of GitHub is pre-populated with certain categories. On Sourceforge we had Developers, Open Discussion and Help. If we manage to import the old discussions the categories must be created for the different elder forums. Should we only have them (the old "categories"), or some combination of the GitHub categories and the old ones?

**Comment by oleg68** [comment]
May be `Open Discussion` mapped to `General`?

**Comment by larspalo** [comment]
Well, I guess we can map the old forum to whatever we decide. The main question is really: How do we want the new discussion forum to look like with its categories?

**Comment by larspalo** [comment]
It's certainly possible to remove the existing categories on the GitHub discussion forum and replace them with whatever we deem suitable.

**Comment by rousseldenis** [comment]
> It's certainly possible to remove the existing categories on the GitHub discussion forum and replace them with whatever we deem suitable.

Yes for sure.

**Comment by oleg68** [comment]
I'd keep all github categories and I`d add `Help` and `Developers`

**Comment by oleg68** [comment]
Could we continue working with the categories?

May we to have
- Developers
- Announcements
- General
- Ideas
- Q&A
- Help
- Show and play organ (instead of Show and tell)

The last topic is specially for sharing some photos and videos

**Comment by larspalo** [comment]
I actually question if the Developers category really is necessary. It was visible only to the developers and only a very few posts ever made it into that forum. Most discussions on developer things happened over the mailing list instead. Here the issues might just fill the same function... I like the last change "Show and play" very much, a nice touch indeed!

**Comment by oleg68** [comment]
Sometimes I would like to discuss the source code itself. I think it would not interesting for ordinar users, so I'd lite to have the Developers cathegory.

**Comment by larspalo** [comment]
If we decide on that approach for communication, yes, then it might fill a purpose. As I think of it, the "Open Discussion" that we consider mapping to "General" contain lots of feature requests and diverse topics that very well could land in anything from Announcements, Ideas and Q&A instead. Maybe we should clean up the categories to something like:

- Developers
- General
- Help
- Show and play

to keep things a bit cleaner. What do you think about that? We could just modify the description of each category so that it's clear what's expected in each of them.

**Comment by oleg68** [comment]
@larspalo I agree

**Comment by oleg68** [comment]
I have reorganised the categories according your suggestion. Seems we may close tis issue.

**Comment by larspalo** [comment]
Yes, it looks good like that, I think!
