### ISSUE TITLE
Installed version number displays incorrectly under Gnome

### ISSUE THREAD

**Issue by kerkovits** [GrandOrgue/grandorgue#1304]
Recently, I was surprised while cleaning up my apps in Gnome software: it reported that I have GO 3.2.0 installed. I did not want to have an old build installed, so I deleted it, and it turned out, that in fact it removed the recent 3.9.2. I suppose that Gnome reports an old version number, because it gets information from grandorgue/resources/GrandOrgue.appdata.xml, which has not been updated for years.

**Comment by kerkovits** [comment]
PS. I could have created a pull request with an updated xml, but that would solve the problem only temporarily. An automatized generation of the xml would be more elegant during the release.

**Comment by rousseldenis** [comment]
@oleg68 We should include those changes in our release management.

@kerkovits That has to be updated automatically. No need to do a PR for that.
