### ISSUE TITLE
Won’t start 3.9.3

### ISSUE THREAD

**Issue by mattrixed** [GrandOrgue/grandorgue#1311]
Just upgraded now won’t even start… multiple sessions are in task manager ctr alt del but no visual and not running /opening….

Ran hw to get me out of trouble and cpu spiking up and down no stops pulled!  oh no it’s broken but then realised and checked GO still running in background chewing up cpu but no visual screen!

will test some more….when have time have rolled back to 3.9.2 and working again.

3.9.3
windows 10

**Comment by oleg68** [comment]
I managed to reproduce it. Will fixed soon.

**Comment by oleg68** [comment]
This bug has been caused by #1296

**Comment by mattrixed** [comment]
Works a treat 👍
