### ISSUE TITLE
Some Launchpad settings not being saved

### ISSUE THREAD

**Issue by oleg68** [GrandOrgue/grandorgue#1350]
### Discussed in https://github.com/GrandOrgue/grandorgue/discussions/1348

<div type='discussions-op-text'>

<sup>Originally posted by **mayesp** January 20, 2023</sup>
I was getting very cross when I kept losing Launchpad settings, and now having calmed down and analysed the situation, what I am seeing is very puzzling!

This is grandorgue-3.9.4-1.1.x86_64 running under SuSE Tumbleweed with latest updates. Sampleset is Bureå Extended AGO.

I have combinations set on all three manuals and pedals for the pistons, and eight generals. That works fine when operated by mouse and screen.

I have enabled GO to send colour settings back to the Launchpad for pistons, generals and couplers.

The couplers and generals work fine - the association with Launchpad buttons and the colours work fine, and are correctly saved between launches.

But when I set the Launchpad to be associated with the keyboard and pedalboard  pistons, they don't get saved, even though they work when first set.

Moreover, if I export the settings to another .cmb file, the keyboard and pedalboard settings are not there.

To give a bit more detail, the eight generals I have set are mapped to the 5th row up - buttons 48-55 - they work fine. Button 120 is general cancel, and the couplers are the RHS buttons 104, 88, 72, 56, 40 and 24 - again, they all work fine, including illuminating the Launchpad, and are saved.

But when I try to use the bottom four rows for pedal and three manual pistons - 112-119, 96-113, 80-87 and 64-71 and they don't get saved. 

Since I wasted a lot of time setting and then losing them, I have just tried setting the bottom left Launchpad button (112) to "Pedal 1". It works when I set it. But when I save settings, or export to a .cmb file, button 112 is not there, and if I exit and restart GO, the setting is lost. I even found an old saved file from a long time back that has

MIDIKey001=112
MIDISendKey001=112

in it, but I don't see that in the new automatically saved .cmb file, or the one that I manually export.

Sorry that is long-winded, but seems VERY confusing to me!!

Thanks in advance for any help.</div>

**Comment by oleg68** [comment]
It is a specific issue with the ``Bureå Extended`` sampleset. Midi settings for divisionals of ``Piteå Scool of Music`` work as expected.

**Comment by willeke1234** [comment]
The issue is reproducable with sample sets Barton, Wildervank, Piteå and probably all sample sets with divisionals. `ShortcutKey` is also not saved. When I import an older cmb file the I get hundreds of warnings like:

```
Monday, 23 January 2023 at 06:40:16: 06:40:16: Warning: Unused CMB entry 'Setter004Divisional101/ShortcutKey'
Monday, 23 January 2023 at 06:40:16: 06:40:16: Warning: Unused CMB entry 'Setter004Divisional101/NumberOfCouplers'
Monday, 23 January 2023 at 06:40:16: 06:40:16: Warning: Unused CMB entry 'Setter004Divisional101/NumberOfMIDIEvents'
Monday, 23 January 2023 at 06:40:16: 06:40:16: Warning: Unused CMB entry 'Setter004Divisional101/NumberOfStops'
Monday, 23 January 2023 at 06:40:17: 06:40:17: Warning: Unused CMB entry 'Setter004Divisional101/NumberOfSwitches'
Monday, 23 January 2023 at 06:40:17: 06:40:17: Warning: Unused CMB entry 'Setter004Divisional101/NumberOfTremulants'
Monday, 23 January 2023 at 06:40:17: 06:40:17: Warning: Unused CMB entry 'Setter004Divisional101/NumberOfMIDISendEvents'
```

**Comment by rousseldenis** [comment]
> The issue is reproducable with sample sets Barton, Wildervank, Piteå and probably all sample sets with divisionals. `ShortcutKey` is also not saved. When I import an older cmb file the I get hundreds of warnings like:
> 
> ```
> Monday, 23 January 2023 at 06:40:16: 06:40:16: Warning: Unused CMB entry 'Setter004Divisional101/ShortcutKey'
> Monday, 23 January 2023 at 06:40:16: 06:40:16: Warning: Unused CMB entry 'Setter004Divisional101/NumberOfCouplers'
> Monday, 23 January 2023 at 06:40:16: 06:40:16: Warning: Unused CMB entry 'Setter004Divisional101/NumberOfMIDIEvents'
> Monday, 23 January 2023 at 06:40:16: 06:40:16: Warning: Unused CMB entry 'Setter004Divisional101/NumberOfStops'
> Monday, 23 January 2023 at 06:40:17: 06:40:17: Warning: Unused CMB entry 'Setter004Divisional101/NumberOfSwitches'
> Monday, 23 January 2023 at 06:40:17: 06:40:17: Warning: Unused CMB entry 'Setter004Divisional101/NumberOfTremulants'
> Monday, 23 January 2023 at 06:40:17: 06:40:17: Warning: Unused CMB entry 'Setter004Divisional101/NumberOfMIDISendEvents'
> ```

@oleg68 That sound to me as a behaviour after a change in settings feature (I don't find the related PR). The solution was to save the settings just after having loaded them. Can you confirm ?

**Comment by oleg68** [comment]
@rousseldenis 

> That sound to me as a behaviour after a change in settings feature (I don't find the related PR). The solution was to save the settings just after having loaded them. Can you confirm ?

No, `Save` does not solve the issue with `Bureå Extended`.
