### ISSUE TITLE
Build fails on linux (mint) - rsvg-convert missing

### ISSUE THREAD

**Issue by ahall41** [GrandOrgue/grandorgue#1357]
Add librsvg2-bin to prepare scripts and list of dependencies, etc? I'm running Mint 20.
Builds OK after `apt install librsvg2-bin.`

**Comment by oleg68** [comment]
rsvg-convert not required for building GO on Mint. 

What error message are your receiving?

**Comment by ahall41** [comment]
I no longer get the error after installing librsvg2-bin. I recall that the error was about a non-existent rsvg-convert - which prompted me to install it. I will try to recreate the exact error message.

**Comment by oleg68** [comment]
@ahall41 I could not reproduce this issue with mint 20.2. Please give me detail information (including the detail mint version and desktop environment) how to reproduce it.

**Comment by oleg68** [comment]
What desktop environment (Cinnamon, Mate or XFCE) do you have?

**Comment by ahall41** [comment]
Cinnamon - imagick on both Ulyana (20) and Una (20.3) are at version 3.4.4-4.
And `convert -list delegate` on both shows `svg =>          "rsvg-convert' -o '%o' '%i"`

**Comment by ahall41** [comment]
So ... downloaded and installed Cinnamon and XFCE VMs for Ulyana - GO builds without issue on both.
I even tried apt purge imagemagick + a reinstall, and still getting this error. While it isn't causing me a problem (once I installed librsvg2-bin), its just possible someone else might come across it? In any case I have a new PC on order for GO.
