### ISSUE TITLE
[3.9.5] Errors when cache management is disabled

### ISSUE THREAD

**Issue by rousseldenis** [GrandOrgue/grandorgue#1363]
On 3.9.4 version, I didn't have errors with cache management disabled at startup.

Since upgrade, a popup shows error at each sample set load.

**Comment by rousseldenis** [comment]
@oleg68 This is the error that is triggered: https://github.com/GrandOrgue/grandorgue/blob/master/src/grandorgue/GOOrganController.cpp#L541

**Comment by rousseldenis** [comment]
And I tried going back and forth from 3.9.4, I confirm that is only with 3.9.5

**Comment by rousseldenis** [comment]
I think, this is due to https://github.com/GrandOrgue/grandorgue/commit/6525ddb21bc6abd06790fe095dec1b463ced9967

**Comment by oleg68** [comment]
@rousseldenis This is a warning, not an error.


Sometimes we change the hash calculation algorithm, so GrandOrgue can not validate the cache created with a previous GrandOrgue version. In that case GrandOrgue puts a warning message and bypasses the cache.

How do you want we fix this issue? Supporting the algorithms from all previous versions would be very expensive.

**Comment by rousseldenis** [comment]
> @rousseldenis This is a warning, not an error.

In this case, it shows a blocking popup (sample set loading is stopped) with that message.

It shows at every load.

> How do you want we fix this issue? 

At least changing the 'GOMessageBox' into a wxLogWarning.

But as said, this behavior triggers only if cache management is disabled in configuration (if you enable it, the popup does not show anymore), so, a better fix should disable every cache message if the cache management is disabled (which makes sense IMHO)

**Comment by rousseldenis** [comment]
> Or GO could delete the invalid cache (maybe after asking the user).

@kerkovits thanks for the clue. Indeed, the behavior is the following:

- enable cache management.
- load a sample set
- disable cache management
- reload sample set
- error message

Deleting the sample set's cache solves the problem.

But IMHO, that has to be improved as confusing for user
