### ISSUE TITLE
Can't find DSP after upgrade to 3.9.0-1

### ISSUE THREAD

**Issue by OrgelSpieler** [GrandOrgue/grandorgue#1372]
I was running v3.7.1-1 when attempting to upgrade to v3.9.5-1.  Upon completion of the upgrade, no sound would occur and this error was posted: _Output Device Rt:asio ASIO Hammerfall DSP:  not found - no sound output will occur_.

I backed out the update and returned successfully to v3.7.1.-1 with the intent of performing incremental upgrades to determine the point of error.

I successfully upgraded  to v3.8.0-1.

The subsequent upgrade to v3.9.0-1 failed resulting in the same error: Output Device Rt:asio ASIO Hammerfall DSP:  not found - no sound output will occur.  I can't find anything in the release notes that would indicate why this problem has occurred other than the port renaming nor do I see any instructions to modify settings upon install of this release.  I don't see anything obvious that I need to fix.  Any suggestions I how I can resolve this issue?

**Comment by oleg68** [comment]
It is caused by #1230: `Rt` was renamed to `RtAudio`. The new GO  should try to find the audio device by it's old name, but something went wrong.

The workaround is to go to Settings->Audio, to select the device, press `Change` and select the device with the new name.

**Comment by OrgelSpieler** [comment]
Thank you for responding so quickly.   Everything is working now.   I was suspicious about #1230 as being the culprit, but it wasn't obvious to me how to deal with it.
