### ISSUE TITLE
Divisionals are missing when importing a cmb file from an older version

### ISSUE THREAD

**Issue by willeke1234** [GrandOrgue/grandorgue#1374]
When I import an existing cmb file then the divisionals on the Divisionals panel are gone and I get a lot of of warnings like

```
Tuesday, 07 February 2023 at 15:20:17: 15:20:17: Warning: Unused CMB entry 'Setter005Divisional109/NumberOfStops'
Tuesday, 07 February 2023 at 15:20:17: 15:20:17: Warning: Unused CMB entry 'Setter005Divisional109/NumberOfMIDIEvents'
Tuesday, 07 February 2023 at 15:20:17: 15:20:17: Warning: Unused CMB entry 'Setter001Divisional100/MIDISendHighValue001'
Tuesday, 07 February 2023 at 15:20:17: 15:20:17: Warning: Unused CMB entry 'Setter005Divisional103/NumberOfTremulants'
Tuesday, 07 February 2023 at 15:20:17: 15:20:17: Warning: Unused CMB entry 'Setter004Divisional101/ShortcutKey'
Tuesday, 07 February 2023 at 15:20:17: 15:20:17: Warning: Unused CMB entry 'Setter005Divisional102/NumberOfTremulants'
Tuesday, 07 February 2023 at 15:20:17: 15:20:17: Warning: Unused CMB entry 'Setter006Divisional101/NumberOfMIDISendEvents'
Tuesday, 07 February 2023 at 15:20:17: 15:20:17: Warning: Unused CMB entry 'Setter004Divisional104/NumberOfMIDIEvents'
Tuesday, 07 February 2023 at 15:20:17: 15:20:17: Warning: Unused CMB entry 'Setter006Divisional100/NumberOfTremulants'
Tuesday, 07 February 2023 at 15:20:17: 15:20:17: Warning: Unused CMB entry 'Setter007Divisional100/NumberOfCouplers'
Tuesday, 07 February 2023 at 15:20:17: 15:20:17: Warning: Unused CMB entry 'Setter001Divisional100/MIDIUpperLimit001'
Tuesday, 07 February 2023 at 15:20:17: 15:20:17: Warning: Unused CMB entry 'Setter001Divisional104/NumberOfMIDISendEvents'
Tuesday, 07 February 2023 at 15:20:17: 15:20:17: Warning: Unused CMB entry 'Setter006Divisional106/NumberOfMIDIEvents'
```

GrandOrgue 3.9.4 and 3.10.0.7
Sample sets Wildervank, Kdousov, demo

**Comment by oleg68** [comment]
> the divisionals on the Divisionals panel are gone

Could you explain what does it mean? Is it lack of divisional pistons on the panel? Could you post here the screenshot of the panel?

> I get a lot of of warnings like

It is a normal consequence of #1211

Earlier all divisionals were saved to the CMB file even there were no stops enabled. After that PR only the combinations with some stops engaged are saved and read. So this warning appear for all divisionals without any assignments.

Another reason that earlier the divisionals of manuals with upper numbers were read but were not used. Now only the real manuals are read from a cmb.

Do you have any real other problems except the extra warnings?

**Comment by willeke1234** [comment]
The buttons are still there but they don't become depressed and all divisionals are empty. I don't use the Divisionals panel and if nobody uses it then it isn't a problem. How do I remove the warnings? Is GrandOrgue not backward compatible?

**Comment by oleg68** [comment]
> The buttons are still there but they don't become depressed and all divisionals are empty

They all are depressed. You can assign combinations to them. If you had assigned some combinations, you can recall them at the `K` bank.

>  How do I remove the warnings?

Just save the cmb file again with a recent GO

> Is GrandOrgue not backward compatible?

Not always. If the old behavior was buggy or confusing, we refuse to support it in the new GO versions.

**Comment by willeke1234** [comment]
>If you had assigned some combinations with an pre 3.9 version, you can recall them at the K bank

Is this documented?

**Comment by oleg68** [comment]
Only here https://github.com/GrandOrgue/grandorgue/pull/1211#issuecomment-1269537193

**Comment by oleg68** [comment]
@willeke1234 Have you managed to use the old saved divisional combinations?

**Comment by willeke1234** [comment]
The divisionals are in bank K but the MIDI events of the buttons on the Divisionals panel are missing. Bank K isn't user friendly, why are the old divisionals not in bank A?
The conversion of the settings and how to handle the warnings should be documented in CHANGELOG.md

**Comment by oleg68** [comment]
@willeke1234 You can reassign all divisionals from the `K` bank to the `A` and save them. You can reassign midi events to the divisionals and save the new settings.

I understand your quandary with the old settings, but supporting them would require a huge additional code. The current format of CHANGELOG.md does not allow to provide a detail description of changes.

I close this issue because there is nothing to fix in GrandOrgue.
