### ISSUE TITLE
Feature request : to have the possibility to apply a logical NOT to an input switch of a drawstop

### ISSUE THREAD

**Issue by eturpault** [GrandOrgue/grandorgue#1390]
In order to permit to convert complex switches networks from Hauptwerk to GrandOrgue ODF format, the following change is requested in GrandOrgue SW : in a drawstop object (stop, coupler, switch, ...), to add the possibility to indicate to GO that the state of an input switch has to be inverted before to apply the logical function of the drawstop (AND, OR, ...).
The proposed syntax is to add a minus character before the input switch number which the state has to be inverted (same syntax as in General object to turn off a switch for example).
Example of a drawstop section with this new syntax : 
```
[Switch001]
Function=And
SwitchCount=2
Switch001=002 
Switch002=-003
```
In this example the Switch001 state would be the result of the logical operation : Switch002 And (Not Switch003)
This would permit to convert to a GO Switch object a HW SwitchLinkage object which has the attribute SourceSwitchLinkIfEngaged=N or ConditionSwitchLinkIfEngaged=N.

**Comment by larspalo** [comment]
What exactly is the real world application? What is it you're trying to model?

**Comment by eturpault** [comment]
The HW ODF model has this SwitchLinkage object used to link switches objects together, with two inputs and one output, the state of each input can be inverted before to be processed. So for the convertion to GO it will help to have the possibility to inverse separately each input of the switch
This property is used for example in the Sonus Paradisi St Martini sample set, which has two tremulants : one real and one artificial. There is one switch permitting to choose between the real and the artificial. This switch is controlling two other switches in opposite effect, when the real tremulant is selected, one switch is passing and the other is blocking, and vice versa when the artificial tremulant is selected.

**Comment by eturpault** [comment]
I forgot to mention another use case of switch state inversion which is used by Piotr Grabowski in his HW sample sets. It is about the drawstops release noise generation. The switch which controls a drawstop triggers an attack sample to play the attack noise, and another switch which inverts the state of the first switch triggers another attack sample to play the release noise. 
In OdfEdit I detects this use case to generate the release noise with a stop having a silent attack sample and the proper release sample, as we are discussing in another thread. So for this use case I don't need the feature requested in this present thread.

**Comment by larspalo** [comment]
Isn't it already possible to use the basic switches to choose between which of the tremulants should be activated? See the example I attach (which indeed does use a NOT switch).

[TwoTrems.zip](https://github.com/GrandOrgue/grandorgue/files/10766866/TwoTrems.zip)

The noise effects is already in another issue and there I think that a better overall solution is to have a more native approach of keeping attack and release in the same stop/rank.

Adding stuff just to make GO behave in the same way as HW is not a real progress, I think. We should always think about the underlying task we should try to solve and do it in the best way possible within GO - not necessarily just imitate how others have done it.

**Comment by eturpault** [comment]
Thanks for the example ODF. It is indeed possible to use an intermediate switch to invert a switch state, but it makes less easy the convertion from HW to GO format for some sample sets.
If you think that this evolution is not worth it, I will see how to do without it in OdfEdit.

**Comment by larspalo** [comment]
@oleg68 As the desired effect already is possible to re-create with the GO switch system as is, perhaps this issue could be closed with a note that it's already possible to achieve?

**Comment by oleg68** [comment]
@larspalo Do you object to implement the requested feature? I'd do this.

**Comment by larspalo** [comment]
> @larspalo Do you object to implement the requested feature? I'd do this.

You do understand that it's not needed as what he want to do already can be done as I've shown?

**Comment by larspalo** [comment]
> Another example where we are implementing a feature that might be achieved with already existing capabilities is #1396

Yes, but it was only possible by misusing features intended to be used in a different way, and even so it didn't really work as it originally was intended before #1396. That's a _very_ big difference in my opinion.

Implementing features that correct things (that either are not working or are abused, or even better: to make new things possible should definitely have higher priority over features asked "to do things simpler for ..." when those things are already possible but the complain is - it's too difficult to do it that way... - which it's by the way: really not (as in using the switch NOT). Pun intended.

If you're really, really, into getting switches working that way - I'm not going to oppose it as long as it doesn't interfer with how it really should be done instead. Because, to me, this request is quite the opposite of #1396 - we now already have a way of how it should be done correctly in GO but a new "hack" is desired to shortcut the logical link chain of switches.
