### ISSUE TITLE
Feature request : to make possible that a switch object can reference switches with a higher number 

### ISSUE THREAD

**Issue by eturpault** [GrandOrgue/grandorgue#1391]
In order to permit to convert complex switches networks from Hauptwerk to GrandOrgue ODF format, the following change is requested in GrandOrgue SW : to make possible that a switch object **can reference switches with a higher number.**
In the current GO implementation, the help of GO says for Drawstop objects : 
> Switch999 (integer 1 - switch count, required) Lists the input switches of the logical function of the drawstop. If the drawstop is a switch, **it can only reference switches with a lower number.** The number of this settings depends on the function.

If there are circular references between switches (which can happen with HW sample sets), GO should be able to support it and avoid to go in infinite loop when switches states are updated, stopping the switches update when all switches linked together have been already updated.

**Comment by eturpault** [comment]
About the switches circular references, it could be detected by GO during the ODF loading phase, and if present it could be logged as an error, stopping the loading.
But please make it possible for a switch to reference a switch with a higher number. It is not simply to make it "easier" the conversion from HW to GO ODF, it is to make it "possible" in case of sample sets having complex switches structure. Thanks.

**Comment by eturpault** [comment]
@oleg68 : I have implemented in OdfEdit the convertion from HW to GO of the conditional switches. Finally I have been able to manage it only with switches referencing other switches with lower numbers.
**So I cancel my request submitted in this issue.**
Maybe you will want to implement this change anyway, it can be useful for other needs.

**Comment by larspalo** [comment]
@oleg68 Might I ask why you think this is necessary to implement? What exactly can be achieved with it that cannot currently be done already in another way?

**Comment by oleg68** [comment]
@larspalo I found the limitation as unreasonable. Of cause, now every switch network may be reordered for satisfying this limitation, but it is hard to do manually.

**Comment by larspalo** [comment]
> but it is hard to do manually.

Not very hard anymore if done with GoOdf or other tools. If there's no gain in functionality from changing the behaviour I'm really not so interested in doing the change at all.

**Comment by oleg68** [comment]
Ok, let close it as won't fix.
