### ISSUE TITLE
Release numbering is outdated

### ISSUE THREAD

**Issue by larspalo** [GrandOrgue/grandorgue#14]
The numbering of the releases should reflect what revision they come from. That was earlier set with cmake with the -DVERSION_REVISION= at build time. I suggest we return to that release numbering instead of the non meaningful current version of keeping an outdated revision number with dash something.

**Comment by rousseldenis** [comment]
> The numbering of the releases should reflect what revision they come from. That was earlier set with cmake with the -DVERSION_REVISION= at build time. I suggest we return to that release numbering instead of the non meaningful current version of keeping an outdated revision number with dash something.

I ++ for this.

**Comment by oleg68** [comment]
Now it can be set  with  -DVERSION and -DBUILD_VERSION parameters at the build time.

I'd like to discuss changing version numbering. I have some thouths.
But I think we may to return here after the first oficcial release `0.3.1.2342-1`
