### ISSUE TITLE
Organ Settings dialog takes the whole height of the screen.

### ISSUE THREAD

**Issue by oleg68** [GrandOrgue/grandorgue#1415]
When I open Audio/Midi -> Organ Setting, the dialog spans the whole screen vertically, and it can not be decreased.

**Comment by ClarkeBrunt** [comment]
Using v3.10.0-1, I'm not finding that Audio/Midi -> Organ Setting spans whole screen vertically. It's rather small vertically for me, e.g. just showing first 4 items in the tree for the demo organ.

Whereas Audio/Midi -> MIDI Objects dialog is rather large vertically - on one of my screens, it always comes up with the buttons at the bottom off the bottom edge of the screen.

Neither of these dialogs seems to remember size/position. I can resize and move around, but if they are closed and re-opened, they go back to the default.

**Comment by oleg68** [comment]
The issue is on linux
