### ISSUE TITLE
Issue with GrandOrgue not turning LED's off on Novation Launchpads - Divisionals

### ISSUE THREAD

**Issue by David-Poole** [GrandOrgue/grandorgue#1418]
I'm having an issue with GrandOrgue not turning off the LED's to Divisionals that I have set them to, despite assigning a 
note-off value of 0 in the MIDI-Settings for Button-ON.

As an example, let's say I assign Divisional 1 for Pedal to MIDI-Note 83.
On the send page, I assign a Note-On value of 53 and a Note-Off value of 55.
Then I go to the Master Controls under Panel, left click the 'ON' button, 
under Send, select 9x Note Off for MIDI-Note 83 of the exact same Launchpad.
I then click on 'OK', and then save. I then go and switch samplesets or shutdown GO,
but the LED for pad 83 is still lit up. If I follow the same procedure as laid out for an
organ stop, no issues, the LED turns off when I shutdown GO or switch samplesets.

I hope this makes sense.

**Comment by oleg68** [comment]
What GO version are you using?

**Comment by David-Poole** [comment]
I'm currently using  the latest version of GrandOrgue,  3.10.1 on Arch
Linux. I had the same issue on Kubuntu and OpenSuse

**Comment by David-Poole** [comment]
Sorry, my bad, I just did a quick check on it through my AUR helper and it's saying version 3.11.0.0.r3.g2664413e-1Sent from my Bell Motorola device over Canada’s largest network. \n Envoyé de mon appareil Motorola de Bell via le réseau le plus vaste au pays.On Feb. 27, 2023 1:03 p.m., David Poole ***@***.***> wrote:I'm currently using  the latest version of GrandOrgue,  3.10.1 on Arch Linux. I had the same issue on Kubuntu and OpenSuseOn Mon., Feb. 27, 2023, 12:49 p.m. Oleg Samarin, ***@***.***> wrote:
What GO version are you using?

**Comment by oleg68** [comment]
@David-Poole I could not reproduce this issue with GrandOrgue 3.11.0-1.

When I close GrandOrgue, it sends midi messages for divisionals and banked divisional as well as for stops.

Feel free to reopen this issue if you manage to reproduce it with the recent GrandOrgue and you are ready to provide an additional information.
