### ISSUE TITLE
No display of pitch in Master Controls - recent bug?

### ISSUE THREAD

**Issue by ClarkeBrunt** [GrandOrgue/grandorgue#1428]
Hi. I'm new to GitHub issues etc, so hope it's OK to flag this which I raised as Discussion #1422, but nobody seems to have taken it up. I does appear to be a bug - no display of pitch in Master Controls. 

I've just noticed that with GO v3.10.1-1, in the Master Controls dialog, the Organ Pitch label (in the centre of top row of buttons) remains always blank, even after using the buttons to adjust the pitch. The pitch **is** altered correctly. This happens both with Windows and the .deb version.

As I still had a v3.10.0-1 version on another windows machine, I tried that. With this version, the label is blank when the Master Controls dialog is first diplayed, but as soon as one of the pitch buttons is pressed, the label displays correctly. Also, the Save button in the dialog is illuminated once the pitch is changed - Save remains un-illuminated in v3.10.1-1.

I've no experience of earlier versions, but it looks like this must have changed in  v3.10.0-1 ->  v3.10.1-1.

_Originally posted by @ClarkeBrunt in https://github.com/GrandOrgue/grandorgue/discussions/1422_

**Comment by oleg68** [comment]
Might be the bug was in 3.10.1-1, but I can not reproduce it in 3.11.0-1. The pitch display starts showing after the pitch is changed, and the `Save settings` button is lighted. 

Feel free to reopen the issue if the problem reoccures with a recent version.
