### ISSUE TITLE
Build error: file LINGUAS is missing

### ISSUE THREAD

**Issue by kerkovits** [GrandOrgue/grandorgue#1429]
I got the following error message while building GO:
`/usr/bin/msgfmt: /builddir/build/BUILD/grandorgue-3.10.1-1/po/LINGUAS does not exist`

This bug was introduced by https://github.com/GrandOrgue/grandorgue/pull/758

Result is that the desktop file does not get processed by `gettext`.

Please consider including `/po/LINGUAS` with the following content:
`de es fr hu it nl pl sv`

Thank you very much in advance.

**Comment by oleg68** [comment]
@kerkovits you are welcome to open a pull request with this file.
