### ISSUE TITLE
GrandOrgue does not store visible switches in combinations by default

### ISSUE THREAD

**Issue by oleg68** [GrandOrgue/grandorgue#1498]
I cannot set any combinations at all in GO with a sample set like Norrfjärden. No combination is set nor saved. With simpler sample sets without any invisible couplers it works fine.

_Originally posted by @larspalo in https://github.com/GrandOrgue/grandorgue/pull/1492#pullrequestreview-1407021965_

**Comment by oleg68** [comment]
Storing switches in combinations is controlled by GOSwitch::IsDisplayed(). Seems that this method returns a wrong result for Norrfjärden.

**Comment by oleg68** [comment]
@larspalo 

> The switches are listed in the [Manual999] section so they should definitely be stored in the divisionals. Also, I think that the visible switches should be the ones controlling the back end stops even if the stops themselves are not displayed or stored in the combinations - they should activate as they are controlled by the switches nevertheless.
> To sum it up: we can expect that since Norrfjärden has the CombinationsStoreNonDisplayedDrawstops=N in the [Organ] section, the combinations should not store any of the non displayed drawstops, but all the displayed drawstops (switches) should really be stored. But to be fair, this "bug/feature" has existed for a long time as I tested a very old GO build and it shows exactly the same behavior.

We should specify a precise definition, what `Displayed` mean? Displayed where? On the main panel only? Or on any other panels?

Why should we assume that any switch mentioned in  [Manual999] section is displayed? It is not obvious.

**Comment by oleg68** [comment]
> @oleg68 The Displayed for the structural elements of an organ is a relic from old times where the main panel was specified in the structural section. With the new panel format the main panel is [Panel000] and all structural elements default to a displayed false - but are displayed as needed on [Panel000]. So, in the old format they are not displayed - but in the new format they are displayed as they exist on [Panel000].

> The reason why it's this complicated is because of keeping compatibility with older versions of specification. Also the current implementation is not fully adapted to deal with the new way of separating the displayed items as anything that is defined on the panels. The structural section is not intended to be used for any kind of display related stuff in the new format.

Any logic checking if a drawstop is displayed or not must take into account multiple things. The simple case is if Displayed=Y in the structural section like in the old format, and this works since ancient times. For the new format GO should check all of the panels (or at the very least [Panel000]) and see if an element is displayed there, if so, then they should be considered displayed even if the value of Displayed is false in the structural section.

> The (only) reason to list the switches in the [Manual999] sections is to have them included in the built in divisionals of GO. As it's not immediately obvious that the CombinationsStoreNonDisplayedDrawstops might currently cancel that - I almost think that listing the switches (or stops, couplers, tremulants - etc) in the manual sections should override the [Organ] setting for divisionals. 

> What is your opinion on this?

**Comment by oleg68** [comment]
I think Displayed=Y or Displayed=N, when it is specified in ODF, should override any calculated value from other things.

I agree with your suggestion to check a presence of the element on **any** panel, not only on Panel000.

What is the `structural` section that you are talking about?

**Comment by larspalo** [comment]
> I think Displayed=Y or Displayed=N, once it is specified in ODF, should override any calculated value from other things.

Then we would need to instead of defaulting to Displayed=N actually calculate the value if it's not present.

> I agree with your suggestion to check a presence of the element on **any** panel, not only on Panel000.
> 
> What is the `structural` section that you are talking about?

In the odf there is the [Organ] section and all the elements that belong to the organ as such (structurally), like manuals, stops, ranks, windchestgroups etc. They should describe how they work and what properties they have.

How they are chosen to be displayed can vary, and for greater flexibility the new panel format was introduced. Also, the thought was to seaparate the functional aspects of the organ (what I called the structural section) from its GUI display which is rendered on the panels.

**Comment by larspalo** [comment]
The thing is that if one specify the Displayed=Y in the odf, one must also specify the gui attributes as in the old style. This is not desirable. That is why I think that the displayed setting is an old relic that should be considered legacy support.

You can say that the default to Displayed=N was done so that we could move to the new panel format and still keep compatibility with older sample sets.

But from the new panel formats point of view, anything that is specified on a panel is per definition displayed, no matter what. (You cannot specify anything on a panel that is not displayed...)

**Comment by oleg68** [comment]
@larspalo Why the visibility of an element is taken in account when saving a combination?

I think the initial intention was to separate primary switches that are controlled  by users from secondary switches or elements that state is calculated based on the state of other elements (either primary or secondary) with logical functions. We should save the state of primary elements only and we shouldn't save the state of secondary elements. Instead we should recalculate their states upon the states of primaries is restored.

So may be we relay on existancy of logical functions in odf instead of the visibility?

**Comment by larspalo** [comment]
> So may be we relay on existancy of logical functions in odf instead of the visibility?

Yes, I think you're right, especially if we don't implement a more sophisticated way of determining the visibility. Not everything in the (current) odf format is perfect - it has evolved over time and some features of it can partially conflict with others. New features have been added to provide improvements while the format also somehow should support older versions of .organ files so that GO could open them. The visibility setting is one of the old legacy parts that date back to the real infancy of GO (and legacy of HW1).

**Comment by oleg68** [comment]
@larspalo Can be an element visible, but "Read-Only"? It would only display the current state calculated from anothers without allowing the user to change it. We shouldn't save it's state in combinations even it is visible.

We should think more before doing any changes the storing combinations algorithm.

**Comment by larspalo** [comment]
@oleg68 Yes, it's perfectly possible to have a visible but "read-only" element. Mainly the switches can have this property. Again you're right. Any element which state is controlled by another shouldn't need to be saved since it's state indeed is controlled by the other element.

**Comment by oleg68** [comment]
@larspalo I changed the saving criteria from `Displayed` to `not ReadOnly`. The result can be downloaded from https://github.com/oleg68/GrandOrgue-official/actions/runs/5163674792 . Something is saved now in Norrfjärden. Could you test more?

**Comment by larspalo** [comment]
@oleg68 Did you link to the correct build? In the linked build nothing new is saved, nor is the code changed from IsDisplayed. I guess you meant another build, right? Could it be https://github.com/oleg68/GrandOrgue-official/actions/runs/5163024336?

**Comment by oleg68** [comment]
@larspalo Yes, you are right. I confused the branch names. [Your](https://github.com/oleg68/GrandOrgue-official/actions/runs/5163024336) is the correct link.

**Comment by larspalo** [comment]
@oleg68 I dare not say about the previous builds, but the one at https://github.com/oleg68/GrandOrgue-official/actions/runs/5164992997 definitely has it working as it should.

**Comment by oleg68** [comment]
Is it better than current behavior?

**Comment by larspalo** [comment]
@oleg68 Yes, I think it is. I've not yet tested every possible case, nor have I in great detail examined the saved yaml file, but so far everything seems to work as I'd expect it to.

**Comment by oleg68** [comment]
> @oleg68 Yes, I think it is. I've not yet tested every possible case, nor have I in great detail examined the saved yaml file, but so far everything seems to work as I'd expect it to.

Ok. I'll submit the new behavior with three PRs. #1560 is the first one.

 (With the slight exception that not all fixes from earlier PRs are yet also applied)

I'm waiting for approval of @rousseldenis
