### ISSUE TITLE
The Settings menu item is malplaced

### ISSUE THREAD

**Issue by larspalo** [GrandOrgue/grandorgue#15]
In the long run I think we should split the current settings dialog that is multi purpose so that we separate general settings from audio related settings etc and place them in relevant menus. In the mean time, until that task is done, I suggest we move down the Settings menu item from the top of the File menu down to just before the Close and Exit options.

**Comment by oleg68** [comment]
I have a discussion topic in https://github.com/oleg68/GrandOrgue/discussions/64

I'd like to discuss the new menu stucture and to make all changes in menu at once.

**Comment by rousseldenis** [comment]
> I have a discussion topic in [oleg68/GrandOrgue#64](https://github.com/oleg68/GrandOrgue/discussions/64)
> 
> I'd like to discuss the new menu stucture and to make all changes in menu at once.

Ok, if something is already began, let's go there and propose something here ?

**Comment by oleg68** [comment]
@rousseldenis I'd like to ask you for copying open issues and discussions from my fork too. Of cause, after importing ones from SourceForge and after the oficial release.

**Comment by larspalo** [comment]
Unfortunately the comments in https://github.com/oleg68/GrandOrgue/discussions/64 show severe lack of understanding on how GrandOrgue works and why things are done the way they are. I too think that the menu system and more importantly the settings dialog should be re-arranged and split up into logical parts/places. However, I do think that we should keep all the relevant information and discussions in the official repository and not split it up or maintain multiple places of feature requests, issues etc. So, yes we can import the things from Oleg, but that's not to say that the suggestions there are good, nor something we should implement in the ways presented there.
