### ISSUE TITLE
Scoped combinations saved as full

### ISSUE THREAD

**Issue by ahall41** [GrandOrgue/grandorgue#1531]
The new yaml combinations don't appear to save scoped combinations correctly - they appear to be saved as "full", regardless. So when you reload they don't operate at all as intended.

**Comment by oleg68** [comment]
@ahall41 

1. What GO version are you using?
2. What sampleset?
3. How to reproduce (give an example of registrations, what registration is expected after loading the combination and what combination is actual)?
4. Is there this issue after loading an cmb-file instead of yaml?

**Comment by ahall41** [comment]
1. 3.11.3-0
2. Demo
3. Set scope of G1 - G3 to Montre, Prestant & Plein Jeu. Set G1 to nothing, G2 to Montre and G3 all 3 of these (all "scoped")
Save to YAML. Set to defaults and load YAML
G1 does nothing (should clear the 3 stops). G2 and G3 clear other stops - they should be unaffected.
4. CMB is OK

The .cmb file stores the settings with positive to set the switch and negative to unset it. The YAML only stores the switches which are set in the combination and marks it as "full". So when you reload the "scope" is lost.

**Comment by oleg68** [comment]
@ahall41 I could reproduce it. Thank you.

> Note that A01 is missing.

Yes, it is entended behavior. Empty combinations are not saved to yaml. If you really need it, you can add it manually with a text editor.

```
banked-generals:
  A01:
  A02:
    switches:
      007: Montre 8'
  A03:
    switches:
      007: Montre 8'
      008: Prestant 4'
      009: Plein jeu III
```

In this case G1 will operate as `General Cancel`.

**Comment by ahall41** [comment]
"Yes, it is entended behavior."
@oleg68 - I recall that you put in a correction where there was an anomaly in that you could create empty combinations for divisionals but not generals (or was it _vice _versa__?). Either way it can be useful to have a combination which turns off several stops (maybe a division), and leaves the others intact. 
If you can set a combination which turns (all) stops off, you should be able to save and reload it so it works exactly as it did? In the above example the A0 combination has been lost ...

**Comment by oleg68** [comment]
@ahall41 I'm trying to fix it. Could you test [the new intermediate build](https://github.com/oleg68/GrandOrgue-official/actions/runs/5093934245)?

**Comment by ahall41** [comment]
Yes, this is working as expected (after a brief examination). Thanks.
