### ISSUE TITLE
MacOS + sound card usb = invalid number of channels 

### ISSUE THREAD

**Issue by dewal5** [GrandOrgue/grandorgue#1550]
I had no problem with this card on PC.

It's not only this specific sound card. I tried two others and give me the same problem/error. 
"Open of the audio stream for Pa: Core Audio: USB Audio CODEC:
failed: Invalid numbers of channels."
"the device does not support the requested channel count"

I change channels with no result. 

On built speakers/card works great. 
On built in monitor/screen works great

**Comment by oleg68** [comment]
@dewal5 

1. Download and install the last version of GrandOrgue.
2. Post the File->Settings->Audio screenshot here.
3. Try to use `RtAudio` instead of `PortAudio`.
4. Post here the exact error message from the Log window.

**Comment by dewal5** [comment]
Hello 
I've the last version of GrandOrgue ✅
Set to RtAudio ✅
RtAudio doesn't work either. Believe me I tried almost everything 

![Zrzut ekranu 2023-05-31 o 09 20 15](https://github.com/GrandOrgue/grandorgue/assets/93423039/721b40b4-d480-4674-83f1-5dbe05f7e569)
![Zrzut ekranu 2023-05-31 o 09 20 10](https://github.com/GrandOrgue/grandorgue/assets/93423039/eeab099a-22f5-45c7-9c4d-cbc3e4253ffa)
![Zrzut ekranu 2023-05-31 o 09 19 56](https://github.com/GrandOrgue/grandorgue/assets/93423039/06dd924c-aecb-40ce-b882-b62a236dda6b)

![Zrzut ekranu 2023-05-31 o 09 22 25](https://github.com/GrandOrgue/grandorgue/assets/93423039/a14327da-86b5-44a6-8043-c1ab9879ec54)

**Comment by dewal5** [comment]
Any idea?

**Comment by oleg68** [comment]
This error is rased inside CoreAudio, so it is the same with RtAudio and PortAudio.

The reason is GrandOrgue tries to open the audio device with two channels (as they are confirured in Audio Settings), but your usb audio interface has a different number of channels.

What audio device do you have?

**Comment by dewal5** [comment]
Behringer uca200. Also with H2n zoom using as sound card

**Comment by oleg68** [comment]
Try to set Sample Rate to 48000.

**Comment by dewal5** [comment]
I've already tried

**Comment by oleg68** [comment]
A better workaround is to install `qjackctl`, setup and start jack and use 'Jack: Native Output'.

**Comment by oleg68** [comment]
The reason of this error is that
- GrandOrgue matches sound devices by name
- The generic MacOs usb sound driver exposes two devices with exactly the same name; one for input and one for output
- GrandOrgue tries to open a wrong device for output

**Comment by oleg68** [comment]
@dewal5 could you try an intermediate GO build from https://github.com/oleg68/GrandOrgue-official/actions/runs/5215177145 ?

**Comment by dewal5** [comment]
"This job was skipped."
I cannot download releases  yet.

**Comment by dewal5** [comment]
I'm trying. Maybe I don't see it.
I clicked the link provide. 
I don't see dmg to download
