### ISSUE TITLE
BUG: off value in send for "ON" button no longer overrides the off value in send for organ stops.

### ISSUE THREAD

**Issue by David-Poole** [GrandOrgue/grandorgue#1555]
Hello,

I use Novation Launchpads for stop control and set velocity numbers for the off and on values in the send dialog.
Since the recent updates, the off value for the "ON" button in Master Controls no longer overrides the off value for the organ stops in any of the samplesets I use, however, it does override the off values for my Generals, G.C. and SET pistons. When I change samplesets or shut down G.O., all my stops are still lit up. Please fix this, it makes it really challenging when switching samplesets to have to double launch them.

David

**Comment by David-Poole** [comment]
I attached a video to this comment that highlights my issue. The orange lit pads on the bottom right of both launchpads are the test subjects. I trapped them "ON" by assigning a stop to them, turned the stop on and then reassigned the stop to a different pad. Under normal circumstances, when I turn off GO, they would stay on. All my pads are set for a 0 off velocity with the Master Controls "ON" button. As you can see, the only pads that shut off when I shut down GO were my test pads. I hope this clarifies the issue, and I hope my video uploads!

**Comment by David-Poole** [comment]
This photo is with GO launched.
![20230530_192709](https://github.com/GrandOrgue/grandorgue/assets/83727709/dd4671ca-0f7a-4964-b430-0782a3c24587)

This photo is after I shut down GO
![20230530_192726](https://github.com/GrandOrgue/grandorgue/assets/83727709/1c095330-6725-48d8-aec6-ecb992eb5f23)

On the right launchpad, the pads that went out were my SET, G.C. and General Presets. As you can see, all my stops are still lit up with their default note-off values. Please note that in the first picture, there's not engaged stops or general presets.

I hope this helps explain my problem. I wish I could help with the code base, but the only language I have any real experience with is python.

**Comment by oleg68** [comment]
@David-Poole I cann't understand what does `override` mean.

 Do you want that MIDI OFF messages would be sent for all stops that were engaged when the user closes an organ?

**Comment by David-Poole** [comment]
What I mean is that when shutting down GO or switching samplesets that if there's MIDI send events set for the "ON" button, that the off and on values for the velocity take precedence over the velocity values for the stops and other
MIDI controls. For example, let's say I have set send and receive information for an 8' Diapason for MIDI number 11 on channel 1 for my Novation Launchpad. For the SEND I have velocity number 15 for the off value and velocity number 13 for the on value. For the "ON" button I have in the SEND 9x-NOTE OFF and the velocity for note off set to 0. Currently,  GrandOrgue is only taking the values I have set for the stops and is ignoring what I have set for the "ON" button when I  shutdown GO or switch samplesets.Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by oleg68** [comment]
@David-Poole 

Could you post here the screenshots of Midi Event Settings (both Receive and Send pages) for one stop (ex.  `8' Diapason`) and for the `ON` button in the master control.

**Comment by David-Poole** [comment]
Attached are the photos of my MIDI settings. As you can see, for the stop, I have a non zero off value. That's to assign a dimmer version of the colour I assigned for that stop, and the number in the on value is a brighter version of the same color. As you can see I have assigned a velocity number of 0 for the off value of the on button sent to the same MIDI number but for all devices. I have tried isolating for the device in question and the problem still persists.
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by oleg68** [comment]
> Attached are the photos of my MIDI settings.

I can not see any files attached.

**Comment by David-Poole** [comment]
![pro-zdEpKa8W](https://github.com/GrandOrgue/grandorgue/assets/83727709/4d141b07-91e2-404d-89a4-80189fd0c973)
![pro-vgduchsv](https://github.com/GrandOrgue/grandorgue/assets/83727709/ef455fff-5086-452b-8ad5-f9192a4eeaa9)
![pro-0DY6MI7D](https://github.com/GrandOrgue/grandorgue/assets/83727709/49d708b9-c933-4f5d-b4ca-957611af9732)
![pro-OP16LBfx](https://github.com/GrandOrgue/grandorgue/assets/83727709/6a457cd3-4e17-4c0f-ad5d-6c12fb9ad0eb)

**Comment by David-Poole** [comment]
Sorry about that, I didn't realize they wouldn't get posted by responding via email. I hope these are sufficient.

**Comment by oleg68** [comment]
I reproduced this issue with your settings. When you close the organ, GrandOrgue sends both MIDI messages independently

```
22:35:06.005  Ch  0, Note Off  33
22:35:06.006  Ch  0, Note On  33, Vel  15
```

in an unpredictable order, so you launchpad may discard ``Note On  33, Vel  15`` with ``Note Off  33`` if it comes later.

I suggest not to use the same note number (33) for `ON` and for any stops. I'd set up your launchpad to use different midi notes for different stops and a separate note for the ON button.

It is not a GrandOrgue issue, because it sends all messages you have set up and GrandOrgue can not predict how your launchpad resolves the conflicting midi messages. You are responsible for correct midi setting.

**Comment by David-Poole** [comment]
I find that interesting. When I produced this video https://youtu.be/0_EV_7JA-fE back in March, I never had this issue at all. Everything was fine up until version 3.12. Ever since version 3.12, I've been having this issue.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by oleg68** [comment]
@David-Poole The order of sending midi messages for different buttons is not documented and it may be changed from one version to another.

So make your midi setting working regardless the message order.

When a midi receiver receives several `Note` messages with the same MIDI note number, it discards all messages except the last one. So *use separate midi note numbers for different buttons*.
