### ISSUE TITLE
Drawstop text not visible

### ISSUE THREAD

**Issue by eturpault** [GrandOrgue/grandorgue#1570]
In some HW sample sets, the drawstops are defined by two dissociated objects : 
- a switch which defines the images of the drawstop,
- a label without background which defines the text to display inside the image.
There is none link between them in the HW ODF, so no possibility to automatically associate them together and create a GO switch with text and image attributes.
The consequence is that the label text is not visible in the panel because it is drawn behind the image by GO.
Is it possible that GO systematically draw the texts over the images ?

**Comment by lewisalexander2020** [comment]
from what I can gather, it’s possible that the images for the switches have the texts embedded to the image so the texts aren’t visible to an assistive tech service, etc.

lew

**Comment by larspalo** [comment]
@eturpault Labels are not expected to update really, whereas the drawstops/buttons can have on/off states which change. Nor is any element that changes state expected to be drawn in the same positions as others, there is no layer handling in the wxDC (last drawn is the one on top). Are you absolutely certain that there's no way to link the objects in the ODF so that the text could be migrated to the correct element that it belongs to? (A very last resort could be some logic to check for overlapping bounding boxes)

**Comment by eturpault** [comment]
@larspalo : Thinking about this during the night I went to the same idea as you, what I can try to do is, when a label has to be converted and it has no background image, to scan the buttons of the same panel and if the label overlaps one button, to set the attribute DispLabelText of this button with the label text, and to not convert the label. I will try to implement this.

**Comment by oleg68** [comment]
If we decide to implement this issue, we will need to redisplay label every time when the drawstop state is changed.

**Comment by eturpault** [comment]
I implemented for OdfEdit v2.5 the merge of a label text inside the switch / setter / enclosure that it overlaps, it works well. So I close this issue.

**Comment by lewisalexander2020** [comment]
With mentioning ODF edit, is there anyone here who could make a version of this for the mac please? I realise it’s an ask, but worth a try, I noticed it as an exe version for Windows , etc.

lew

**Comment by eturpault** [comment]
OdfEdit being implemented in Python, it is possible to run it on Mac OS. There are two solutions (to run on a Mac computer, that I don't have) : 

- execute OdfEdit as a Python script, as described [here in the readme](https://github.com/GrandOrgue/ODFEdit)
- someone is willing to create an executable of OdfEdit for Mac OS using [pyinstaller ](https://pyinstaller.org/en/stable/usage.html)(as I am doing for Windows and Linux) and share this executable in the release pages of OdfEdit. The pyinstaller parameters that I use on my computer are available [here](https://github.com/GrandOrgue/ODFEdit/pull/3#issuecomment-1421386968).
