### ISSUE TITLE
[Regression] Noise stops are not displayed.

### ISSUE THREAD

**Issue by kerkovits** [GrandOrgue/grandorgue#1583]
Steps to reproduce:

Sample: http://binauralpipes.com/Iba/Iba1.1.zip or http://binauralpipes.com/Lochtum/Lochtum1.1.zip
Version: 3.12.1
The Klingel, Cimbelstern and friends are not visible. The log is filled with warnings about unused display properties from the ODF.

They were present in older versions.

**Comment by oleg68** [comment]
@kerkovits Could you try to open these organs with [the intermediate build](https://github.com/GrandOrgue/grandorgue/actions/runs/5455267006). Seems #1590 also fixed this issue.

**Comment by kerkovits** [comment]
Yes, it is fixed.
