### ISSUE TITLE
Switches are not distributed among manuals in a yaml file

### ISSUE THREAD

**Issue by oleg68** [GrandOrgue/grandorgue#1599]
When a user exports combinations from a new-style panel organ to a yaml file, all switches are saved globally instead of under manuals. Example:

```
generals:
  0:
    switches:
      001: Sousbasse 16'
      002: Bourdon 8'
      007: Montre 8'
      016: Hautbois 8'
  1:
    switches:
      001: Sousbasse 16'
      002: Bourdon 8'
      003: Contrebasse 16'
      007: Montre 8'
      008: Prestant 4'
      014: Bourdon 8'
      018: Gamba 8'
      022: II/I
```

So it is unusable for a user to read these combinations.

**Comment by oleg68** [comment]
> It's kind of expected that switches should be listed globally for generals as they are never referenced from a manual for them

Why must not the switches in generals be referenced from a manual?

**Comment by larspalo** [comment]
@oleg68 Because the switches, like the tremulants are global objects (they can affect more than one manual).

**Comment by oleg68** [comment]
> @oleg68 Because the switches, like the tremulants are global objects (they can affect more than one manual).

But in most samplesets they belong only to a single manual for each.

So I'd look at the usage counter: if the switch is used only in one manual, it woud be referenced from the manual, otherwise it would be global.

**Comment by oleg68** [comment]
> Switches in the generals always had their own section of reference

I understand that this is the current behavior, but I cann't understand why the distribution inside an internal file format (.cmb) must not be changed?

> previously stored combinations should still be working as before

Yes, of cause. I want to load both global and manual switches from .cmb, but save into the new file only as manual swithes (if they are referenced from only one manual).

**Comment by larspalo** [comment]
Sure. Another option of selection is to list the switches that (in the odf) are listed under the manuals (for getting the divisionals to work) also under the manuals for the generals in the yaml file. Then the odf designer can select which switches (logically) should be shown under each manual that way.

**Comment by oleg68** [comment]
@larspalo could you explain more your option? Now the ODF designer already can select switches in each manuals. The problem is that it is ignored in cmb/yaml files now.

**Comment by larspalo** [comment]
Currently, the switches listed under the manuals are only there for getting divisionals to work. But couldn't you use that listing for the yaml combinations to also list/sort the switches set in a general to be shown under the manual (that they are listed under)? Then the switch enumeration under the manual would also serve a logical purpose.

Still it could possibly be so that a switch actually affects more than one manual, but usually one only lists the switches that logically belong to a manual under the manual in question.

**Comment by oleg68** [comment]
> Still it could possibly be so that a switch actually affects more than one manual, but usually one only lists the switches that logically belong to a manual under the manual in question.

I wouldn't change anything in this case. I'd only list switches under a manual only if they affect only one manual.

What do you mean as `list of switches`? I mean `list of switches` as the `SwitchXXX` keys in `ManualXXX` sections of ODF.

**Comment by larspalo** [comment]
> I mean list of switches as the SwitchXXX keys in ManualXXX sections of ODF.

Yes, exactly. If it's listed there it should be possible to also show such a switch under the manual even in a general combination for the yaml, right?

**Comment by larspalo** [comment]
@oleg68 Have you decided on the strategy for listing of the general combinations? If a switch is listed under the manual, then it's also included under the manual for a general, not only the divisionals? For switches not listed under any manual - still as global?

**Comment by oleg68** [comment]
Yes, I have.

Switches are not referenced from any manual or referenced from more than one manual will be considered as global. But switches referenced from exactly one manual will be considered as manual-level.

All .cmb or .yaml files will be imported regardless where the switches are referenced from, so all old saved combinations will be still playable. But the new combinations will be saved according the manual ownership.
