### ISSUE TITLE
The organ loading progress dialog size is not stable

### ISSUE THREAD

**Issue by oleg68** [GrandOrgue/grandorgue#1600]
When loading a large sampleset with GrandOrgue from the `grandorgue-wx32` package for linux, the progress dialog changes it's horisontal size every second as the size of the path string of the loaded sample.

There is no such problem with wxWidgets 3.0.

**Comment by oleg68** [comment]
This issue is a result of a wxWidget bug introduced with https://github.com/wxWidgets/wxWidgets/commit/4101849b4d0a4e1291e45cd990611eb9408c68a1 since 3.1.

I submitted a [PR](https://github.com/wxWidgets/wxWidgets/pull/23727) to the wxWidgets repo.

I'm planning to submit the same PR against the 3.2 branch.

Because GrandOrgue for windows uses the precompiled wxWidgets mingw build https://github.com/GrandOrgue/WxWidgetsCross, we'll need to upgrade it to 3.2 and to apply the same patch there.

**Comment by oleg68** [comment]
Will be fixed in wxWidgets 3.2.3 https://github.com/wxWidgets/wxWidgets/milestones/3.2.3

After that, we'll build wx for windows and we will switch GO builds for windows to it.

**Comment by rnditdev** [comment]
May I add a request for showing the progress percentage in the window bar?

**Comment by ahall41** [comment]
And while doing so ... ignore the time taken to process the ODF in the time to wait ... it might be more accurate (I assume this is what causes it - typically starts off as several minutes to go, but ends up as 1 minute or so on my slow laptop!)
