### ISSUE TITLE
changing gains of multiple ranks at once givesm "release length is invalid" error

### ISSUE THREAD

**Issue by davidgritter** [GrandOrgue/grandorgue#1601]
I have been trying to change the gain of multiple ranks at once on the audio/midi/organ settings panel.  For example I have a diapason rank on a direct windchest, a diffues windchest, and a rear windchest (6 channel surround)  I can change the gain of each diapason rank individually without error, but if I select all three ranks, then change the gain,  I get the "release length is invalid" error when I hit the apply button.  You can demonstrate this in the Grandorgue demo V1 organ by trying to change the Hautbois 8 and Trompette 8 gains simultaneously.  I recall that I could change multiple gains at one time in grandorgue many versions ago.

**Comment by kerkovits** [comment]
I observed this bug a month ago, or something like that. I found the workaround to enter "Max" into the release length. The issue is present not only with gain but with any other setting (e.g. tuning, load channels).
