### ISSUE TITLE
Convultion Reverb (settings)

### ISSUE THREAD

**Issue by Bumblebee001** [GrandOrgue/grandorgue#1617]
I have tried this feature in GO before by adding the path of an IR file I had and it seemed like it worked as expected.

I do not understand why the program informs the user that this feature is not yet supported:
![image](https://github.com/GrandOrgue/grandorgue/assets/6999990/23fd59e4-bf71-4b2e-aa45-a064a4331d05)

Can you kindly check this out, perhaps removing the pop up that shows in the picture above?

**Comment by Bumblebee001** [comment]
![image](https://github.com/GrandOrgue/grandorgue/assets/6999990/4cdbd2c6-25fb-4f84-a532-257aa833b464)

:-(

**Comment by Bumblebee001** [comment]
So am I understanding correctly that the issue will be tackled in v 3.12.3?

**Comment by oleg68** [comment]
@Bumblebee001 Yes, it will. The fix #1621 is ready, but it has not yet been merged upstream.
