### ISSUE TITLE
Only Note Off (0x80) is sent for "note off"

### ISSUE THREAD

**Issue by larspalo** [GrandOrgue/grandorgue#1640]
According to MIDI standard both the specific Note Off message (0x80 0x.. 0x..) as well as the Note On with velocity 0 (0x90 0x.. 0x00) is interpreted as a "note off". This is correctly handled for the receiving of MIDI messages in GrandOrgue. However, when sending messages GrandOrgue currently always send the Note Off message (0x80), even when explicitly sending a Note On message with velocity 0, which is possible to do but it's converted to a Note Off message when actually sent from GO.

The reason why this is important is that some MIDI equipment understand (use) only messages of the type Note On with velocity 0 to function at all. (I recently tested using an Akai APC mini mk2 that needs exactly this to turn off the light of the led pads)

My thoughts are that it would be beneficial if the user could decide how the note off message should be sent from GO. This could be done with for instance a checkbox for "Send Note Off as Note On w. Velocity 0" that could be customized for every individual send event, or possibly set as a default for a specific device. Thoughts about that?

**Comment by larspalo** [comment]
@oleg68 I've implemented a quick way of allowing to select how to send "Note Off" in https://github.com/larspalo/grandorgue/tree/FlexibleNoteOff that works fine in my tests so far, but as you're working on the MIDI right now I don't know how it fits with your plans generally. Did you intend to solve it in another way?

**Comment by oleg68** [comment]
@larspalo Now I'm working on #1392. I planned to start working on this isue after #1392, but if you have already implemented it, I'd see your PR.
