### ISSUE TITLE
Unison Off (U.O.) coupler gets stuck

### ISSUE THREAD

**Issue by organart** [GrandOrgue/grandorgue#1643]
I'm using the Eisenbarth sample set.

If U.O. coupler is drawn on the Hauptwerk manual when GrandOrgue is shut down, then when GrandOrgue is restarted, the organ acts as though U.O. is always drawn, even when not.  The 16' and 4' couplers work fine.

How to replicate the problem:
1. Draw the Principal 8' (or any set of stops) on Hauptwerk, and the U.O. coupler in the Coupler 2. Hauptwerk panel.
2. Perform a File->Save.
3. Restart GrandOrgue
4. Retire the U.O. coupler.
5. Play notes (assumes stops on Hauptwerk are drawn.)  Nothing will be heard.

Workaround fix:
1. Retire the U.O. coupler
2. Perform a File->Save.
3. Restart GrandOrgue.

Notes:
1. Restarting GrandOrgue without the File->Save before the restart did not fix the problem.
2. I didn't try a similar scenario for the other manuals.
3. I tried replicating the problem three times, and it failed twice.

I'm using v0.3.1.2330 of GrandOrgue.

Now that I know about this, I'm personally not too concerned about it.  I've been using GrandOrgue for several years and just now tripped over this bug.  I hope this helps someone else solve their problem if they encounter it.

**Comment by rousseldenis** [comment]
@organart Have you tried the latest version of GrandOrgue?

**Comment by organart** [comment]
Thanks for your reply.  I do like to stay current, but I don't look that often.  I don't like to fix things that aren't broke.

Where do I go to get the latest version?  I looked on Sourceforge and it showed the same version as I have.  It also sends me to github.  I look on github, and it shows version 3.12.3-1, which is way past what I have.  I didn't see a link to download an install package for a known stable version.  I don't want to download the source and build.  If you can point me to the download for the latest stable version, that would be greatly appreciated.

**Comment by rousseldenis** [comment]
> Thanks for your reply. I do like to stay current, but I don't look that often. I don't like to fix things that aren't broke.
> 
> Where do I go to get the latest version? I looked on Sourceforge and it showed the same version as I have. It also sends me to github. I look on github, and it shows version 3.12.3-1, which is way past what I have. I didn't see a link to download an install package for a known stable version. I don't want to download the source and build. If you can point me to the download for the latest stable version, that would be greatly appreciated.

@organart the GrandOrgue versions beginning by 0. are very old ones.

Usually, most of platforms are supported in build that are generated on releases, so, you could find your happiness there. You can also download the source code. You find them under 'Assets' section under the release you look for.

Here are the list of releases: https://github.com/GrandOrgue/grandorgue/releases

**Comment by organart** [comment]
Thanks for the info.

Art

**Comment by oleg68** [comment]
@organart When you start GrandOrgue, it cann't know the current state of hardware switches, because they send MIDI messages only when their state is changed. So if you have made something wheng GrandOrgue is shut down, GrandOrgue will not take it into account.

I cann't fix this behavior due the MIDI restrictions.
