### ISSUE TITLE
Midi files are saved as wav.

### ISSUE THREAD

**Issue by kerkovits** [GrandOrgue/grandorgue#1644]
Addendum to https://github.com/GrandOrgue/grandorgue/issues/1629

GrandOrgue 3.12.3
Fedora 38
Wx 3.2

Panel->Record/play->Record MIDI->Stop
Expected result: GO saves a MIDI file
What happens instead: GO saves a valid MIDI to MIDI recordings, but with an extension *.wav

**Comment by oleg68** [comment]
@kerkovits I cann't reproduce this issue. When I press 'REC' at the second line (`MIDI recorder`), a new file is created in the $HOME/`GrandOrgue/MIDI recordings` directory with the `.mid` extension.

Could you tell, which buttons did you press on the midi recorder panel?

**Comment by briff** [comment]
I have the same issue. Start up GO, click Midi Record, click Midi Stop, and a wav file is created.

**Comment by briff** [comment]
So it seems this happens probably only when Hungarian is the language, doesn't happen with English, German and French. I've looked at the code and this makes no sense, but this happens :)

**Comment by oleg68** [comment]
@briff Thank you for very important information. I managed to reproduce the issue.
