### ISSUE TITLE
Failed to open the graphic on sample set loading

### ISSUE THREAD

**Issue by eturpault** [GrandOrgue/grandorgue#1650]
I moved the PC of my organ from Windows to Linux Ubuntu 22.04.3 LTS.
I installed successfully the file grandorgue_3.12.3-1_amd64.deb according to the procedure described [here](https://github.com/GrandOrgue/grandorgue/blob/master/INSTALL.md).
The embedded demo sample set can be loaded and played without issue. 
But when I load a sample set which contains images (not provided by GO), I get systematically the following Load error message just after the ODF parsing is completed, on the first image loading : Failed to open the graphic '...\...png'.
In the log messages window, there are two messages : 
```
Warning: Unknown image data format.; FileName=...\...png
Error: Failed to open the graphic '...\...png'
```
Same issue if the first loaded image has the bmp format.
Same issue if I run GrandOrgue from the AppImage file.

How can it be solved ? 
Probably it is a problem of missing dependencies, but I find nothing in the issues or discussions about similar problem.
Thanks.

**Comment by jason-barba** [comment]
Can you open any .png file with another app than GO?

**Comment by eturpault** [comment]
Yes .png / .bmp / .jpg files can be opened without issue with the file viewer of Ubuntu for example.

**Comment by eturpault** [comment]
Looking at the source code of GO, the error "Failed to open the graphic" is generated by the fonction GOBitmap GOBitmapCache::GetBitmap in the file GOBitmapCache.cpp, which calls the function loadFile of the same class, itseslf calling the function LoadFile of the class wxImage of the lib wxWidgets. Probably it is this function which returns an error.

Here is the wxWidgets packages installed on my PC, is something missing ? : 

> $ sudo apt-cache search libwxgt*
> libwxgtk-media3.0-gtk3-0v5 - wxWidgets Cross-platform C++ GUI toolkit (GTK 3 media library runtime)
> libwxgtk-media3.0-gtk3-dev - wxWidgets Cross-platform C++ GUI toolkit (GTK 3 media library development)
> libwxgtk-webview3.0-gtk3-0v5 - wxWidgets Cross-platform C++ GUI toolkit (GTK 3 webview library runtime)
> libwxgtk-webview3.0-gtk3-dev - wxWidgets Cross-platform C++ GUI toolkit (GTK 3 webview library development)
> libwxgtk3.0-gtk3-0v5 - wxWidgets Cross-platform C++ GUI toolkit (GTK 3 runtime)
> libwxgtk3.0-gtk3-dev - wxWidgets Cross-platform C++ GUI toolkit (GTK 3 development)

**Comment by eturpault** [comment]
I have no issue with the Burea church sample set of Palo Lars.
I have issue with Strassburg of Piotr Grabowski or Frankfurt of Sonus Paradisi, which were loaded without issue in Windows, strange...

**Comment by larspalo** [comment]
@eturpault My first suggestion would be to carefully compare the image paths against the actual images for case differences. The Windows file system is not case sensitive but the Linux is. The differences can be very subtle but still cause issues.

**Comment by eturpault** [comment]
Unfortunately it is not that simple, I double checked, the character cases are the same between the ODF and real path/file names (I remember I had to take this case sensitive constraint into account in OdfEdit for HW to GO conversion). Only the path separator was different (\ instead of /), but changing it has not solved the problem.
I checked with Friesach of P.Graboswki, it loads well, whereas Strassburg of P.Graboswki and Frankfurt or Prytanée of Sonus Paradisi doesn't load due to image issue, very strange. 
I will continue to make tests to try to understand, if someone has an idea about the reason of this I am very interrested.

**Comment by eturpault** [comment]
Friesach has also only .png images and I have no issue to load it.
I have finally understood the problem. Before to install Linux on my computer instead of Windows, I had two partitions on the hard disk : a first one for Windows and a second one to store the sample sets. I have installed Linux on the first partition whereas I have let the second one unchanged. I had the issue with the sample sets written in the second partition when the OS was Windows. The sample sets working well were the one written in the second partition when the OS was Linux.
By writting again the Strassburg sample set now that the OS is Linux permits now to load it with GO without issue.
It was a tricky situation ! Thank you @larspalo for your kind support.

**Comment by oleg68** [comment]
@eturpault 

I tried to reproduce opening the Strassburg Sample Set with GrandOrgue from a Windows partition without success: it was opened without any issues.

How do you mount the windows partition in linux?
What is the full path of the Strassburg Sample Set in your linux system?

**Comment by eturpault** [comment]
I cannot answer you about how I mount the Windows partition in Linux. I have finally formatted my whole hard disk from a Linux USB pen then reinstalled Linux and the sample sets in a unique partition, I have no more issue now.
When the issue was present, the sample sets where stored in another disk automatically mounted by Linux that I accessed by "Other Locations" / "On This Computer" in the file explorer.

**Comment by ahall41** [comment]
If it helps, I don't have a problem opening sample sets in Linux on an NTFS partition ...  mounted as:
`/dev/nvme0n1p5	/home/go	ntfs	uid=1000,gid=1000,dmask=027,fmask=137	0 0
`

**Comment by oleg68** [comment]
@eturpault 
1. Was it a USB stick or a hard drive partition?
2. What filesystem type was there? NTFS or FAT?

**Comment by oleg68** [comment]
> If it helps, I don't have a problem opening sample sets in Linux on an NTFS partition ... mounted as: `/dev/nvme0n1p5 /home/go ntfs uid=1000,gid=1000,dmask=027,fmask=137 0 0 `

It would help if you reproduced the problem.

**Comment by eturpault** [comment]
@oleg68 
It was a hard drive partition, in NTFS format. What is strange is that GO was able to read the ODF of the sample set but not its images.

**Comment by oleg68** [comment]
> @oleg68 It was a hard drive partition, in NTFS format. What is strange is that GO was able to read the ODF of the sample set but not its images.

I made a separate NTFS disk partition and I could load the Strassburg organ from it without any problems.

So I can not fix fhis issue without reproducing. Feel free to reopen this issue when you have the same problem again and be ready to provide me additional information.

**Comment by oleg68** [comment]
> @oleg68 It was a hard drive partition, in NTFS format. What is strange is that GO was able to read the ODF of the sample set but not its images.

I made a separate NTFS disk partition and I could load the Strassburg organ from it without any problems.

So I can not fix fhis issue without reproducing. Feel free to reopen this issue when you have the same problem again and be ready to provide me additional information.

**Comment by oleg68** [comment]
> @oleg68 It was a hard drive partition, in NTFS format. What is strange is that GO was able to read the ODF of the sample set but not its images.

I made a separate NTFS disk partition and I could load the Strassburg organ from it without any problems.

So I can not fix fhis issue without reproducing. Feel free to reopen this issue when you have the same problem again and be ready to provide me additional information.
