### ISSUE TITLE
AppImage creates multiple copies of the demo organ

### ISSUE THREAD

**Issue by ahall41** [GrandOrgue/grandorgue#1660]
Every time you launch GrandOrgue as an Appimage (after the first), you get an error e.g.
`Thu 21 Sep 2023 17:49:48 BST: 17:49:48: Error: can't open file '/tmp/.mount_grandoWSlhCy/usr/share/GrandOrgue/packages/demo-4232D4C616E4B99145537F02B34D342D4E3E3808.orgue' (error 2: No such file or directory)`
Together with another copy of the demo organ. And continue to do so until you switch to "Start without any organ".

**Comment by oleg68** [comment]
Fixed with #1681 and #1682
