### ISSUE TITLE
Feature request: Retain size of dialog boxes

### ISSUE THREAD

**Issue by ahall41** [GrandOrgue/grandorgue#1662]
Some dialog boxes are shown too small (e.g. Help #1661) and need to be resized. It would be helpful if this could be permanent (at least for the session)?

**Comment by oleg68** [comment]
Duplicates #1035

**Comment by ahall41** [comment]
@oleg - Great work. One small problem - in the Organs dialog - could you also retain the size of the Path column - or at least make it autofit the display?
