### ISSUE TITLE
SYSEX Hauptwerk 32 Byte LCD Name length in preset

### ISSUE THREAD

**Issue by willeke1234** [GrandOrgue/grandorgue#1686]
The maximal length of a SYSEX Hauptwerk 32 Byte LCD Name MIDI event is 32. If an event with length 32 is saved in a preset then loading the preset results in error "Out of range value at section 'Switch002' entry 'MIDISendLength001': 32".

**Comment by radionerd** [comment]
Thanks Oleg. Your first work around works well. I can now open the Pitea organ once more and continue my console development. Would you be able to suggest an app for opening the cmb file? My ubuntu graphical extraction tool does not seem up to the job.

I'm inclined to leave my issue open as it underlines several issues:

 - Only the time and date of the .cmb file might offer a clue as to its purpose or its possible role in a workaround.
 - We should be pedantic about the configurations that we save
 - And gracious about loading the configurations that we open.
 
Thanks so much for your help. I'm keen to explore your second option of inspecting the .cmb file, and might even try building GO later this evening to try to investigate further.
Cheers
Richard
