### ISSUE TITLE
Organ fails to start with invalid configuration

### ISSUE THREAD

**Issue by radionerd** [GrandOrgue/grandorgue#1696]
While trying to understand the format of sysex messages to my LCDs which seem to vary in text start position I suspect that I configured the metronome displays (BPMinute or BPBar) of PiteaMHS badly. Now the organ fails to start with the following log message displayed:

> Sun 29 Oct 2023 15:54:08: 15:54:08: Error: Out of range value at section 'SetterCurrentPosition' entry 'MIDISendLength001': 32

Selecting the panel tab, where I would expect to see the Metronome panel, a blank rectangle is displayed. This prevents me from updating/correcting the configuration so I am stuck. I cannot even determine what the bad configuration item is. The organ was running nicely before I closed and restarted it.

![Screenshot from 2023-10-29 16-31-08](https://github.com/GrandOrgue/grandorgue/assets/3194568/742b3422-b937-4be4-9862-85619d2beca1)

Ideally I would like to be able to restore the organ configuration to something that starts without losing the unrelated receive and send event configurations. The problem occurred running grandorgue-3.12.3-1.linux.aarch64, and persists with grandorgue-3.13.0-1.linux.aarch64. This seems like a bug to me.

The setup is:
- Console:  Homebrew USB connected running on STM32F103C8T6 Blue pill in active development
- Computer: Raspberry Pi4 4GB
- OS: Ubuntu Linux 22.04
- Organ: Pitea MHS
- GO Versions 3.13.0-1.linux.aarch64 and 3.12.3-1

Any help, or suggestions for further investigations much appreciated. Thanks for such a wonderful project.

**Comment by oleg68** [comment]
A workaround: delete the old .cmb file from the GrandOrgue/Data folder, start GrandOrgue and make the configuration from scratch. Don't use 32 as the midi message length due the bug #1686.

A more complex workaround: unpack the text file from the .cmb file, change the MIDISendLength001 value to 31 and replace the packed .cmb file with the plain text file.

**Comment by radionerd** [comment]
Thanks Oleg. Your first work around works well. I can now open the Pitea organ once more and continue my console development. Would you be able to suggest an app for opening the cmb file? My ubuntu graphical extraction tool does not seem up to the job.

I'm inclined to leave my issue open as it underlines several issues:

 - Only the time and date of the .cmb file might offer a clue as to its purpose or its possible role in a workaround.
 - We should be pedantic about the configurations that we save
 -  And gracious about loading the configurations that we open, maybe warnings would be better behaviour for issues.

Thanks so much for your help. I'm keen to explore your second option of inspecting the .cmb file, and might even try building GO later this evening to try to investigate further.
Cheers
Richard

**Comment by oleg68** [comment]
> * Only the time and date of the .cmb file might offer a clue as to its purpose or its possible role in a workaround.

File->Settings->Organs, select the organ and press to ``Delete preset(s)``

also ``Organ hash`` contains the name of the organ settings file.

> And gracious about loading the configurations that we open, maybe warnings would be better behaviour for issues.

Agree. It will be the subject of the issue.

**Comment by larspalo** [comment]
> Would you be able to suggest an app for opening the cmb file? My ubuntu graphical extraction tool does not seem up to the job.

Right click on the .cmb file in Nautilus.
"Extract here" and a file named data will appear that you can open in any text editor (the file is an ini type config file)

As usual, the recommendation is that one doesn't edit the .cmb files manually, but sometimes it can indeed save the day...

**Comment by radionerd** [comment]
Thanks Oleg and Lars for your very helpful suggestions. I must have fumbled the .cmb file extraction previously. Using 'nautilus' aka 'files' I successfully extracted and viewed the .cmb file and located the troublesome field value of [SetterCurrentPosition]...MIDISendLength001=32. Yesterday I re-created the organ configuration avoiding the field value of 32, so I'll not risk file editing this time around. 

The source code build instructions for debian work perfectly on rpi4 taking 50 minutes to compile. I do have a much faster Ubuntu x86 machine if you would like me to test any fixes for this issue.

Thanks Lars for the excellent video series. Is the Barton 3-7 organ sample set featured in your Full and 2nd touch video available for download somewhere please? Maybe I should consider designing a velocity sensing pedal board!
