### ISSUE TITLE
Build on Mint 21.2 fails - missing libpthread.so

### ISSUE THREAD

**Issue by ahall41** [GrandOrgue/grandorgue#1700]
As a quick bodge, I ran `sudo ln -s /usr/lib/x86_64-linux-gnu/libpthread.so.0 /usr/lib/x86_64-linux-gnu/libpthread.so`, however perceived wisdom (sorry I can't find the reference I had earlier) is this should not be a dependency in the makefile, but rather use -pthread option for gcc?

Without it you get this error:
```
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libpthread.so', needed by 'bin/GrandOrgue'. Stop.
make[1]: *** [CMakeFiles/Makefile2:550: src/grandorgue/CMakeFiles/GrandOrgue.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

**Comment by oleg68** [comment]
@ahall41 I cannot reproduce this problem.

I installed mint 21.2 docker image from https://hub.docker.com/r/linuxmintd/mint21.2-amd64 in a podman container, ran ``build-scripts/for-linux/prepare-debian-based.sh`` and then ``build-scripts/for-linux/build-on-linux.sh``. GrandOrgue was built without any errors.

How did you try to build GrandOrgue?

**Comment by ahall41** [comment]
As described (I seem to recall). I had just upgraded from an earlier version of Mint, rather than a fresh install. When I googled the error message (I can no longer find the link), the bottom line is that the dependency on libthread.so should be removed from the makefile, and the -pthread option passed to gcc instead.

**Comment by ahall41** [comment]
Just installed Ubuntu Cinnamon - got the same error!

**Comment by oleg68** [comment]
@ahall41 You have not yet answered my question ``How did you try to build GrandOrgue?``

**Comment by ahall41** [comment]
As you described - build-scripts/for-linux/prepare-debian-based.sh and then build-scripts/for-linux/build-on-linux.sh. The dependency on libthread.so needs to be removed from the makefile, and the -pthread option passed to gcc instead.

**Comment by ahall41** [comment]
Except ... I've just removed the symlink and it has built OK with the latest version. I don't think any further action is needed as I can no longer see the reference in the Makefile.
