### ISSUE TITLE
Proper EnglishUse

### ISSUE THREAD

**Issue by Bumblebee001** [GrandOrgue/grandorgue#1716]
Hi Oleg,

Avoid ”cann’t” as it is not used in English. If anything it is “can’t” with one “n”.

In writing we use “cannot” in full. This is true for other words like isn’t (is not), shouldn’t (should not) and so on. Avoid abbreviations when writing especially in help files and dialogue boxes. 

Mark

**Comment by rousseldenis** [comment]
@Bumblebee001 thanks for this. Are you able to propose a PR with correct strings? Thanks

**Comment by Bumblebee001** [comment]
Im not sure I understand your reply fully.

**Comment by Bumblebee001** [comment]
Should be: “I’m” and since this is a “chat” it will be acceptable.

**Comment by rousseldenis** [comment]
@Bumblebee001 I wanted to say, if you want to contribute and change existing strings, you can propose a Pull Request here in order to correct terms. GrandOrgue is open to everyone that want to contribute.

**Comment by Bumblebee001** [comment]
I do participate already.

I’ve been using GO ever since it was created more than a decade ago and I
have been producing sample sets for it too (Maltese Historic Pipe Organs).
😉

**Comment by oleg68** [comment]
@Bumblebee001 Having searched the GrandOrgue source code I found several occurences of ``can not`` but I couldn't find any ``cann't``. Where did you see them?
