### ISSUE TITLE
Panic button hangs

### ISSUE THREAD

**Issue by willeke1234** [GrandOrgue/grandorgue#1726]
If I forget to connect my Bluetooth MIDI devices, I use the Panic button to rescan the MIDI devices. Every now and then, GO hangs when I press the Panic button. Steps to reproduce:

1. Load a sample set (demo).
2. Hit the Panic button repeatedly.

or

1. Load a sample set (demo).
2. Pull all the stops and press all keys.
3. Hit the Panic button.
4. Repeat step 2 and 3.

GO 3.13.2

[Samples.zip](https://github.com/GrandOrgue/grandorgue/files/13415853/Samples.zip)

**Comment by oleg68** [comment]
1. MacOs?
2. Did this issue experience with 3.13.1?
3. Do you use RtAudio or PortAudio?

**Comment by willeke1234** [comment]
1. Yes, macOS 14 and macOS 10.15
2. GO 3.13.0 (macOS 14) and GO 3.7 (macOS 14 and macOS 10.15) also hang.
3. GO 3.13.2 uses PortAudio and GO 3.7 uses RtAudio.

**Comment by oleg68** [comment]
@willeke1234 could you test my attemt to fix this issue https://github.com/oleg68/GrandOrgue-official/tree/bugfix/panic-hang ?

If GrandOrgue still hangs please attach the stacktrace.

**Comment by oleg68** [comment]
@willeke1234 Lets continue our iteration at #1736
