### ISSUE TITLE
Debian AMD64 and ARM64 versions crash on clicking Enable Convolution Reverb

### ISSUE THREAD

**Issue by djbottrill** [GrandOrgue/grandorgue#1741]
Running the AMD64 version on a MAC running Linux Mint or Ubuntu or a Raspberry Pi 5 running Raspberry PI OS (Debian):
 in settings if you click the Enable Convolution Reverb check box causes GO to crash with the error message:

Unhandled unknown exception; terminating the application.

I don't know if this is related but just opening the settings dialog gives the following error message:

(GrandOrgue:2299): Gtk-CRITICAL **: 12:39:30.528: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton

although all the other functions in settings do seem to work without a problem.

**Comment by oleg68** [comment]
What version of GrandOrgue are you trying?

**Comment by djbottrill** [comment]
I've just done a hack and copied GrandOrgueConfig and GrandOrgueConfig.last from the now working system to the non-working installation and this has brought over the Reverb settings obviously I had to reset the Audio settings, but at least it now works.
