### ISSUE TITLE
Cache files

### ISSUE THREAD

**Issue by Bumblebee001** [GrandOrgue/grandorgue#1750]
One thing that has irked me for a long time is the randomly generated long alphanumeric names of cache files. 
eg: 439A8C1BE59F555EF3CEE0C74ADCB1A105778AC6-0.cache
529CC35CFB06E14F316E691B40215AE4F9612E41.idx

So many incredible things have been made possible in the digital world. 

Surely this could be improved to indicate more specifically which sampleset the cache file/s pertain to.

**Comment by oleg68** [comment]
Go to the File->Settings->Organs and look at the cache names.

**Comment by Bumblebee001** [comment]
There are no "cache" references on that tab.

There are Organ hash, Package id, Package hash ...... all different long alphanumeric values but I see no cache. The closest I was able to compare as the cache is the Organ hash but not all organs installed seem to generate such cache in the cache folder.

Could it be possible to generate a simpler and more identifiable set of details? Why should things be made so user unfriendly? My moto in whatever I have done in life (be it music or medicine or anything else in between) has always been "keep it simple"!
