### ISSUE TITLE
Respect tempo changes in loaded MIDI

### ISSUE THREAD

**Issue by khenisey** [GrandOrgue/grandorgue#1753]
When loading a MIDI for play back in GO, it seems like GO plays using the last tempo meta-event occurring in the file. I believe the intended implementation of "set tempo" system meta event (type `0x51`) sent after some delay is to change the milliseconds per timing pulse (where the pulses per quarter note are defined in the MIDI header's division bytes) for pulses that occur only after the tempo event.

For example, the MIDI file encoded below (in base64) plays two measures starting at 240bpm and changing to 120bpm at the beginning of the second measure. Windows Media Player plays this file correctly. GO, on the other hand, plays the eight pitches at the same tempo, specifically, the last tempo encountered in the first track (120bpm).

Base64 encoded example tempo change MIDI:
```
TVRoZAAAAAYAAQACAWhNVHJrAAAAEwD/UQMD0JCLIP9RAwehIAH/LwBNVHJrAAAATACRPH+CaIE8fwCRPn+CaIE+fwCRQH+CaIFAfwCRQX+CaIFBfwCRQ3+CaIFDfwCRRX+CaIFFfwCRR3+CaIFHfwCRSH+CaIFIfwH/LwA=
```

**Comment by oleg68** [comment]
Already fixed with #1232
