### ISSUE TITLE
Issue install grandorgue

### ISSUE THREAD

**Issue by janvanveldhuizen** [GrandOrgue/grandorgue#1777]
▶ sudo dpkg -i Downloads/grandorgue_3.13.3-1_amd64.deb 
Selecting previously unselected package grandorgue.
(Reading database ... 179692 files and directories currently installed.)
Preparing to unpack .../grandorgue_3.13.3-1_amd64.deb ...
Unpacking grandorgue (3.13.3-1) ...
dpkg: dependency problems prevent configuration of grandorgue:
 grandorgue depends on libwxbase3.0-0v5 (>= 3.0.4+dfsg); however:
  Package libwxbase3.0-0v5 is not installed.
 grandorgue depends on libwxgtk3.0-gtk3-0v5 (>= 3.0.4+dfsg); however:
  Package libwxgtk3.0-gtk3-0v5 is not installed.
 grandorgue depends on libwxgtk3.0-gtk3-0v5 (>= 3.0.4+dfsg-10~); however:
  Package libwxgtk3.0-gtk3-0v5 is not installed.

dpkg: error processing package grandorgue (--install):
 dependency problems - leaving unconfigured
Processing triggers for desktop-file-utils (0.26-1) ...
Processing triggers for mailcap (3.70+nmu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for man-db (2.11.2-2) ...
Processing triggers for shared-mime-info (2.2-1) ...
Errors were encountered while processing:
 grandorgue

My version of libwxbase is 3.2-1. Which is definitely >=3.0.4

**Comment by janvanveldhuizen** [comment]
When checking libwxbase, it says:

▶ sudo apt install libwxbase3.2-1                     

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libwxbase3.2-1 is already the newest version (3.2.2+dfsg-2).
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 grandorgue : Depends: libwxbase3.0-0v5 (>= 3.0.4+dfsg) but it is not installable
              Depends: libwxgtk3.0-gtk3-0v5 (>= 3.0.4+dfsg) but it is not installable
              Depends: libwxgtk3.0-gtk3-0v5 (>= 3.0.4+dfsg-10~) but it is not installable
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

**Comment by janvanveldhuizen** [comment]
I already solved the issue by using the AppImage version.

**Comment by janvanveldhuizen** [comment]
AppImage solved the dependencies issu

**Comment by oleg68** [comment]
> packages have unmet dependencies: grandorgue : Depends: libwxbase3.0-0v5 (>= 3.0.4+dfsg) but it is not installable Depends: libwxgtk3.0-gtk3-0v5 (>= 3.0.4+dfsg) but it is not installable Depends: libwxgtk3.0-gtk3-0v5 (>= 3.0.4+dfsg-10~) 

You are trying to install grandorgue_3.13.3-1_amd64.deb, that relays on wxgtk3.0, that is not present in your distro.

Because your distro has wxgtk3.0, you should install grandorgue-wx32_3.13.3-1_amd64.deb instead.

**Comment by janvanveldhuizen** [comment]
Ah, of course. That makes sense. Thx!
