### ISSUE TITLE
Default MIDI settings not applied where there is a default .cmb file

### ISSUE THREAD

**Issue by ahall41** [GrandOrgue/grandorgue#1785]
Where there is a default combination file, containing (say) combination or tuning settings only, which is then loaded on startup, the default MIDI settings (keyboard, swell, GC, etc), should also be applied.

**Comment by ahall41** [comment]
Some suggestions:
1. As well as importing a default .cmb settings, also import default .yaml
2. If the .cmb file does no contain a midi (or key stroke) setting, apply the default after import (including import settings)
3. OR Apply defaults after importing a default cmb (but not after a saved .cmb)
I think it can be assumed that, by and large, the defaults are what the user wants to use?

**Comment by oleg68** [comment]
> 1. As well as importing a default .cmb settings, also import a default .yaml with the same name as the .organ

There is no any reason of importing a default .yaml because the combinations can be stored in the default .cmb,
