### ISSUE TITLE
Build on Raspberry Pi - missing packages

### ISSUE THREAD

**Issue by abehnke** [GrandOrgue/grandorgue#1799]
Following the "BUILD.md" instructions for "Building for Linux"
On Rasberry Pi 4 - debian bookworm

The step "#2. Manually" is missing or unclear about some packages. I found that the phrase "development packages" means surround the name with "lib" and "-dev".

Thus: libfftw3-dev libwavpack-dev libwxgtk3.2-dev 

Not mentioned in the "BUILD.md": 
 libyaml-cpp-dev imagemagick libudev-dev
 
Rebuild was done to see if reverb is fixed.  3.9.5 I got no reverb - but with 3.14 reverb works!

**Comment by oleg68** [comment]
@abehnke Raspbian is a debian-based linux system. Did you try to use build-scripts/for-linux/prepare-debian-based.sh for installing dependencies?

**Comment by abehnke** [comment]
I did not try the build-scripts. (no particular reason)  I followed the BUILD.md "Building for Linux on Linux" following the steps that had the word "Manually".  The finally result was successful.  Each time the build stopped due to a missing part, I fetched the missing part and continued.

**Comment by oleg68** [comment]
@abehnke could you test if build-scripts/for-linux/prepare-debian-based.sh is sufficient for installing all necessary dependencies?

**Comment by abehnke** [comment]
Yes - the prepare-debian-based.sh works fine.  I did the following:

installed a fresh Raspberry Pi OS on a SD card
sudo apt update && sudo apt upgrade
sudo shutdown -P now # and restart
uname -a
Linux rasp4x 6.1.0-rpi8-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.73-1+rpt1 (2024-01-25) aarch64 GNU/Linux
git clone --recurse-submodules https://github.com/GrandOrgue/grandorgue.git
sudo ~/grandorgue/build-scripts/for-linux/prepare-debian-based.sh
mkdir gobuild
cd /home/abehnke/gobuild
cmake -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" /home/abehnke/grandorgue
make
... 
quick run of GrandOrgue program to check if it plays - yes it does
so all appears OK

**Comment by oleg68** [comment]
@abehnke thank you for your test.

So the only thing to do is to update BUILD.md according the last prepare-debian-based.sh
