### ISSUE TITLE
Synchronize the stops at startup

### ISSUE THREAD

**Issue by William-Purvis** [GrandOrgue/grandorgue#1806]
When I start up GrandOrgue, it seems to remember which stops were set at shutdown. However, it doesn't tell my
console, so the lights on the tabs don't agree with the actual settings. There doesn't appear to be any setting in the 
setup dialogue to request this. How do other people manage?

**Comment by jason-barba** [comment]
What OS du you use?

I use Ubuntu 22.04 LTS and can shutdown with the computer's power button with GO running. When restart, GO comes up in the mode defined by the last Save.

**Comment by William-Purvis** [comment]
On 18/02/2024 08:39, Jens Andersson wrote:
>
> What OS du you use?
>
> I use Ubuntu 22.04 LTS and can shutdown with the computer's power 
> button with GO running. When restart, GO comes up in the mode defined 
> by the last Save.
>
I'm running Debian 12. Yes, I can do that, but it seems to be a crude 
method. I was brought up to believe
that things should be shut down in an orderly manner! I guess the 
SIGTERM method is probably going to
be the nearest I can manage.

Bill

-- 
+----------------------------------------+
| Bill Purvis                            |
| email: ***@***.***                  |
+----------------------------------------+

**Comment by jason-barba** [comment]
> I'm running Debian 12. Yes, I can do that, but it seems to be a crude method. I was brought up to believe that things should be shut down in an orderly manner! I guess the SIGTERM method is probably going to be the nearest I can manage. 

I have used the "crude" method for many years now without any problems (so far anyway).

//Jens

**Comment by oleg68** [comment]
@William-Purvis If you set up sending midi of all your stops, then GrandOrgue sends midi out messages for these stops each time GrandOrgue starts. Please check your midi output settings.
