### ISSUE TITLE
Enclosure - AmpMinLevel=0

### ISSUE THREAD

**Issue by ahall41** [GrandOrgue/grandorgue#1813]
If you set AmpMinLevel=0, and then completely close the enclosure, nothing will sound on re-opening until another note is played. These enclosures are usually used to regulate the sound balance between near and far perspectives, and is only a problem if you want to change the balance in real time using a midi controller. The work round is to code AmMinLevel=1, but at this setting some sound will bleed through.
I don't think this is a high priority, but thought the phenomenon should be recorded (I recently forgot to code 1 and set it to 0 and someone complained about it!)

**Comment by eturpault** [comment]
You will find some exchanges we had on this topic here : https://github.com/GrandOrgue/grandorgue/discussions/1381#discussioncomment-4939401

**Comment by ahall41** [comment]
I'm not convinced as if you set AmpMinLevel to 0, some sound still bleeds through - which may or may not be desirable. Perhaps the spec should be changed, so that 0 generates a warning? And add a 'health warning' to the Help too? If 0 sets the pipe to 'off' then perhaps it could be some ridiculously low value that is inaudible?

**Comment by oleg68** [comment]
I think AmpMinLevel=0 ahould be considered as a valid value and the current GrandOrgue behavior as an incorrect.

**Comment by larspalo** [comment]
> AmpMinLevel=0 ahould be considered as a valid value

It **is** a valid value, **and** it mutes the sound - as it forces an amplitude of zero on any attack sample - which also incidentally cancels any existing attack sample and returns the sampler to the pool because that's how the audio engine fader works.

**Comment by oleg68** [comment]
> that's how the audio engine fader works

I'm going to change the audio engine behavior.

**Comment by larspalo** [comment]
> I'm going to change the audio engine behavior.

Ok, but it will require quite a lot of care.
