### ISSUE TITLE
size limit for images in GO 

### ISSUE THREAD

**Issue by pgwid-og** [GrandOrgue/grandorgue#1840]
Yesterday I tried to convert a new sample set (http://www.pipeloops.com//product_info.php?products_id=64) to GO. It uses bitmaps with the size 5760 x 3336, which is obviously too large for GO (afaik the max size is 4000). Since HD pictures are much bigger than the ones in old days, it might be the time to  enlarge the upper limit for image sizes?
It is a bit  annoying to rescale the images and calculate all the position parameters in the ODF again, although Lars' GoODF helps a bit with this job.
Oliver

**Comment by larspalo** [comment]
If I remember correctly, the limit of the image size comes actually from the limit of the panel size.

**Comment by larspalo** [comment]
The size limit is imposed in GOConfigReader::ReadSize funcion. So to change it it's necessary to alter the file src/core/config/GOConfigReader.cpp line 544:

`if (100 <= size && size <= 4000)`

which is a no-brainer.

Given 8K UHD a raise to 8000 would currently be enough, but there are even higher resolutions available so 16000 or greater isn't out of the question. ;-)

**Comment by oleg68** [comment]
I would increase it to 30000

**Comment by larspalo** [comment]
@oleg68 Then it should be 32000 to match the 4K increases that seems to be current screen resolution development.

**Comment by oleg68** [comment]
> @oleg68 Then it should be 32000 to match the 4K increases that seems to be current screen resolution development.

OK

**Comment by pgwid-og** [comment]
Thank you for the quick solution.
