### ISSUE TITLE
Wave tremulant on/off affects pipes that should not be affected.

### ISSUE THREAD

**Issue by larspalo** [GrandOrgue/grandorgue#1855]
Currently due to a bug, likely in the crossfading/new attacking re-work of the audio engine, a wave based tremulant will affect a default sample (IsTremulant=-1) that should not be affected by the wave-based tremulant on the same windchestgroup by triggering a new attacking/fading. Both odfs in the tremulant demo sample set linked below shows this. For instance in the IsTremulantDemo.organ one can activate the Plain stop, hold down a key and activate/de-activate the Wave tremulant (that should not affect the Plain stop at all (it has a default value of IsTremulant=-1) and hear the effect of the bug.

[TremulantDemo.zip](https://github.com/GrandOrgue/OdfEdit/files/14750019/TremulantDemo.zip)

This sample set assumes GO v3.14.0, an earlier version needs the Percussive=N value added to the ranks.

**Comment by oleg68** [comment]
@larspalo I tried to fix this bug. Could you test https://github.com/oleg68/GrandOrgue-official/actions/runs/8544025323 ?

**Comment by larspalo** [comment]
@oleg68 Yes, this seems to work now as it should.
