### ISSUE TITLE
DefaultToEngaged is described in the help as required

### ISSUE THREAD

**Issue by eturpault** [GrandOrgue/grandorgue#1874]
In the help of GrandOrgue, the attribute DefaultToEngaged of a Drawstop object is described as being required. In fact, looking at the source code in GODrawstop::Load it is optional at False by default, and even it is ignored if the switch has not the Input funtion.
Could the help be aligned to the implementation ?

**Comment by eturpault** [comment]
Looking again at the GrandOrgue source code, DefaultToEngaged is required only if the drawstop function is Input (or not defined). In other cases it is ignored.
This is good, as if the drawstop has input switches its initial state is defined by the initial state of its input switches, there is no need to define its own initial state with DefaultToEngaged.

**Comment by oleg68** [comment]
Fixed with #1920
