### ISSUE TITLE
RtAudio submodule using a commit that is orphan (not on any branch)

### ISSUE THREAD

**Issue by hfiguiere** [GrandOrgue/grandorgue#1888]
RtAudio submodule using a commit that is orphan (not on any branch)

![image](https://github.com/GrandOrgue/grandorgue/assets/114441/eaeb81e0-5b40-4553-9927-d60fb19dbfea)

This cause the flatpak build to fail.

```
fatal: Fetched in submodule path 'submodules/RtAudio', but it did not contain 6e962c0422b5953c82466ecf07765c471a7bfacb. Direct fetching of that commit failed.
```

**Comment by hfiguiere** [comment]
If this commit is on a fork, then the submodule should point to that fork.

**Comment by kerkovits** [comment]
The patch provided affects only Windows, so for Linux, you should build against the official release.

**Comment by hfiguiere** [comment]
There is no source package, and the github generated one exclude submodules. So it's pulled form the git tag, and that's where the submodule bug is.

**Comment by kerkovits** [comment]
There is no source package?

I successfully build GO for Linux using
http://www.music.mcgill.ca/~gary/rtaudio/release/rtaudio-6.0.1.tar.gz
https://github.com/GrandOrgue/grandorgue/archive/refs/tags/3.14.1-1.tar.gz

**Comment by hfiguiere** [comment]
for GrandOrgue. This is GrandOrgue issue tracker, isn't it?

**Comment by kerkovits** [comment]
Or alternatively, https://github.com/GrandOrgue/grandorgue/releases/download/3.14.1-1/grandorgue-wx32-3.14.1-1.src.rpm contains all sources in the submodule directory.
