### ISSUE TITLE
Issue with Detect Complex MIDI Setup

### ISSUE THREAD

**Issue by pipe-organ-enthusiast** [GrandOrgue/grandorgue#1895]
When using "Detect Complex MIDI Setup" for organ stops, after going through the setup of toggling the control on and off,
the event listed is still "9x Note" when it should be "9x Note On Toggle".

When using "Detect Complex MIDI Setup" for Manuals and Pedalboards, the event "9x Note" is correct, but the "Lowest Velocity" is not. The "Lowest Velocity" should be 1, NOT 0 because when the "Lowest Velocity" is 0, the notes don't send a note-off event when released. 

NB: I was previously using Arch Linux. None of the links provided worked on that distro. I am currently using Kubuntu 24.04 and I am using the grandorgue-wx32_3.14.1-1_amd64.deb build as the grandorgue_3.14.1-1_amd64.deb would not build on my machine.

**Comment by larspalo** [comment]
Fix of this issue was committed about 5 days ago, test a more recent build like https://github.com/GrandOrgue/grandorgue/actions/runs/8838235975 until a new release is out.

**Comment by oleg68** [comment]
3.14.1-1 does not contain the fix #1884 . It is included in official intermediate build since 3.14.2-0.3and will be available in the future release 3.14.2-1.
