### ISSUE TITLE
MIDI Signals on Shutdown of GrandOrgue

### ISSUE THREAD

**Issue by pipe-organ-enthusiast** [GrandOrgue/grandorgue#1896]
When terminating GrandOrgue, the MIDI events for the "ON" button in "Master Controls" should be sent AFTER MIDI events for the organ stops, divisionals, generals, etc. This is NOT happening. I'm still having my Novation Launchpads remain illuminated with the stop layout from my last used sampleset when I exit GrandOrgue.

**Comment by larspalo** [comment]
Fix of this issue was committed less than 5 days ago, test a more recent build like https://github.com/GrandOrgue/grandorgue/actions/runs/8838235975 until a new release is out.

**Comment by pipe-organ-enthusiast** [comment]
I successfully installed this build and tested it. It works exactly as
expected.
Thanks so much!

**Comment by oleg68** [comment]
Already fixed
