### ISSUE TITLE
GO 3.14+ hangs on Windows 10

### ISSUE THREAD

**Issue by rousseldenis** [GrandOrgue/grandorgue#1906]
I have a feedback of a GO user that the versions >= 3.14 hang on Windows 10 at organ loading (Alessandria).

I don't have more details than it's a freezing of the application without messages.

@oleg68 Is it possible that this is related to https://github.com/GrandOrgue/grandorgue/issues/1878 ?

**Comment by rousseldenis** [comment]
In fact, I had a temporary problem with Alessandria loading on Linux too. It seemed blocked for a few seconds, then loaded successfully.

**Comment by oleg68** [comment]
> versions >= 3.14 hang on Windows 10 at organ loading (Alessandria).

I need more information.
1. What step of loading GO hangs at? Providing some screen video would be very useful.
2. Is this problem affects only `Alessandria` or other organs as well?
3. Can GrandOrgue load `Alessandria` with the `-g` (`--gui-only`) option?

> @oleg68 Is it possible that this is related to #1878 ?

Everything is possible, but it does not look as probable.

> In fact, I had a temporary problem with Alessandria loading on Linux too. It seemed blocked for a few seconds, then loaded successfully.

`Alessandria` requires a lot of RAM. Blocking loading for a few seconds may be linked with swap activity.

**Comment by JPIL04** [comment]
Bonjour,
je viens d'essayer de mettre à jour la version 3.14 de GO, pour continuer d'utiliser Alessandria (j'utilisais la version spéciale V3.14.0-0.2 qui fonctionnée parfaitement , suite à mon problème #1772...)
Mais maintenant , impossible de charger l'orgue...Message d'avertissement : élèment ODF non utilisé...et ça reste bloqué sur 10% du chargement ....même au bout de 15 minutes !
Heureusement, je suis repassé à ma version précédente V3.14.0-0.2 et tout remarche correctement. Suis-je condamné à rester sur ma version ? J'ai lu sur facebook que beaucoup d'utilisateurs avaient eu des problèmes ...
merci pour votre aide ( PS : je n'ai pas de fichier DMP à vous envoyer ...j'ai interrompu le chargement brutalement !)

**Comment by oleg68** [comment]
@rousseldenis Is #1918 the same?

**Comment by rousseldenis** [comment]
> @rousseldenis Is #1918 the same?

Yes, looks like.

**Comment by oleg68** [comment]
Duplicates #1918
