### ISSUE TITLE
chargement alessandria impossible avec la version V3.14 sous Windows 10

### ISSUE THREAD

**Issue by JPIL04** [GrandOrgue/grandorgue#1918]
Bonjour,
je viens d'essayer de mettre à jour la version 3.14 de GO, pour continuer d'utiliser Alessandria (j'utilise la version spéciale V3.14.0-0.2 qui fonctionnait parfaitement , suite à mon problème https://github.com/GrandOrgue/grandorgue/issues/1772 ...)
Mais maintenant , impossible de charger l'orgue...dés l'ouverture de GO : Message d'avertissement : élèment ODF non utilisé ........sur des dizaines de ligne et ça reste bloqué sur 10% du chargement ....même au bout de 20 minutes !
Heureusement, je suis repassé à ma version précédente V3.14.0-0.2 et tout remarche correctement. Suis-je condamné à rester sur ma version ? J'ai lu sur facebook que beaucoup d'utilisateurs avaient eu des problèmes ...
merci pour votre aide ! 
nota : C'est peut-être le même soucis que le dernier commentaire de Denis Roussel ??? 
( PS : je n'ai pas de fichier DMP à vous envoyer ...j'ai du interrompre le chargement brutalement, au bout de 20 minutes !)

**Comment by oleg68** [comment]
@JPIL04 Pourriez-vous faire les actions suivantes?

1. Startez GO 3.14.2 avec Alessandria.
2. Jusqui apres GO a commencer a charger MAIS AVANT il bloque, pressez sur le Cancel button. Une avertissement de charge partielle sera, pressez sur le OK.
3. Allez a File->Setting->Organs.
4. Cliquez l'Alessandria orgue et pressez sur le 'Delete cache' boutton; apres pressez sur le OK.
5. File->Reload.

Est-ce que Alessandria se charge? Si ca marche, vous devez repetes les meme actions pour starter une previous version de GO apres 3.14+.

**Comment by JPIL04** [comment]
b‌onjour 
 

De : "Oleg Samarin" ***@***.***>
A : "GrandOrgue/grandorgue" ***@***.***>,"JPIL04" ***@***.***>,"Mention" ***@***.***>
Envoyé: samedi 1 Juin 2024 09:52
Objet : Re: [GrandOrgue/grandorgue] chargement alessandria impossible avec la version V3.14 sous Windows 10 (Issue #1918)
 

Bonjour Oleg

J'ai fait ce que vous avez indiqué...Mais je n'arrive pas à bloquer le démarrage de GO....Le message d'erreur est plus rapide et bloque toute action !
Y-a t'il d'autres solutions ?

merci

Jpil04

@JPIL04 Pourriez-vous faire les actions suivantes?


	Startez GO 3.14.2 avec Alessandria.
	Jusqui apres GO a commencer a charger MAIS AVANT il bloque, pressez sur le Cancel button. Une avertissement de charge partielle sera, pressez sur le OK.
	Allez a File->Setting->Organs.
	Cliquez l'Alessandria orgue et pressez sur le 'Delete cache' boutton; apres pressez sur le OK.
	File->Reload.


Est-ce que Alessandria se charge? Si ca marche, vous devez repetes les meme actions pour starter une previous version de GO apres 3.14+.

**Comment by oleg68** [comment]
@JPIL04 excusez-moi, que je ne vous'ai pas repondee rapidement.

Si vous n'avez pas le temps d'arreter le démarrage de GrandOrgue de la version nouvelle, mais une version ancienne marche, vouos pouvez supprimer le cache avec la version qui marche.

1. Startez GrandOrggue de la version ancienne.
2. Allez a File->Settings->Organs
3. Cliquez l'Alessandria orgue et pressez sur le 'Delete cache' boutton; apres pressez sur le OK.
4. Quittez GrandOrgue. Ne startez plus la version ancienne, sinon vous devrez repeter les etapes (2) et (3)
5. Startez GrandOrgue de la version nouvelle
6. Si Alessandria marche, vous pouver supprimer le cache des autres ogrues avec la version nouvelle pendant elle marche

**Comment by JPIL04** [comment]
Bonjour Oleg,

Merci pour les dernières indications. J'ai fait exactement ce qui était écrit :
 Lancer GO avec ma version V3.14.0-0.2 qui fonctionne. J'ai supprimé le cache, puis j'ai redémarré avec version V3.14.2-1. ...mais hélas, exactement le même message et le chargement qui tourne en boucle autour des 9% de chargement. Ci-dessous la copie d'écran ...et toujours pas de fichier DMP car j'ai interrompu le chargement au bout de 40 minutes !!!!

[cid:457f6149-c18d-4388-afe2-45128c4e05ee]
Cordialement,  JPIL04

________________________________
De : Oleg Samarin ***@***.***>
Envoyé : jeudi 6 juin 2024 09:52
À : GrandOrgue/grandorgue ***@***.***>
Cc : JPIL04 ***@***.***>; Mention ***@***.***>
Objet : Re: [GrandOrgue/grandorgue] chargement alessandria impossible avec la version V3.14 sous Windows 10 (Issue #1918)


@JPIL04<https://github.com/JPIL04> excusez-moi, que je ne vous'ai pas repondee rapidement.

Si vous n'avez pas le temps d'arreter le démarrage de GrandOrgue de la version nouvelle, mais une version ancienne marche, vouos pouvez supprimer le cache avec la version qui marche.

  1.  Startez GrandOrggue de la version ancienne.
  2.  Allez a File->Settings->Organs
  3.  Cliquez l'Alessandria orgue et pressez sur le 'Delete cache' boutton; apres pressez sur le OK.
  4.  Quittez GrandOrgue. Ne startez plus la version ancienne, sinon vous devrez repeter les etapes (2) et (3)
  5.  Startez GrandOrgue de la version nouvelle
  6.  Si Alessandria marche, vous pouver supprimer le cache des autres ogrues avec la version nouvelle pendant elle marche

**Comment by oleg68** [comment]
@JPIL04 Ou peux je regarder la copie d'ecran?

**Comment by JPIL04** [comment]
Voici la copie d'écran....Le 8 juin 2024 19:23, Oleg Samarin ***@***.***> a écrit :
@JPIL04 Ou peux je regarder la copie d'ecran?

**Comment by oleg68** [comment]
> Voici la copie d'écran

Il n'y a pas de copie d'ecran ici.

Etez-que vous prets a lancer la version ge GrandOrgue avec une impression de debogage supplementaire?

**Comment by JPIL04** [comment]
je vous renvoie la copie d'écran.

Quelle est la manipulation que vous voulez que je fasse ?

Cordialement
JPIL04
________________________________
De : Oleg Samarin ***@***.***>
Envoyé : samedi 15 juin 2024 15:38
À : GrandOrgue/grandorgue ***@***.***>
Cc : JPIL04 ***@***.***>; Mention ***@***.***>
Objet : Re: [GrandOrgue/grandorgue] chargement alessandria impossible avec la version V3.14 sous Windows 10 (Issue #1918)


Voici la copie d'écran

Il n'y a pas de copie d'ecran ici.

Etez-que vous prets a lancer la version ge GrandOrgue avec une impression de debogage supplementaire?

**Comment by oleg68** [comment]
> Quelle est la manipulation que vous voulez que je fasse ?
- Telechargez https://github.com/oleg68/GrandOrgue-official/actions/runs/9536322735/artifacts/1606123409
- Decompressez ce fichier dans un derectoire
- Lancez une fenetre de commande (cmd.exe)
- Executez la commande
    ``<Chemin a la directoire>\bin\GrandOrgue.exe >load.log 2>&1``
- Cette version de GrandOrgue chargera tres lentement mais ecrira le fichier `load.log`
- Quand GO arret de charger, interrompez ca et postez le fichier `load.log` ici.
- Repetez les memes etapes et postez l'autre fichier `load.log` ici.

**Comment by oleg68** [comment]
@JPIL04 Y at'il un progres?

**Comment by JPIL04** [comment]
Bonsoir

Je n'ai pas encore eu le temps d'essayer en suivant vos indications ! cette période est un peu chargée (quelques concerts à préparer...) et je ne voulais pas prendre le risque de ne pas pouvoir m'entrainer si GO ne fonctionnait plus  !

J'ai juste fait un essai de démarrer un autre orgue avec la nouvelle version V3.14.2-1  (avec Dluga Koscielna de piotr Grabowski) et ça fonctionne. Le problème vient juste d' Alessandria , apparemment !

Je vous tiens au courant, dès que possible

JPLI04
De : "Oleg Samarin" ***@***.***>
A : "GrandOrgue/grandorgue" ***@***.***>,"JPIL04" ***@***.***>,"Mention" ***@***.***>
Envoyé: dimanche 23 Juin 2024 16:26
Objet : Re: [GrandOrgue/grandorgue] chargement alessandria impossible avec la version V3.14 sous Windows 10 (Issue #1918)
 

 

@JPIL04 Y at'il un progres?

**Comment by oleg68** [comment]
@JPIL04 etes-vous prets de commencer les tests?

**Comment by JPIL04** [comment]
Bonjour,Je suis en vacances loin de chez moi.  Je ferai le test à mon retour fin août. Merci.Jpil04 Le 5 août 2024 20:26, Oleg Samarin ***@***.***> a écrit :
@JPIL04 etes-vous prets de commencer les tests?

**Comment by oleg68** [comment]
@JPIL04 Bonnes vacances! 

J'attends les resultats de votre tests.

**Comment by JPIL04** [comment]
Bonjour,

Je viens de reprendre le test que vous avez proposé. Malheureusement, je n'arrive pas à lancer GO en suivant vos indications ?????
Ci joint la copie d'écran que j'ai ...[cid:2ff8435a-9ed5-4000-a945-583a7b66cd7e]
________________________________
De : Oleg Samarin ***@***.***>
Envoyé : mardi 6 août 2024 10:18
À : GrandOrgue/grandorgue ***@***.***>
Cc : JPIL04 ***@***.***>; Mention ***@***.***>
Objet : Re: [GrandOrgue/grandorgue] chargement alessandria impossible avec la version V3.14 sous Windows 10 (Issue #1918)


@JPIL04<https://github.com/JPIL04> Bonnes vacances!

J'attends les resultats de votre tests.

**Comment by JPIL04** [comment]
Re bonjour

J'ai essayé de nouveau directement avec la commande cmd.exe... voila le message d'erreur que j'obtiens :
[cid:c72b96ff-6883-4d88-b69a-3dfcc6e0fe2f]
________________________________
De : Oleg Samarin ***@***.***>
Envoyé : mardi 6 août 2024 10:18
À : GrandOrgue/grandorgue ***@***.***>
Cc : JPIL04 ***@***.***>; Mention ***@***.***>
Objet : Re: [GrandOrgue/grandorgue] chargement alessandria impossible avec la version V3.14 sous Windows 10 (Issue #1918)


@JPIL04<https://github.com/JPIL04> Bonnes vacances!

J'attends les resultats de votre tests.

**Comment by oleg68** [comment]
@rousseldenis Avez-vous Alessandria pour fair quelques tests?

**Comment by rousseldenis** [comment]
> @rousseldenis Avez-vous Alessandria pour fair quelques tests?

Oui sous Ubuntu 24

**Comment by JPIL04** [comment]
Bonjour, j'utilise toujours alessandria avec la version de GO que Oleg m'avait envoyé (et qui fonctionne parfaitement ! ). Je suis sous Windows 10.Je veux bien faire tous les tests que vous voulez ....Le 7 nov. 2024 06:11, "Denis Roussel (ACSONE)" ***@***.***> a écrit :

@rousseldenis Avez-vous Alessandria pour fair quelques tests?

Oui sous Ubuntu 24

**Comment by oleg68** [comment]
> > @rousseldenis Avez-vous Alessandria pour fair quelques tests?
> 
> Oui sous Ubuntu 24

Y'a-t-il ce problem de chargement de l'Alessandria comme ca avec la version recente sous  Ubuntu 24?

**Comment by oleg68** [comment]
> .Je veux bien faire tous les tests que vous voulez .

Oui, mais je ne peux pas voir les resultats en votres mesages.

Ja ne sais common dechiffrer , par example,``[cid:c72b96ff-6883-4d88-b69a-3dfcc6e0fe2f]`` ou ``[cid:2ff8435a-9ed5-4000-a945-583a7b66cd7e]``.

**Comment by oleg68** [comment]
> j'utilise toujours alessandria avec la version de GO que Oleg m'avait envoyé

Quelle version? C'etait il y a tres longtemps donc je ne m'en souviens pas.

**Comment by JPIL04** [comment]
J'utilise la version V3.14.0-0.2 sous Windows 10.
Depuis que j'ai installé cette version, je n'ai eu aucun problème.

Je n'ai pas essayé la version V3.15 !!!

________________________________
De : Oleg Samarin ***@***.***>
Envoyé : jeudi 7 novembre 2024 09:14
À : GrandOrgue/grandorgue ***@***.***>
Cc : JPIL04 ***@***.***>; Mention ***@***.***>
Objet : Re: [GrandOrgue/grandorgue] chargement alessandria impossible avec la version V3.14 sous Windows 10 (Issue #1918)


j'utilise toujours alessandria avec la version de GO que Oleg m'avait envoyé

Quelle version? C'etait il y a tres longtemps donc je ne m'en souviens pas.

**Comment by oleg68** [comment]
> Je n'ai pas essayé la version V3.15

Pourriez-vous essayer la version 3.15.2-1?

**Comment by JPIL04** [comment]
je viens d'essayer de démarrer avec la version V 3.15 en utilisant cet exécutable  (pris sur GitHub) : grandorgue-3.15.2-1.windows.x86_64.exe<https://github.com/GrandOrgue/grandorgue/releases/download/3.15.2-1/grandorgue-3.15.2-1.windows.x86_64.exe>

Malheureusement, toujours le même problème....
ci joint la copie d'écran pendant que GO essaie de démarrer ....

[cid:bd6a849b-8e62-4a32-9b01-d9be11ee06f7]

________________________________
De : Oleg Samarin ***@***.***>
Envoyé : jeudi 7 novembre 2024 18:45
À : GrandOrgue/grandorgue ***@***.***>
Cc : JPIL04 ***@***.***>; Mention ***@***.***>
Objet : Re: [GrandOrgue/grandorgue] chargement alessandria impossible avec la version V3.14 sous Windows 10 (Issue #1918)


Je n'ai pas essayé la version V3.15

Pourriez-vous essayer la version 3.15.2-1?

**Comment by oleg68** [comment]
Comment peux je voir la copie d'ecran: ``[cid:bd6a849b-8e62-4a32-9b01-d9be11ee06f7]``?

**Comment by JPIL04** [comment]
[cid:e9304ab0-1d9e-4cb7-b291-91ad1278ae4f]

________________________________
De : Denis Roussel (ACSONE) ***@***.***>
Envoyé : vendredi 8 novembre 2024 07:50
À : GrandOrgue/grandorgue ***@***.***>
Cc : JPIL04 ***@***.***>; Mention ***@***.***>
Objet : Re: [GrandOrgue/grandorgue] chargement alessandria impossible avec la version V3.14 sous Windows 10 (Issue #1918)


@JPIL04<https://github.com/JPIL04> Je vous suggère d'embarquer directement l'image dans le corps du mail si vous répondez par ce biais. Sinon, le plus facile est de joindre l'image dans la discussion sur github.

**Comment by oleg68** [comment]
@JPIL04 

> [cid:e9304ab0-1d9e-4cb7-b291-91ad1278ae4f]

Ce n'est pas clair.

Vous devez changer de facon dont vous joignez les images aux messages pour que je puisse les voir.

**Comment by JPIL04** [comment]
j'essaie d'envoyer la copie d'écran ici..... en espérant que ça marche !
format png :
![Capture écran](https://github.com/user-attachments/assets/16ae550e-37f7-4b99-b8e7-55a8490e15eb)
format jpeg :
![Capture ecran](https://github.com/user-attachments/assets/d817416d-0f92-4411-9205-9af60268e8a6)
format pdf :
[capture ecran.pdf](https://github.com/user-attachments/files/17704063/capture.ecran.pdf)

**Comment by oleg68** [comment]
@JPIL04 C'est magnifique! Merci beaucoup.

**Comment by oleg68** [comment]
@JPIL04 Pourriez-vous essayer [la version nouvelle](https://github.com/oleg68/GrandOrgue-official/actions/runs/11823309974) et poster la copie d'ecran ici?

**Comment by JPIL04** [comment]
de quelle version parlez vous ? 
comme vous le voyez avec la copie d'écran, le problème a lieu aussi avec la version V3.15.2-1 !!!!

**Comment by oleg68** [comment]
> de quelle version parlez vous ? 

De la version intermediaire 3.15.3-0.4. Vous la pouvez telecharger ici: https://github.com/oleg68/GrandOrgue-official/actions/runs/11823309974

**Comment by JPIL04** [comment]
même problème ...
voici la copie d'écran :
![Capture 1](https://github.com/user-attachments/assets/f36f3904-6870-44e4-a582-f661fc56dc4e)

**Comment by oleg68** [comment]
@JPIL04 Merci. Pouriez-vous essayer la version intermediaire 3.15.3-0.8 d'ici https://github.com/oleg68/GrandOrgue-official/actions/runs/11844384777 ?

**Comment by JPIL04** [comment]
Bonjour et Merci. La version semble fonctionner normalement..... je viens de charger plusieurs fois GO et Alessandria s'ouvre normalement. Je constate juste qu'il ya une fenêtre en plus qui s'affiche lors du chargement et un message d'avertissement à la fin du chargement ; Cf. les captures d'écran 1,2 et 3 dans l'ordre du chargement  ...
![Capture 1 V3 15 3-0 8](https://github.com/user-attachments/assets/0ced8c0b-041d-46bb-b100-229fdb3387ba)
![Capture 2 V3 15 3-0 8](https://github.com/user-attachments/assets/b6fb1ee8-06ea-4811-bc59-3bf97203f6e3)
![Capture 3 V3 15 3-0 8](https://github.com/user-attachments/assets/b5b01a3c-29ac-4ba1-82a4-2bca2de4961d)

**Comment by oleg68** [comment]
@JPIL04 Pouriez-vous essayer la version 3.15.3-0.5 de https://github.com/oleg68/GrandOrgue-official/actions/runs/11861982128 ?

**Comment by JPIL04** [comment]
bonjour 
voici le résultat avec la nouvelle version V3.15.3-0.5. J'ai cru que j'aurais le même problème au début du chargement de GO (Cf. photo capture 1....), mais au bout de 2 minutes, Alessandria a continué a se charger , et il semble fonctionner normalement , avec le message d'avertissement suivant : Cf. photo capture 2...
![Capture 1](https://github.com/user-attachments/assets/5376a320-aa60-42c1-a4b6-83d53058022d)
![Capture 2](https://github.com/user-attachments/assets/156f270c-bceb-467b-88a6-2f1df7878433)

**Comment by oleg68** [comment]
@JPIL04 Merci beacoup.

Grace a vous j'ai reussi a trover les raisons du probleme. C'etaient deux raisons pour lesquelles combinaison GO ne pouvait pas charger l'Alessandria.

- La fenetre "Messages" se bloque si il'y a beacoup de messages a montrer. J'ai limitee leur quantite par 3000 en 3.15.3-0.5 et GO a commence a charger l'Alessandria.
- La modification [``Added support of specifying different crossfade length for additional attack and release files https://github.com/GrandOrgue/grandorgue/issues/1760``](https://github.com/GrandOrgue/grandorgue/commit/663d8b053af8544ae9526ce2b7e325c5a187f63d) en 3.14.0 a change la regle de specification de PipeXXXReleaseCrossfadeLength. C'est pour ca les versions nouvelles montrent beacoup de messages ``non utilise``.

**Comment by oleg68** [comment]
L'ODF d'Allesandria a les vieux PipeXXXReleaseCrossfadeLength, il faut recreer l'ODF de le Hauptwerk fichier par OdfEdit.

@rousseldenis Parce que je n'ai l'Allesandria, pourirez-vous convertir le Hauptwerk ODF a l'GrandOrgue ODF par OdfEdit 2.15?

**Comment by JPIL04** [comment]
que voulez vous que je fasse ? je ne sais pas comment exécuter ce que vous semblez demander ? je n'ai jamais utilisé OdfEdit ....
pouvez être plus clair ; Cela ne risque t'il pas de créer un conflit avec mes fichiers d'Alessandria ???

**Comment by oleg68** [comment]
@JPIL04 

> que voulez vous que je fasse ? je ne sais pas comment exécuter ce que vous semblez demander ? je n'ai jamais utilisé OdfEdit ....

Je ne suis pas sur que vous le fassiez correctement, donc je l'ai demande @rousseldenis.

Je le ferais moi-mem, mais je ne le peux pas parce que je n'ai touts les fichiers d'Alessandria et @rousseldenis les a.

> Cela ne risque t'il pas de créer un conflit avec mes fichiers d'Alessandria ???

Vous pourrez placer le .organ fichier nouveau en votre derectoire d''Alessandria avec un nom different pour eviter le conflit.

**Comment by JPIL04** [comment]
bonjour, je viens de voir qu'une version v3.15.3-1 est disponible . Est-ce que je peux mettre à jour  la version d'essai actuelle que j'utilise et passer de v3.15.3-0.8 à v3.15.3-1 ???

**Comment by oleg68** [comment]
3.15.3-1 n'a pas de changement de 3.15.3-0.8.

> Est-ce que je peux mettre à jour la version d'essai actuelle que j'utilise et passer 

Pas ancor. #2045 n'a pas ete merge a la code oficciel.
