### ISSUE TITLE
Stops slow to respond

### ISSUE THREAD

**Issue by William-Purvis** [GrandOrgue/grandorgue#1922]
Our church organ is now in regular use but GO displays an annoying problem occasionally: When pressing a divisional to bring in a different stop, the console stop lights up, as does the GUI display stop, but no sound is produced for several seconds. Normally, stops sound immediately after pressing either a divisional or individual stops, but this is very disconcerting to the player (I'm not a player, I just maintain the system.)

GO is running under Debian 12 with plenty of free RAM so it's not a page-thrashing problem.

Any ideas?

**Comment by oleg68** [comment]
Could you look at Audio/MIDI -> Log MIDI events? Do the midi events come in time?

**Comment by William-Purvis** [comment]
Well, the stop sends a midi message to GO, and GO sends a response which turns on the led in the stop immediately, so I'm assuming that's not the problem.

**Comment by oleg68** [comment]
Is this effect happens only when pressing divisionals? What happens if the stop is enabling manually (without combinations): does it start sounding immediately or not? What sample set do you use?

**Comment by William-Purvis** [comment]
THe samples are mostly the Billerbeck Semi-dry samples, With some modifications. As far as I am aware it has only happened with the divisionals. I will consult with the organist to contirm. I believe the stop which seems to cause the problem has mostly been the Tuba stop - which was the Rohrflute. I have tried to reproduce the problem myself, not being  an organ player, but it always worked OK for me.

**Comment by William-Purvis** [comment]
Just to confirm, he doesn't use the stops direct much, at least not while playing. He has only seen this when using a divisional. He also reports one instance where the same thing happend on the Pedal Contra Bourdon. The stop doesn't sound until about 3-5 seconds after selection, and that is disconcerting in the middle of playing a piece.

**Comment by oleg68** [comment]
Could you confirm that just after pushing a divisional all stops start playing immediately except `Rohrflute` and `Contra Bourdon`?

Could you post here the .organ file and the yaml file from exported combinations?

**Comment by William-Purvis** [comment]
I can't do it at present, I'm away from home for a week. I don't have up-to-date copies of the files here, but will get them to
you when I get back. I presume when you say yaml you mean the compressed *.cmb file in the Data folder?

**Comment by oleg68** [comment]
File -> 'Export combinations' to a yaml file would be better, but .cmb is also OK.

**Comment by William-Purvis** [comment]
On 23/06/2024 16:49, Oleg Samarin wrote:
>
> File -> 'Export combinations' to a yaml file would be better, but .cmb 
> is also OK.
>
I hadn't come across that one! Something new to try!

Bill

-- 
+----------------------------------------+
| Bill Purvis                            |
| email: ***@***.***                  |
+----------------------------------------+

**Comment by William-Purvis** [comment]
I can't do it at present, I'm away from home for a week. I don't have up-to-date copies of the files here, but will get them to
you when I get back. I presume when you say yaml you mean the compressed *.cmb file in the Data folder?

**Comment by William-Purvis** [comment]
Sorry, I've not been able to access the files until today.
[Test.organ.txt](https://github.com/user-attachments/files/16173749/Test.organ.txt)
[combinations.yaml.txt](https://github.com/user-attachments/files/16173760/combinations.yaml.txt)
Be aware that the names of the stops have changed from those used in the original samples.
I have somewhere a rather messy spreadsheets whic provides a mapping if required.

**Comment by William-Purvis** [comment]
I think I have tracked down the problem - nothing to do with GrandOrgue you'll be pleased to hear. I turns out that the Tuba stop
plays via a dedicated speaker, and the amplifier driving that stop has a 'sleep' more which clicks in if no audio signal is detected for approx 15 minutes. The amplifier must have a fault, as this behaviour is supposed to be turned off, but it is still shutting down after about 20 minutes. It does switch back to normal mode when a signal is detected, but this takes a few seconds before any output is produced. I'm working on a fiddle to circumvent this if Thomann can't come up with a solution that doesn't involve shipping the amp back to Germany for repair, which we don't want to agree to. It's two-channel amp, but only one channel is being used. I can configure a dummy stop and windchest to send a note to the other channel, which isn't connected to a loudspeaker. I can then persuade one of the Arduinos in the console to send a note to that stop once a minute and keep the amplifier awake.

Thanks for advice and suggestions!

**Comment by oleg68** [comment]
May be your amplifier has a special setting that disables the standby mode?
