### ISSUE TITLE
GO 3.15.0-1

### ISSUE THREAD

**Issue by Bumblebee001** [GrandOrgue/grandorgue#1967]
Thank you for including the much awaited Tonal balance setting to GO. I hope it proves to be useful as intended raising GrandOrgue to a new level.

May I suggest that the setting is placed just below Gain in the Organ Setting window.

When I uploaded one of my latest sample-sets, I got these three warning/error messages:

![image](https://github.com/user-attachments/assets/7abdaae5-67d5-4993-ae62-f6e11ea5fc39)

What do they mean and what should I do to correct the issue/s?

Mark

**Comment by 25Tim** [comment]
Restart GO or make a new ODF with no header for GO 3.14 and 3.15.
Refresh the cache if the error persists

**Comment by Bumblebee001** [comment]
I had no ";" in the odf. It was created with GOodf.

Reloading GO seems to have done the issue. The messages did not come up again.

Thanks.
Mark
