### ISSUE TITLE
Slow Sampleset Load time

### ISSUE THREAD

**Issue by OrgelSpieler** [GrandOrgue/grandorgue#1983]
For awhile now, when I load a sampleset that is not in cache, it is taking longer than past load times.   For example, I used to be able to load the Freisach Sample set in four to five minutes. Now, it is taking about forty-five minutes loading at a rate of about one note per second.  I have more than adequate memory, a decent processor and running the latest build.  I've run memory tests and chkdsk and everything is fine.  There are no other programs that run on the machine.  Windows defender is disabled.   Does anyone have a clue as to what might be amiss?  I'm stumped.

**Comment by oleg68** [comment]
Might be you have switched the "compress cache" option on? Try to disable it.

**Comment by OrgelSpieler** [comment]
Thanks for the suggestion.  I checked and the cache was not being compressed
What's odd is that this morning, I loaded a different organ not in the cache and it loaded in ninety seconds.  Might there be something unique to the Freisach set that could cause a long load time?  Once loaded, it plays fine.

**Comment by oleg68** [comment]
@OrgelSpieler Is the problem of slow load still present?

**Comment by sstefano75** [comment]
Hello, I have the same problem with the Freisach sampleset. It used to load in a minute now since a couple of months it took about 15 minutes to load. I'm on a Windows 11 PC with an Intel i7 processor and 16GB of RAM. Any suggestion? Many thanks!

**Comment by rousseldenis** [comment]
> Hello, I have the same problem with the Freisach sampleset. It used to load in a minute; now, since a couple of months, it took about 15 minutes to load. I'm on a Windows 11 PC with an Intel i7 processor and 16GB of RAM. Any suggestion? Many thanks!

@sstefano75 If you have ssd or M2 drives, you can try disabling the cache.

**Comment by oleg68** [comment]
> Hello, I have the same problem with the Freisach sampleset. It used to load in a minute; now, since a couple of months, it took about 15 minutes to load. I'm on a Windows 11 PC with an Intel i7 processor and 16GB of RAM. Any suggestion? Many thanks!

1. Do you use cache?
2. Please post here the screenshot of the File->Settings->Options?

**Comment by oleg68** [comment]
It seems you was using this cache before, but when you upgrade GO, the cache sometimes goes to be invalidated.

So try to do File->Update Cache and then try to reload your sampleset. Will it solve your issue?

**Comment by sstefano75** [comment]
Hi, I did an Update Cache and now it loads in less than a minute! Great!
Many thanks

**Comment by oleg68** [comment]
@sstefano75 If you want the cache would be updated automatically every time after GrandOrgue is upgraded next time, you can enable the ``Automatically manage cache`` (``Gestione automatica della cache``).

**Comment by oleg68** [comment]
The reason of the slow loading after upgrade is invalidating of the existing cache and lack of automatic cache management in the File->Options

**Comment by sstefano75** [comment]
Ok, Thank you for the support!
