### ISSUE TITLE
Crash when using -g switch

### ISSUE THREAD

**Issue by willeke1234** [GrandOrgue/grandorgue#2019]
If I run GO with the -g switch (very useful in developing GUI) then GO crashes when I press a key and then press some drawstops. Steps to reproduce:
-Start GO with -g
-Load the demo organ
-Click on a key on the lower manual
-Click on Cornett III
-Click on Flute douce 4'

This is not a bug that regular users will encounter.

macOS Sequoia 15.0
GrandOrgue v3.15.1-1

[Crash.txt.zip](https://github.com/user-attachments/files/17304885/Crash.txt.zip)

**Comment by oleg68** [comment]
The root case is GOReferencePipe becuse it's Initialize() has never been called.
