### ISSUE TITLE
Migrating discussions and issues from oleg68/GrandOrgue

### ISSUE THREAD

**Issue by oleg68** [GrandOrgue/grandorgue#23]
Hi, @larspalo @rousseldenis 

A have some discussion topics and open issues in https://github.com/oleg68/GrandOrgue

I'd like to move them here. Do you agree or disagree?

**Comment by larspalo** [comment]
I don't mind at all, but we might need to review and rethink things as GrandOrgue evolves.

**Comment by oleg68** [comment]
We may do it after they have been moved here

**Comment by oleg68** [comment]
The migration has finished.

The issues are available among others in [https://github.com/GrandOrgue/grandorgue/issues](https://github.com/GrandOrgue/grandorgue/issues)

Discussions have also migrated to https://github.com/GrandOrgue/grandorgue/discussions. Unfortunally, they all have the real posting time, so they are placed before all topics migrated from SourceForge and can be found at the last page of Discussions.
