### ISSUE TITLE
Migrate wiki from sourceforge

### ISSUE THREAD

**Issue by larspalo** [GrandOrgue/grandorgue#24]
GrandOrgue had some documentation also on the wiki pages of Sourceforge. Should we migrate and edit them here?

**Comment by oleg68** [comment]
Where can we place them in Github? Maybe to create some file in the source tree or just to add it to reddme.md?

**Comment by rousseldenis** [comment]
> Where can we place them in Github? Maybe to create some file in the source tree or just to add it to reddme.md?

There is also a wiki here

**Comment by larspalo** [comment]
@oleg68 @rousseldenis I've done a rough migration of the wiki content from SF. There are lots of things to change/update and some pages might better be deleted completely. I can work on it, but I'd like to have your opinions on how the wiki here on GitHub should be. Loads of images doesn't show up here and would need to be uploaded to the pages, but we perhaps should look at the the greater picture first and decide what pages we should have and what content they should have...

**Comment by oleg68** [comment]
@larspalo 

> but I'd like to have your opinions on how the wiki here on GitHub should be.

1. The current pages are OK as the first approach
2. The nearest step must be replacing all links to sourceforge.net with the actual urls on github
3. The next step would be restructuring the pages. It's better to discuss the target structure here
4. Then we may remove some unnecessary pages
5. Then the rest page may be actualised
6. Then to add images
7. The last step is actualising presentations on youtube

>  Loads of images doesn't show up here and would need to be uploaded to the pages, but we perhaps should look at the the greater picture first and decide what pages we should have and what content they should have...

**Comment by larspalo** [comment]
@oleg68 That seems like a good strategy. I'll look over the links to begin with and change where we have equivalents here on GitHub and then we can return to discuss the overall structure.

**Comment by larspalo** [comment]
@oleg68 @rousseldenis I've fixed the links on the home page of the GO wiki here on GitHub and very slightly updated some text. You can track all the changes in the revisions. Shall I go on and continue the link corrections for every page and only where it's obviously needed, also change some text? After that we can return do discuss what should be done structurally to the wiki?

**Comment by oleg68** [comment]
@larspalo Yest, the links in the home page look all right now so you may continue.

**Comment by larspalo** [comment]
@oleg68 @rousseldenis I think I've fixed all links on all the wiki pages. Please check them out and think about what we could remove completely and what otherwise should change.

Personally, I think most of the build related stuff should be removed and we just point to the more up to date [BUILD.md](https://github.com/GrandOrgue/grandorgue/blob/master/BUILD.md) instead.

For [GO performance](https://github.com/GrandOrgue/grandorgue/wiki/GO-Performance) I think that we could instead start a discussion thread in Developers forum where users (once we have fixed perftest) can post data from their setups.

One of the most important pages is almost at the bottom: [Sample Sets](https://github.com/GrandOrgue/grandorgue/wiki/Sample-Sets). This page should be carefully checked, updated and completed with all available sources of samplesets for GO users.

I won't mind if we choose to remove all the detailed pages about my samplesets too.

The [Broken MIDI adapters](https://github.com/GrandOrgue/grandorgue/wiki/Broken-MIDI-Adapters) could perhaps be changed to a page about MIDI equipment tested by GO users and thus contain information about what can be recommended and what to avoid.

**Comment by oleg68** [comment]
> I think I've fixed all links on all the wiki pages. Please check them out and think about what we could remove completely and what otherwise should change.

Now the links look all right.

> Personally, I think most of the build related stuff should be removed and we just point to the more up to date [BUILD.md](https://github.com/GrandOrgue/grandorgue/blob/master/BUILD.md) instead.

Agree.

> For [GO performance](https://github.com/GrandOrgue/grandorgue/wiki/GO-Performance) I think that we could instead start a discussion thread in Developers forum where users (once we have fixed perftest) can post data from their setups.

Agree. I'd also create an issue for including the perftest tool to the GrandOrgue distribution.

> One of the most important pages is almost at the bottom: [Sample Sets](https://github.com/GrandOrgue/grandorgue/wiki/Sample-Sets). This page should be carefully checked, updated and completed with all available sources of samplesets for GO users.
> I won't mind if we choose to remove all the detailed pages about my samplesets too.

I think the list of your samplesets with small screenshots and links to the pages with detail information would be enough.

> The [Broken MIDI adapters](https://github.com/GrandOrgue/grandorgue/wiki/Broken-MIDI-Adapters) could perhaps be changed to a page about MIDI equipment tested by GO users and thus contain information about what can be recommended and what to avoid.

Agree

**Comment by larspalo** [comment]
> I'd also create an issue for including the perftest tool to the GrandOrgue distribution.

That would be great so that users can more easily test the performance of GO on their system in actual numbers.

> I think the list of your samplesets with small screenshots and links to the pages with detail information would be enough.

I think it's enough having my samplesets listed on the [Sample Sets](https://github.com/GrandOrgue/grandorgue/wiki/Sample-Sets) page with links to my webpage. There I can have the detailed information instead. I don't think that kind of information is really necessary here. The [screenshots page](https://github.com/GrandOrgue/grandorgue/wiki/Screenshots) I think we can leave though.

One question is if it's really necessary to make the distinction between the [Sample Sets](https://github.com/GrandOrgue/grandorgue/wiki/Sample-Sets) page and the [Free Sample Sets](https://github.com/GrandOrgue/grandorgue/wiki/Free-Sample-Sets) that anyway is very incomplete? I'm in favor of only keeping the [Sample Sets](https://github.com/GrandOrgue/grandorgue/wiki/Sample-Sets) page.

**Comment by oleg68** [comment]
> I think it's enough having my samplesets listed on the [Sample Sets](https://github.com/GrandOrgue/grandorgue/wiki/Sample-Sets) page with links to my webpage. There I can have the detailed information instead. I don't think that kind of information is really necessary here. The [screenshots page](https://github.com/GrandOrgue/grandorgue/wiki/Screenshots) I think we can leave though.

Agree

> One question is if it's really necessary to make the distinction between the [Sample Sets](https://github.com/GrandOrgue/grandorgue/wiki/Sample-Sets) page and the [Free Sample Sets](https://github.com/GrandOrgue/grandorgue/wiki/Free-Sample-Sets) that anyway is very incomplete? I'm in favor of only keeping the [Sample Sets](https://github.com/GrandOrgue/grandorgue/wiki/Sample-Sets) page.

Agree

**Comment by larspalo** [comment]
Ok! I'll start fixing it then!

**Comment by oleg68** [comment]
@larspalo I see you have made a great job with the wiki pages. Are you going to make more changes? How may I help you?

**Comment by larspalo** [comment]
@oleg68 @rousseldenis Reworking the page about MIDI equipment (now the [Broken MIDI adapters](https://github.com/GrandOrgue/grandorgue/wiki/Broken-MIDI-Adapters)) should involve feedback from the user community. Maybe we could start a discussion thread where users report what they are using for MIDI equipment with GO, and especially what equipment they have had issues with? Then we can update that page with information from the discussion thread.

When reading [Controlling stops with external controls](https://github.com/GrandOrgue/grandorgue/wiki/Controlling-stops-with-external-controls) and [How to get the LED lights working on a Novation Launchpad with GO](https://github.com/GrandOrgue/grandorgue/wiki/How-to-get-the-LED-lights-working-on-Novation-Launchpad-with-GO) I get the impression that they basically describe the same thing. Maybe this information should eventually be coordinated into one page.

However, I think that we by now could consider this issue as basically completed. Now it's just to continously update the wiki with such information that actually is useful for the community of GO users.

**Comment by oleg68** [comment]
> @oleg68 @rousseldenis Reworking the page about MIDI equipment (now the [Broken MIDI adapters](https://github.com/GrandOrgue/grandorgue/wiki/Broken-MIDI-Adapters)) should involve feedback from the user community. Maybe we could start a discussion thread where users report what they are using for MIDI equipment with GO, and especially what equipment they have had issues with? Then we can update that page with information from the discussion thread.

Yes, it would be great.

> When reading [Controlling stops with external controls](https://github.com/GrandOrgue/grandorgue/wiki/Controlling-stops-with-external-controls) and [How to get the LED lights working on a Novation Launchpad with GO](https://github.com/GrandOrgue/grandorgue/wiki/How-to-get-the-LED-lights-working-on-Novation-Launchpad-with-GO) I get the impression that they basically describe the same thing. Maybe this information should eventually be coordinated into one page.
 
Agree. I'd append the information from the second page to the first one and I'd add the title `Example: How to get the LED lights working on Novation Launchpad with GO"

> However, I think that we by now could consider this issue as basically completed. 

Almost it is. But I'd add several remarks:
1. I'd rename the ``GrandOrgue Installations`` page to some other without the word `Installation` because people will click on this page searching for a ``How to install`` doc
2. The last link from this page points to a sourceforge discussion page
3. I'd add the link to the https://github.com/GrandOrgue/grandorgue/blob/master/INSTALL.md to the FAQ.
4. I'd move the link to https://github.com/GrandOrgue/grandorgue/blob/master/BUILD.md from the main page to the FAQ

**Comment by larspalo** [comment]
> Almost it is. But I'd add several remarks:
> 1. I'd rename the GrandOrgue Installations page to some other without the word Installation because people will click on this page searching for a How to install doc
> 2.     The last link from this page points to a sourceforge discussion page
> 3.     I'd add the link to the https://github.com/GrandOrgue/grandorgue/blob/master/INSTALL.md to the FAQ.
> 4.     I'd move the link to https://github.com/GrandOrgue/grandorgue/blob/master/BUILD.md from the main page to the FAQ

@oleg68 
1. Done.
2. Changed link to discussion here on GitHub.
3. It's already there, under point three. But maybe point three and four should be edited together and placed as the top point under a general "Where can I download GrandOrgue"?
4. What if we edit the Home page to have Download GrandOrgue: and the badge first, samplesets after and tutorials as third and remove the link to impulse responses?

I also found some more typos in the [INSTALL.md](https://github.com/GrandOrgue/grandorgue/blob/master/INSTALL.md) that I'll add a PR for.

I'll create a topic in the General discussion forum for gathering information on MIDI equipment from GO users.

**Comment by oleg68** [comment]
> * It's already there, under point three. But maybe point three and four should be edited together and placed as the top point under a general "Where can I download GrandOrgue"?

Now there are two items: ``Where can I download GrandOrgue for Linux?`` and ``Where can I download GrandOrgue for Windows and OS X?`` with almost identical information.

I suggest to 
1. Add the list of OS and architectures GO supports
2. Replace ``Where`` it with one ``Where can I download GrandOrgue``
3. Add ``How can I install GrandOrgue`` with the link to INSTALL.md. Not to mix download and installation.

> * What if we edit the Home page to have Download GrandOrgue: and the badge first, samplesets after and tutorials as third and remove the link to impulse responses?

Agree. But the link to FAQ also should be there.

**Comment by larspalo** [comment]
Ok. I'll do the FAQ points separately for download and installation but similar/combined for all OS types as that's how it works now anyway and link to the correct places.

I'll absolutely keep the FAQ link on the Home page. I was only talking about the content of the first section. I'll do a version!

**Comment by larspalo** [comment]
@rousseldenis @oleg68 What do you think about [the wiki](https://github.com/GrandOrgue/grandorgue/wiki) now? Can we consider this issue as completed? As I see it, the wiki will/should be continously updated anyway, but this is perhaps an acceptable start.

**Comment by oleg68** [comment]
@larspalo Yes, we can. Now wike is ready. I think we may close this issue.

**Comment by larspalo** [comment]
@rousseldenis Do you agree?

**Comment by jason-barba** [comment]
Maybe a side comment in #876 could be considered?

**Comment by larspalo** [comment]
> Maybe a side comment in #876 could be considered?

Well, it seems that no matter how we do some people will miss it anyway... :-) From the [FAQ](https://github.com/GrandOrgue/grandorgue/wiki/FAQ)


    How do I install/upgrade GrandOrgue?

See https://github.com/GrandOrgue/grandorgue/blob/master/INSTALL.md for information on installing/upgrading GrandOrgue.

**Comment by jason-barba** [comment]
I some cases the user is blindfolded and have no luck with search engines. This is the case with this user and occasion. I am sorry, but thanks for the link.

As I understand, upgrade to the latest version is the same modus as installation. Will the old version be overwritten or will the old version and the upgrade be present in parallel? I ask this because I see the final command stated is apt-get install.

**Comment by larspalo** [comment]
No problem. If you upgrade with apt-get install your old version will indeed be overwritten. Same settings files will be used, but beware that the device naming have changed (see #872).

It's possible to test the new version without installing too, in which case you'll still have the old installed version available. Again see [INSTALL.md](https://github.com/GrandOrgue/grandorgue/blob/master/INSTALL.md) for details.

**Comment by larspalo** [comment]
@rousseldenis Do you agree that we close this issue?

**Comment by oleg68** [comment]
@rousseldenis the new release waits for your approval of closing this issue

**Comment by oleg68** [comment]
@rousseldenis may we close this issue?

**Comment by oleg68** [comment]
@larspalo I'd remove the last paragraph from the FAQ: ``There are no GO Packages for my Ubuntu/Debian derived distribution XXXX``.

**Comment by larspalo** [comment]
Done.

**Comment by oleg68** [comment]
@larspalo because all works have been done and @rousseldenis does not answer, let we close this issue.
