### ISSUE TITLE
Change the version numbers

### ISSUE THREAD

**Issue by oleg68** [GrandOrgue/grandorgue#27]
Now GO versions look like 0.3.1.`Svn number`.

After migrating to GitHub we might change tis,

My suggestion is 
- to remove leading `0.` from the version number. GO is mature enough for starting with `0.`
- To increase `1` to `2`.

So to make `3.2.0` after `0.3.1.2342`

**Comment by larspalo** [comment]
Well, for me, the first numbers are mostly cosmetic. GO is certainly mature enough to not be in a beta state, but the development is rather continuous which makes the revision numbering from the current commit used to build the release most interesting, I think. So I'd for instance like the .2518 as the last numbers regardless of what we put before.

**Comment by oleg68** [comment]
@larspalo @rousseldenis After issuing the first official releases we need to continue talking about the new versions format. Any ideas?

**Comment by rousseldenis** [comment]
> @larspalo @rousseldenis After issuing the first official releases we need to continue talking about the new versions format. Any ideas?

As I said, I like the three part format. In any circumstances, I cannot see a case where we need to add a suffix (even for a bug as we can use the patch part).

**Comment by larspalo** [comment]
We could just go to 3.2.commit_number. I realize that most users won't be that interested in the commit number but it gives us immediately an idea where a certain build comes from and what issues might already have been solved since then.

**Comment by rousseldenis** [comment]
> We could just go to 3.2.commit_number. I realize that most users won't be that interested in the commit number but it gives us immediately an idea where a certain build comes from and what issues might already have been solved since then.

A release IMHO should not be 'commit' aware. As release is in fact a tag in git repo, we can find easily the history

**Comment by oleg68** [comment]
> We could just go to 3.2.commit_number. I realize that most users won't be that interested in the commit number but it gives us immediately an idea where a certain build comes from and what issues might already have been solved since then.

1. Usually releases are more rare than commits
2. Svn commit history islinear so it gives sequencial numbers to all commits, but git history is not linear, so this number cannot be assigned automatically

**Comment by larspalo** [comment]
That's where the current 2342 number comes from! And I disagree, it's not immediately obvious from what commit a certain release comes from other than by a cryptic link. The current release for instance only have a commit link that's called https://github.com/GrandOrgue/grandorgue/commit/7b71ce320f59f8532edb7f5335c02f376ae8c098 and even if it's pretty easy to use the Browse files button to inspect the source at that time - you still doesn't easily see any revision number, but that's maybe just how GitHub works... Anyway, what about date then?

**Comment by oleg68** [comment]
> > @larspalo @rousseldenis After issuing the first official releases we need to continue talking about the new versions format. Any ideas?
> 
> As I said, I like the three part format. In any circumstances, I cannot see a case where we need to add a suffix (even for a bug as we can use the patch part). 

The suffix like -1 is necessary according to the standards of linux packaging.

**Comment by rousseldenis** [comment]
> > As I said, I like the three part format. In any circumstances, I cannot see a case where we need to add a suffix (even for a bug as we can use the patch part).
> 
> The suffix like -1 is necessary according to the standards of linux packaging.

So, the linux packaging name can be 0.3-2, no? Following https://refspecs.linuxfoundation.org/LSB_2.1.0/LSB-Core-generic/LSB-Core-generic/pkgnameconv.html

**Comment by larspalo** [comment]
Yes, for a package it's true. But we could have 3.20210916-1 where the 3 is the major GO version and we have a release date and the dash build version that day...

**Comment by rousseldenis** [comment]
> Yes, for a package it's true. But we could have 3.20210916-1 where the 3 is the major GO version and we have a release date and the dash build version that day...

Yes, that's a possibility too.

IMHO, in order to begin on sane bases, I tend to say 'keep it simple'.

But, I'm not so used to linux build processes.

**Comment by oleg68** [comment]
> So, the linux packaging name can be 0.3-2, no?

According to the specs, yes, it can.

This number means `build number`. Usually it is increased when only build scripts or envronment is changed or some pathc is applied *without changing the source code*. So the best suffix is equal to `-1`

But Github builds GO every time someone merged PR. These builds are "intermediate", not releases. So now is used suffixes like 0.`number` for these builds. Everyone can access these builds in https://github.com/GrandOrgue/grandorgue/actions and can download the built artifacts.

So usually we have several intermediate builds between releases.

0.3.1.2342-0.1 - intermediate build N0
0.3.1.2342-0.2 - intermediate build N1
0.3.1.2342-0.3 - intermediate build N2
0.3.1.2342-0.4 - intermediate build N3
0.3.1.2342-1 - release

**Comment by oleg68** [comment]
> That's where the current 2342 number comes from! 

I put this number manually in a git tag. I might put any other number instead of 2342

> Anyway, what about date then?

Using the date is the third component is possible. But I'd made it shorter: 3.2.10916-1 (I hope in 2030 year the first two letters will be greater than 3.2)

**Comment by larspalo** [comment]
And why keep the old relic of 2342, out of nostalgia to Sourceforge? No, keep the build number sensible for what it is - the number of build done - for instance that day. And of course drop the non meaningful revision number.

**Comment by larspalo** [comment]
I also question if the major.minor really is applicable. The development really isn't done in such steps it's much more continuously done, I think the versioning numbers should reflect that. We could of course just bump up the number to 1.date-build since we have a 0.3.1 at the moment. Major versions should really be major differences too, I think. Again, that's not really how GO is developed.

**Comment by oleg68** [comment]
> And why keep the old relic of 2342

I wanted to issue the first official release as soon as possible and to hold this discussion over the first release.

>  for instance that day

The day looks OK, but is too long. I suggest to lave only one figure frm the year number. i. e. 10916 means 2021-09-16

**Comment by larspalo** [comment]
> I suggest to leave only one figure frm the year number. i. e. 10916 means 2021-09-16

Well, what about two year numbers? Then noone would need to bother until 2100, and then I won't be around anymore... ;-)

**Comment by oleg68** [comment]
3 - is a major
2 - is a minor

We will need to increase them after some changes.

IMHO, Migration to github is sufficient to increase the minor version.

**Comment by oleg68** [comment]
> Well, what about two year numbers? Then noone would need to bother until 2100, and then I won't be around anymore... ;-)

It also possible. But I hope that major and minor versions will increase before 2100 and even before 2030.

**Comment by larspalo** [comment]
Usually, such numbering require/involve a set plan of changes to reach the new version. I'd say that the move to GitHub in itself could even warrant a change in major...

**Comment by oleg68** [comment]
Using the date is also useful for resolving #14: we can modify the cmake script to substitute the date automatically unless it is not overridden with -CVERSION parameter

**Comment by larspalo** [comment]
Yes, absolutely. The question then would be the other numbering. Should we keep a major.minor like 3.2.YYMMDD-build pattern?

**Comment by oleg68** [comment]
So, the last approach for the next release is

3.2.210917-1

Some important concern: it will be the date when we start working with the release, not when the release is issued. Otherwise the intermediate build numbers will not correspond the release number.

**Comment by oleg68** [comment]
> Should we keep a major.minor like 3.2.YYMMDD-build pattern?

I think yes.

@rousseldenis What do you think it on?

**Comment by larspalo** [comment]
I think that intermediate builds, if we at all should have such, should follow the same pattern and increase the date portion and build number for that day. Then we tag what we think is the final "release" for stable production use as opposed to a kind of "daily builds". Am I optimistic?

**Comment by oleg68** [comment]
Intermediate build is a synonym of pre-release so it's number should be close to the release number.

So the following seq looks nice:

3.2.210917-0.1  the first intermediate build
3.2.210917-0.2  the second intermediate build
3.2.210917-1  the release

It is highly not desired to change the third component between intermediate builds.

**Comment by oleg68** [comment]
> that intermediate builds, if we at all should have such,

They are very useful for testing before release

**Comment by larspalo** [comment]
Isn't it possible to just mark a release (or tag it) and let the intermediate builds be like "daily builds" for testing? The thing about the build number is that I'd like to keep it as an Int to really represent the number of builds that day, that does in fact make more sense to me.

**Comment by oleg68** [comment]
> Isn't it possible to just mark a release (or tag it) and let the intermediate builds be like "daily builds" for testing?

It is good when intermediate builds have similar version numbers as the release they belong to

**Comment by oleg68** [comment]
There is another thing related to the release number.

The good practice is to plan future releases, group and assign issues to them, label them with the release number. So it is highy desirable to know the release version number in advance, before it is actually issued.

**Comment by oleg68** [comment]
Seems everything agree that the major should be 3 and the minor should be 2. Now we sjould choose the third component of the version.

Summarising the ideas told here, we have three options:

- To continue from the Sourceforge number, ie the next release will be 3.2.2343–1
- To reset this number to 0. The next release will be 3.2.0–1
- To ise YYMMDD. The next release will be like 3.2.210918-1

@larspalo @rousseldenis @nickappleton please vote for one of them.

**Comment by larspalo** [comment]
I think that the YYMMDD third part is best. However, I'm still doubtful about the release plan builds and any "pre-releases" as you suggested. I think that such detailed planning is not really suitable to the development of GO that is rather random and un-structured in it's nature.

I'd like to see the automatic builds as "daily builds" or like testing snapshots without any 0.1-0.9 suffixes to a future release with a date that's back in time (a very confusing way of thinking about the release, in my opinion). When we think it's time to make an actual release we just mark that build as a stable.

**Comment by oleg68** [comment]
@larspalo automatic builds are not daily builds. They are triggered every time on merge anything to master. If more than 1 merge occures during a day then YYMMDD will not be sufficient.

Moreover these builds are available in every fork: it is good to get the build and to test it after any changes commited to the own fork before making a PR. Build numbers YYMMDD may confuse across the fork and the main repo.

**Comment by larspalo** [comment]
@oleg68 I don't mind adding the -build_number. What I don't like is the 0.1 build numbering, especially up to a release of 1 that's dated in the past! And yes, they are not daily builds - more like build snapshots. I suggest we use 3.2.YYMMDD-build_number (of the day, and increment it as int for every additional build that day)

**Comment by oleg68** [comment]
@larspalo leading zero is the standard way for marking prereleases. It would is understandably by all.

If you don't like having a date in the past in the version number, I can suggest several options not breaking the prerelease numbering logic:

- using the starting date for all preleleases and the actual issuing date for the final release
- using an increasing integer number instead of the date: 2343
- use the previous release number as the base for all following prereleases. In this case after 3.2.210925-1 will be 3.2.211025-1.1, -1.2 and so on

**Comment by larspalo** [comment]
I think it will be good enough to let the prereleases (or build snapshots of the repository) have a build number starting with 0.x to separate them from actual releases with a -1, if that's so important to you. However, I think that the date portion should always relate to the date when they are created.

If we think about it - from one release to another we might have quite a few different changes coming from different forks/branches completely oblivious to whatever changes might have happened in other forks/branches at different times. To force them into a "release plan" (that doesn't even exist) by having it look like they actually build upon each other in an orderly fashion is just ridiculous in my opinion.

Thus, I suggest that the next pre-release should be having a version number of 3.2.YYMMDD-0.1. If any more builds happen the same day they get -0.2 up to something that's still < 1. If a pre-release happen the next day then the date portion changes to current date and the build numbering resets to 0.1. It will still be obvious if you look at the series what the progression of the builds are. For instance:

3.2.210918-0.1
3.2.210919-0.1
3.2.210919-0.2
3.2.210920-0.1
3.2.210921-1

What we gain by this is a clear timeline of releases and pre-releases that doesn't pretend that completely unrelated commits have anything in common except leading up to the next actual release that's clearly differentiated from any pre-release. If any new pre-release would happen on a release day then it could have a fraction added to indicate that. If for some reason we need another real release the same day we increment the integer number to 2 etc. Would this an acceptable compromise?

**Comment by oleg68** [comment]
Now it is not feasible with the current build scripts. For making a version  3.2.210919-0.1 they require that the tag `3.2.210919-0` would already exist in the repository.

All my suggestions do not require any build script modifications. So let start with
- 3.2.210918-0.1
- 3.2.210918-0.2
- 3.2.210918-0.3
- 3.2.210921-1

and then create a separate issue about for the third number automation.

@rousseldenis what do you think about using the date as a third component? Or using an integer is better?

**Comment by oleg68** [comment]
@larspalo I've tried to build version 3.2.210920-0 and received an error while building for OSx: 
[ld: malformed 64-bit a.b.c.d.e version number: 3.2.210920](https://github.com/GrandOrgue/grandorgue/runs/3654408484?check_suite_focus=true)

We are not ready to such long version numbers from technical point of view.

I suggest to return to short numbers: 3.2.0 or 3.2.2343

**Comment by rousseldenis** [comment]
> @larspalo I've tried to build version 3.2.210920-0 and received an error while building for OSx:
> [ld: malformed 64-bit a.b.c.d.e version number: 3.2.210920](https://github.com/GrandOrgue/grandorgue/runs/3654408484?check_suite_focus=true)
> 
> We are not ready to such long version numbers from technical point of view.
> 
> I suggest to return to short numbers: 3.2.0 or 3.2.2343

Seems that versions must obey max values for OSX (<65536.<255.<255)

**Comment by larspalo** [comment]
Ok, so that's very convenient... Then we might just as well simplify more.

I think we should drop the 2343 svn revision number at any rate. Also I think we should establish some set rules as to when it's appropriate to change major and minor numbers - like for instance when any new feature is added the minor version is bumped up. With any major changes in the ODF format - for instance when we changed to the new panel layout as recommended default, or the new organ packaging format - the major version could be bumped up (both of these things has of course already happened).

I have another suggestion for the build numbering then. We could just start from the release build 1 that's already done on GitHub and every time we make a new "actual" release we just bump up that number to next integer. Then any pre releases just increment the fraction as you like to have it - but staying on the old actual release build version until a real release is issued!

If we only make bug fixes, build changes, documentation corrections, rearranges the dialogs or menu items without any actual new features, then we only change the build number.

So, to celebrate GOs successful move to GitHub and all feature additions/changes from Oleg we could then release next version as 3.2-2, next pre release as 3.2-2.1 leading up to either a 3.2-3 or a 3.3-3 depending on what's done to it. What do you think about that? (major.minor-incremented_build_number)

**Comment by oleg68** [comment]
@larspalo Why not to call releases 3.2.0-1, 3.2.1-1, 3.2.2-1, 3.2.3-1 and so on? `-1` is the default build number for releases. It is not a standard way to put the actual version to the build number.

**Comment by oleg68** [comment]
@larspalo I like the idea of major.minor.incremental_release_number_on_GitHub. (not build number, but release number) Now we reset it to 0 and we increment it every release. Is it OK?

**Comment by oleg68** [comment]
@larspalo Displaying the package number was added in https://github.com/oleg68/GrandOrgue/pull/62

We may revert this change. But I found sufficient convinient to see the packaging number when users send screenshots in bug reports from intermediate versions.

Now technically is not feasible to increment the version number on automatic builds. It requires putting a tag manually.

Issuing a release is quite rare and is intended to be manual steps (including approval), so putting a new tag on each release is acceptable. But it is not acceptable for automatic builds on commits.

**Comment by larspalo** [comment]
Actually, l question if all commits really should have a build. Many changes, especially now to begin with, will be fairly invisible to end-users.

But that aside, the major.minor.incremental_release_on_GitHub is a good starting point, I think. If you really want to have the "dash numbering" appendix then that's going to function more as a build type identifier than a package numbering anyway.

**Comment by rousseldenis** [comment]
> Actually, l question if all commits really should have a build. Many changes, especially now to begin with, will be fairly invisible to end-users.

That's the point. We can have infinite amount of builds during development normal users don't care about. The important ones are releases ones.

**Comment by larspalo** [comment]
Also, if we start thinking of the -0.1 up to -1 as build_type_identifier then Olegs first suggestion of bumping up the release_number immediately after a -1 is reached starts to make sense. We just have to realize that it could very well be that the minor (or perhaps major sometime in the future) need to be adjusted at time of the release even though the pre-release version might not suggest it.

**Comment by larspalo** [comment]
The incremental_release_on_GitHub is of course predictable. But if new features also gets included into the final new release then the minor version should be bumped up too. Then at least we won't risk having the nightmare scenario that Oleg imagined of still having the same versioning numbering in 2030...

**Comment by oleg68** [comment]
> Actually, l question if all commits really should have a build.

If you are talking about the main repository, there is no any commits except merging pull requests. And indeed, each merge of PR triggers a build.

If you are talking about forks, there any commit triggers a build. It is a good practice to see the build status and to test built GO before making the PR.

**Comment by oleg68** [comment]
> But if new features also gets included into the final new release then the minor version should be bumped up too. 

1. I hope we will plan releases as I've already started in #715 
2. If we decide to add more features after, then no problems: we just switch to the new version:

3.2.57-0.1
3.2.57-0.2
3.3.57-0.1 (or 3.3.0-0.1)
3.3.57-1 (or 3.3.0-1)

**Comment by oleg68** [comment]
A separate question: should we reset the github_release_number to 0 after incrementing a major or a minor version?

**Comment by rousseldenis** [comment]
> A separate question: should we reset the github_release_number to 0 after incrementing a major or a minor version?

I tend to say yes (I practice that flow on my day to day work)

**Comment by larspalo** [comment]
> If you are talking about forks, there any commit triggers a build. It is a good practice to see the build status and to test built GO before making the PR.

Right, so even in different branches there will be builds for every commit, or is that happening only on master? (talking about the forks, not main repository)

So, we more or less have reached an agreement? I think we can reset build number if any of the version numbers change. Maybe any lower numbers really should be reset if a higher is changed? I personally don't think it's a problem if we have a pre-release that seems to target only next release but it in fact later turns out to target next minor version.

**Comment by oleg68** [comment]
> Right, so even in different branches there will be builds for every commit, or is that happening only on master? (talking about the forks, not main repository)

Yes, in all branches. But these builds will appear only in the fork, not in the master.

**Comment by oleg68** [comment]
> Maybe any lower numbers really should be reset if a higher is changed?

I like such practice.

**Comment by oleg68** [comment]
> Right, so even in different branches there will be builds for every commit, or is that happening only on master? (talking about the forks, not main repository)

I have to modify my previous answer.

By default github does not run builds in forks. For running them you have to go to the Action page of repo and enable actions on it

Usually you make commits locally in a temporary branch and then push this branch to Github. One push may contain several commits. The build is triggered not for every commit, but once for the push in your fork. Later you may add more commits to your branch and push again. Then the next build will occur.

**Comment by oleg68** [comment]
@larspalo 

> So, we more or less have reached an agreement? I think we can reset build number if any of the version numbers change. 

`3.2.0`?

**Comment by rousseldenis** [comment]
> @larspalo
> 
> > So, we more or less have reached an agreement?
> 
> `3.2.0`?

For me, that's the best!

**Comment by larspalo** [comment]
Yes, lets go on with that.

**Comment by oleg68** [comment]
3.2.0
