### ISSUE TITLE
Merging changes from https://github.com/oleg68/GrandOrgue

### ISSUE THREAD

**Issue by oleg68** [GrandOrgue/grandorgue#4]
The discussion was already started in https://sourceforge.net/p/ourorgan/discussion/962124/thread/980e53e5f4/?limit=25&page=3#fa69/6bd9/c233 and then was continued in https://github.com/GrandOrgue/grandorgue/pull/2#issuecomment-913387050

I think it's better to start a separate thread for discussing the process of merging.

We have several options, each of them have their advantages and disadvantages.

1. Merge all changes without code review
2. Merge all changes after some small amount of code review but without lots of modifying
3. Merge all changes with exact code review in the same order as they were in the fork
4. Merge only some of changes. It is quite easy to merge small changes but it is difficult to extract large changes with a lot of related commits
    1. Minimal approach. If there are two changes A and B; B works only with A. We want to merge B but don't want to merge A, then we modify B and A before merge that to get the maximum from B and the minimum from A.
    2. Maximal approach. If there are two changes A and B; B works only with A. We want to merge B than we also take A. It can recursivelly require additions of other changes, so the PR becomes very large.
        Some example of this approach is #2
5. Not to merge any changes at all

**Comment by rousseldenis** [comment]
> The discussion was already started in https://sourceforge.net/p/ourorgan/discussion/962124/thread/980e53e5f4/?limit=25&page=3#fa69/6bd9/c233 and then was continued in [#2 (comment)](https://github.com/GrandOrgue/grandorgue/pull/2#issuecomment-913387050)
> 
> I think it's better to start a separate thread for discussing the process of merging.
> 
> We have several options, each of them have their advantages and disadvantages.
> 
> 1. Merge all changes without code review
> 2. Merge all changes after some small amount of code review but without lots of modifying
> 3. Merge all changes with exact code review in the same order as they were in the fork
> 4. Merge only some of changes. It is quite easy to merge small changes but it is difficult to extract large changes with a lot of related commits
>    
>    1. Minimal approach. If there are two changes A and B; B works only with A. We want to merge B but don't want to merge A, then we modify B and A before merge that to get the maximum from B and the minimum from A.
>    2. Maximal approach. If there are two changes A and B; B works only with A. We want to merge B than we also take A. It can recursivelly require additions of other changes, so the PR becomes very large.
>       Some example of this approach is [[IMP] Add build scripts #2](https://github.com/GrandOrgue/grandorgue/pull/2)
> 5. Not to merge any changes at all

I'm in favor of getting the fork state as is to grandorgue/master. I've tested the software and, for me, it's very good, so functional review for my part. +1

**Comment by oleg68** [comment]
@larspalo 

> I also think that the submodule approach might be extended to include
portaudio too

I wanted to make this, but the old Portaudio works fine with ASIO when the new  RTAudui has [an issue with ASIO](https://github.com/oleg68/GrandOrgue/issues/57). So I planned to switch PortAudio after fix RtAudio otherwise users may lose the only capability of using ASIO.

> By the way, are you using Netbeans as IDE? As I understood it at least JLD
was interested in having the assistance from an IDE to help development.

Yes, of cause. I use netbeans. It is [a freeware opensource IDE](http://netbeans.apache.org/) and it allows to modify the code, to build GrandOrgue and to debug it. It would be quite difficult to work with the code without IDE.

Other people prefer another IDEs. It is a discussion question are we to place IDE projects files to the source tree.

**Comment by oleg68** [comment]
The discussion questions about some my changes:

1. Placing IDE project files to the source tree (now it is has already added for Netbeans. Maybe to add ones for other IDEs too) 
2. The new GrandOrgue application icon https://github.com/oleg68/GrandOrgue/issues/20
3. Enabling ASIO support by default in the GitHub builds https://github.com/oleg68/GrandOrgue/issues/8

Maybe there are another non-evident changes that I missed.

**Comment by larspalo** [comment]
1. I just saw some netbeans artifacts in the code tree so I assumed so. I don't think we need to purge that but eventually, if more IDEs are used, we need to organize it well and perhaps have some instructions written on how to use them.

2. The new approach of creating the icon from a .svg image at build time is perfectly ok for me and I doubt that any other developer will complain. However, I personally think that the photorealistic image is screaming too much piano for my taste. But changing that with something else more organlike might be a good thing for the community to work on.

3. Already the mentioned indication that ASIO creates issues is a very good reason not to release or support any builds with it, I think - not only the murky legal aspect. If someone wants to build with ASIO then they need to do it themselves and take responsibility for the issues caused by it too. I wouldn't recommend that we keep building with ASIO support.

**Comment by rousseldenis** [comment]
1. I doubt about placing IDEs configuration files in project. IMHO, each person has its own configuration that may differ from that. I'm more used to add some .gitignore configuration to exclude projects configuration (for the reasons I said before).
2. I've tested the oleg build and I'm pleased by the more realistic picture. Maybe creating a new one with reverse colors or black/brown.
3. It's allowed until agreement is signed: https://www.steinberg.net/developers/ IMHO, such things, if we do it, has to be done as the community association and not as individual.

**Comment by oleg68** [comment]
More questions to discuss:
4. Github Build and removing the files for old building systems
6. README file refactory (and using .md file formats)
7. CHANGELOG.md

**Comment by rousseldenis** [comment]
4. That's a good point to avoid maintaining unused versions. Some users may be unhappy for those having old hardware and don't want to upgrade.
5. I can do it (I've already done a PR to improve a little), but I can go forward.
6. For my experience, the changelog should be updated automatically after a release as it sometimes a burden to update it. Maybe, if we are as many as we can share tasks before releasing.

For all those things, we can create a new issue or using the first I did and create tasks (github flavor) like :

- [ ] First task
- [x] Second task
- [ ] ...

**Comment by larspalo** [comment]
The old OBS related files should of course be removed as they no longer have any purpose.
README and BUILD instructions need to be updated, no question there, and yes we should probably best have an issue/task list for at least future changes. For getting the repository to a working state I agree it might be best to archive the current svn state in a branch and then import Olegs as a new master. Then perhaps we can work on necessary issues/tasks for it. Like removing ASIO build releases, move portaudio to a submodule, fix suitable headers for some of the newer files etc.

**Comment by rousseldenis** [comment]
> For getting the repository to a working state I agree it might be best to archive the current svn state in a branch and then import Olegs as a new master.

Ok, so we agree. Let's go on that point (easy one :smiley: )

**Comment by rousseldenis** [comment]
> > For getting the repository to a working state I agree it might be best to archive the current svn state in a branch and then import Olegs as a new master.
> 
> Ok, so we agree. Let's go on that point (easy one  )

Done. New playground @oleg68 !

**Comment by oleg68** [comment]
Thanks, @rousseldenis 

I pushed the tag `0.3.1.2342-0` in the repository. It triggers the first intermediate build of 0.3.1.2342 that is the same as  0.3.1.2341-15.os.

All another commits witout a tag will trigger intermediate builds `0.3.1.2342-0.1`,  `0.3.1.2342-0.2` and so on.

Now we have to define the first issues for the 0.3.1.2342 release. When we complete these issues, we will push the tag `0.3.1.2342-1` that will trigger building a release version `0.3.1.2342-1`.

**Comment by rousseldenis** [comment]
@oleg68 by the way, build is red (on tag)

**Comment by oleg68** [comment]
Something went wrong. I'm discovering it.

**Comment by oleg68** [comment]
The problem was in the build for windows:

zypper has terminated on downloading 8 packages from 25 without any error. 

Retrieving package mingw64-libwx_mswu_core_suse1-3.0.2-12.983.noarch (8/25)

So wxWidget has not been installed that caused dependency check failure on cmake.

It is better to fail the build on the `Install dependencies` phase, not on the `cmake` one.

Running zypper on ubuntu is not safe. Sometimes it breaks.

I've just restarted the same build and the build finished successfully

It is not good that we ignore zypper errors #5

**Comment by oleg68** [comment]
May I push the tags from my repository here,

**Comment by rousseldenis** [comment]
> @larspalo @rousseldenis May I push the tags from my repository here?

You have the ownership, so yes!

I have protected master branch with some common rule as two reviews for a merge. But we can evolve with this

**Comment by oleg68** [comment]
@rousseldenis Github doesn't support pull requests on tagging. So the only way is to push them directly from my repo

**Comment by oleg68** [comment]
@larspalo Do you agree with pushing tags from my repo here?

**Comment by rousseldenis** [comment]
> @rousseldenis Github doesn't support pull requests on tagging. So the only way is to push them directly from my repo. And I ask for approving in comments.

Yes. That's not an issue for me. Maybe we need to keep your tag format or not. But for now it's ok for me.

**Comment by larspalo** [comment]
No problem for me. I'm still learning about Github...

**Comment by oleg68** [comment]
I've pushed my tags here.

Merge completed.
