### ISSUE TITLE
[Bug] Build for Windows fails on cmake phase due wxwidgets is not installed

### ISSUE THREAD

**Issue by oleg68** [GrandOrgue/grandorgue#5]
Now we use zypper for installing some packages for cross compiling from http://download.opensuse.org/repositories/home:e9925248:mingw/openSUSE_Tumbleweed/home:e9925248:mingw.repo

Sometimes zypper fails and the `prepare-ubuntu-20.sh` ignores this error. It causes a dependency failure on the `cmake` phase that makes troubleshooting more complex.

It is better not to ignore this error and to fail on the `Install Dependencies` phase

**Comment by rousseldenis** [comment]
> It is better not to ignore this error and fail on the `Install Dependencies` phase

Indeed. If we can skip some builds

**Comment by oleg68** [comment]
@rousseldenis  @larspalo  let's check the PR and Code Review technologis on example of a small change. After my own build finishes I'l create a PR and I'll invite you as reviewers.

**Comment by oleg68** [comment]
@rousseldenis I've pushed the fix to oleg68/GrandOrgue, but I cann't find a way to create a pull request from oleg68/GrandOrgue to GrandOrgue/grandorgue because my repo is not a fork. Maybe you know how to do it?

**Comment by larspalo** [comment]
It's a bit of walking around in a circle... I think you'll have to actually
fork the "official" GO repository to yourself, even though the master
branch in the "official" repository in it's current state is (was) a clone
of your repository!

Den mån 6 sep. 2021 kl 20:40 skrev Oleg Samarin ***@***.***>:

**Comment by oleg68** [comment]
@larspalo Yes, I've created a true fork .

I wouldn't like to delete my first fork because there are some discussions and issues that I'd like to keep.

**Comment by larspalo** [comment]
Of course, I can understand that. I'm still working on understanding how to import the exported forums from Sourceforge. I've also tested making a manual build on Linux from a git clone of the official repository and it works as expected. There will be some changes necessary to the README et al, but I think that I'll have to go to bed now... More work later!
