### ISSUE TITLE
Provide wxwidgets-mingw-w64 ubuntu package

### ISSUE THREAD

**Issue by oleg68** [GrandOrgue/grandorgue#683]
For getting rid of zypper #28 it is to have wxwidgets-mingw-w64 ubuntu package for cross-compiling grandorgue for windows.

**Comment by oleg68** [comment]
I've tried to build wxwidgets for windows on ubuntu, but couldn't find any analogs of opensuse packages: mingw64-filesystem mingw64-libexpat-devel mingw64-libjpeg-devel mingw64-libpng-devel mingw64-libtiff-devel

@larspalo You said that you had cross-compiled wxWidgets for windows. Where did you get these dependencies?

**Comment by larspalo** [comment]
I have cross compiled wx many times, even the latest release yesterday, though I had to manually add the bin folder to get make install to work. With the stable 3.0.5 I didn't have that issue.

However, I've failed to get things to work with the old instructions available for cross compiling GO to windows from Linux - even before getting any issues with wx. Most of these dependencies you mention should be built together with the wx build if I remember correctly. Unfortunately this time I got stuck after I cross compiled fftw and failed to get pkg-config to recognize it even if I had added it in the toolchain.def. We seriously need to update the build instructions, I think.

**Comment by oleg68** [comment]
> We seriously need to update the build instructions, I think.

My aproach - not to include building wx to the guide on building GO, but to provide a precompiled .deb packages with wx.

**Comment by larspalo** [comment]
> My aproach - not to include building wx to the guide on building GO, but to provide a precompiled .deb packages with wx.

That's perfect for the automated builds and as a quick option. But it's not an option for someone like me who wants to be able to do everything manually to understand it! So, by all means create the packages - but document everything, each and every step on the way as good as you can!

**Comment by larspalo** [comment]
For the dependencies mentioned earlier - I have a vague memory of options like that for the .configure.

**Comment by oleg68** [comment]
I'm trying to build wx without the dependencies mentioned above. I received some warnings:

```
configure: WARNING: zlib library not found or too old, will use built-in instead
checking for png.h > 0.90... 
checking for png.h... no
configure: WARNING: system png library not found or too old, will use built-in instead
checking for jpeglib.h... no
configure: WARNING: system jpeg library not found, will use built-in instead
checking for tiffio.h... no
configure: WARNING: system tiff library not found, will use built-in instead
checking for lzma_code in -llzma... no
checking for jbg_dec_init in -ljbig... no
checking for expat.h... no
configure: WARNING: system expat library not found, will use built-in instead
```

The compilation now is in progress. Maybe it will work without all dependencies.

**Comment by larspalo** [comment]
Yes, it should work with the builtin packages. It should be possible to specify to ./configure the options of --disable-shared --enable-unicode --with-expat=builtin --with-zlib=builtin --with-libjpeg=builtin --with-libtiff=builtin -with-libpng=builtin. But I think it will sort itself out.

**Comment by oleg68** [comment]
@larspalo I managed to create a singleton .deb package with the whole wxWidgets for windows.

But Martin Koegler built multiple small .rpm packages. Do we need the same with .deb, or the singleton is OK?

**Comment by larspalo** [comment]
I think it's perfectly ok with a single package. If the build size jumps extremely much we could perhaps re-consider, but otherwise it's just easier to manage.

**Comment by oleg68** [comment]
@larspalo 
>  though I had to manually add the bin folder to get make install to work. With the stable 3.0.5 I didn't have that issue

Yes, I had the same issue: https://github.com/oleg68/WxWidgetsCross/commit/c26c859a8f103a48377634e42c2f91c823fd58fe

**Comment by oleg68** [comment]
wxWirget package is available here: https://github.com/GrandOrgue/WxWidgetsCross/releases

There are 3 versions:

- 3.0.2 - the same as now
- 3.0.5.1 - the last release from 3.0 branch
- 3.1.5 - the last release

When we try to build GO/windows against .deb we will choose among them
