### ISSUE TITLE
[Feature request] AppImage target

### ISSUE THREAD

**Issue by lbssousa** [GrandOrgue/grandorgue#698]
It would be helpful if you could include some scripts to enable deploying of AppImage bundles as well as DEB/RPM packages.

I already have a recipe for building AppImage for GrandOrgue in my forked OBS repository: https://build.opensuse.org/package/view_file/home:lbssousa:grandorgue/grandorgue/appimage.yml?expand=1 , but I'm still having problems with JACK support. Maybe I should build GrandOrgue AppImage without JACK support.

This Github action can be handful: https://github.com/marketplace/actions/build-appimage

**Comment by larspalo** [comment]
@oleg68 I've spent some time reading the appimage documentation and successfully built an appimage locally without too much trouble. So far it has worked where I've tested it, but I'll test it on some completely clean computers too just to verify. Next step after testing would be to create the build script and modify the build.yml for an appimage target, right? Of course in a separate branch on my fork at first...

**Comment by oleg68** [comment]
> Next step after testing would be to create the build script and modify the build.yml for an appimage target

Yes, it would.

You need a subdirectory build-scripts/for-appimage with two scripts `prepare-ubuntu.sh` for installing dependencies and ``build-on-linux.sh` for building appimage. Then they should be included to build.yml in the same way as other build scripts.

The built appimage filenames must start with `grandorgue` and include the full version number.

**Comment by larspalo** [comment]
For 1. will the needed appImages be available at something like ../../linuxdeploy-x86_64.AppImage then?

For 2. I have the gtk warning

```
Gtk-WARNING **: 21:04:31.211: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
```

but the app runs fine except for some problems with the rendering of + and - in the spin controls. Maybe one could test adding the linuxdeploy-plugin-gtk plugin and see if that helps...

**Comment by oleg68** [comment]
> For 1. will the needed appImages be available at something like ../../linuxdeploy-x86_64.AppImage then?

I'd install them to `/usr/local/bin`

> but the app runs fine

I've made more testing.

It works out of box on ubuntu18 and debian9.

It doesn't work on Fedora 34 and on OpenSuse with the error above.

It doesn't work on OracleLinux 8.4 with the error:

```
[admin@ol84 ~]$ ./grandorgue-3.3.1-0.1-x86_64.AppImage 
./grandorgue-3.3.1-0.1-x86_64.AppImage: error while loading shared libraries: libjack.so.0: cannot open shared object file: No such file or directory
```

**Comment by larspalo** [comment]
> I'd install them to `/usr/local/bin`. They would appear in the PATH

I can just chmod them and then mv them there then, right?

The pixbuf error should be taken care of with the linuxdeploy-plugin-gtk.

It seems that linuxdeploy doesn't include the jack library, it must be present on the system. If it's indeed not present in many Linux distros then we might need to include it in the appimage manually.

**Comment by lbssousa** [comment]
>```
> [admin@ol84 ~]$ ./grandorgue-3.3.1-0.1-x86_64.AppImage 
> ./grandorgue-3.3.1-0.1-x86_64.AppImage: error while loading shared libraries: libjack.so.0: cannot open shared object file: No such file or directory
> ```
AppImages don't bundle libjack by design. It should be already installed in host system.

**Comment by larspalo** [comment]
> AppImages don't bundle libjack by design. It should be previously installed in host system.

Yes, but we can bundle it manually if needed.

**Comment by oleg68** [comment]
> AppImages don't bundle libjack by design. It should be previously installed in host system. 
> 
> 

It contradicts the basic idea of appimage: run the program without installing anything

**Comment by oleg68** [comment]
> > I'd install them to `/usr/local/bin`. They would appear in the PATH
> 
> I can just chmod them and then mv them there then, right?

sudo wget -P /usr/local/bin
sudo chmod +x

**Comment by lbssousa** [comment]
> It contradicts the basic idea of appimage: run the program without installing anything

It seems some libs don't work well when bundled in AppImages. Here's the Full list: 
https://github.com/AppImage/pkg2appimage/blob/master/excludelist

**Comment by larspalo** [comment]
I've updated the [branch on my fork](https://github.com/larspalo/grandorgue/tree/issue698) with the suggestions above and the manual inclusion of libjack. The appimage from GitHub run here, even though I get a

`Gtk-Message: 07:24:15.978: Failed to load module "canberra-gtk-module"`

and a few other notes like

```
/usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so: undefined symbol: g_mount_operation_get_is_tcrypt_system_volume
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so: undefined symbol: g_mount_operation_get_is_tcrypt_system_volume
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
```

so far the appimage works just fine and looks ok with the spinctrls. Of course I get the usual complaints about jack server not running but that's nothing special to the appimage. I'm thankful for additional testing, feedback and suggestions.

**Comment by oleg68** [comment]
> It seems some libs don't work well when bundled in AppImages.

I'd use the same approach as for MacOs .dmg image: libjack is included to the image. GrandOrgue can be launched and can work with core subsystems without error that libjack is missing.

But if the user wants to use jack, he have to download and install Jack Audio Server and to start it manually. Then he became able to switch GrandOrgue to jack.

If it was feasible to implement the same approach with appimage, it would be great.

**Comment by larspalo** [comment]
Actually, with the current inclusion of libjack, I cannot use jack with the GitHub appimage build! In a local appimage build without libjack manually included that's not happening and I can switch to jack just fine.

**Comment by larspalo** [comment]
Ok, but the build won't work unless the bug is fixed so if I don't include it in this branch the appimage build will fail.

**Comment by oleg68** [comment]
@rousseldenis 

You have already approved several upcomming PRs but not #766.

Do you oppose building appimage target at all? Or you have another plans?
