### ISSUE TITLE
Audio midi tab W10 crashes GO

### ISSUE THREAD

**Issue by mattrixed** [GrandOrgue/grandorgue#699]
On windows 10 when you click audio midi it crashes the program when you have a usb audio interface connected.  Since version 4?  The way around it turn off usb device.  click on audio midi make change save, ok error audio device not found.  close go turn on device and startup up go again and load sampleset..... !!! argh!

thanks for you hard work.

W10 latest 
focusrite 18i20 2nd gen

**Comment by oleg68** [comment]
Seems it has already been fixed. Feel free of opening the next issue if [the last release](https://github.com/GrandOrgue/grandorgue/releases/tag/0.3.1.2342-1) still crashes.
