### ISSUE TITLE
Software update

### ISSUE THREAD

**Issue by oleg68** [GrandOrgue/grandorgue#704]
### Discussed in https://github.com/oleg68/GrandOrgue/discussions/51

<div type='discussions-op-text'>

<sup>Originally posted by **Jean-Gabriel1982** August  5, 2021</sup>
Would it be possible to implement a software update module, in GrandOrgue, rather than checking each time for possible updates on Github?</div>

**Comment by rousseldenis** [comment]
> It is too difficult to implement a real software updater (it would required the administrator privileges that ordinar users running GO do not have). But we can implement a optional checking for update with displaying a message that the new release exist.
> 
> This should be switchable on/off in the settings

One thing we could do is publish apt packages. So, the automatic updates can come.

**Comment by oleg68** [comment]
@rousseldenis Yes, publishing repositories for different linux distributions (like Martin did on OBS) would help to update. But this solution is applicable only for linux.

There are lots of users with windows and OSx that also want to receive notifications about the new releases.

So I this issue is about checking for the new release for all platforms.

Making OBS repositories is a subject of a separate issue.

**Comment by rousseldenis** [comment]
> @rousseldenis Yes, publishing repositories for different linux distributions (like Martin did on OBS) would help to update. But this solution is applicable only for linux.
> 
> There are lots of users with windows and OSx that also want to receive notifications about the new releases.
> 
> So I this issue is about checking for the new release for all platforms.
> 
> Making OBS repositories is a subject of a separate issue.

Yes, such feature for windows for instance needs something like a static url to check for new versions and popup user if exists.
