### ISSUE TITLE
Audio output : no sound 

### ISSUE THREAD

**Issue by Jean-Gabriel1982** [GrandOrgue/grandorgue#706]
To day I tried to connect an organ (basic one) with my MacMini, but impossible to have any external sound, except internal Mac's speakers.
I had no sound on headphones or speakers by plugging into the headphone jack.

I have this error message :
> Output interface Pa: Core Audio: External headphones: not found - no sound will be produced

**Comment by oleg68** [comment]
Fixed with #706
