### ISSUE TITLE
[Bug] Panel menu is too narrow

### ISSUE THREAD

**Issue by oleg68** [GrandOrgue/grandorgue#712]
When opening a Panel menu for the first time, the menu rectangle is narrow; the pannel names do not fit to it

**Comment by rousseldenis** [comment]
Indeed, +1

**Comment by larspalo** [comment]
Actually, I think it's not really populated until an organ is opened/loaded.

**Comment by larspalo** [comment]
But yes, even after an organ is opened/loaded the first opening of the Panel menu is too narrow the first time so it's a bug.

**Comment by Jean-Gabriel1982** [comment]
+1

**Comment by oleg68** [comment]
The reason of this bug is that GOrgueFrame::UpdatePanelMenu, that populates this menu, is called a response to wxEVT_MENU_OPEN event. But the size of menu is defined before wxEVT_MENU_OPEN.

The solution may be to populate PanelMenu in Advance, when an organ is loaded.
