### ISSUE TITLE
Copyright headers need updating

### ISSUE THREAD

**Issue by larspalo** [GrandOrgue/grandorgue#716]
And occationally I think some files need them added.

**Comment by rousseldenis** [comment]
We can also adopt short license header like:

`* Copyright 2006 Milan Digital Audio LLC
 * Copyright 2009-2019 GrandOrgue contributors (see AUTHORS)
 * License GPL-3.0 or later (http://www.gnu.org/licenses/gpl.html).`

**Comment by larspalo** [comment]
I don't think we should mess with the version of the license, as that would require that all the contributors must agree. However the date should be changed to 2009-2021. The AUTHORS file should be updated with the new contributors. Also, all the new files must have the same header applied to them.

**Comment by rousseldenis** [comment]
> I don't think we should mess with the version of the license, as that would require that all the contributors must agree. However the date should be changed to 2009-2021. The AUTHORS file should be updated with the new contributors. Also, all the new files must have the same header applied to them.

I took the specific parts in existing files.

The other parts are text from the GNU license. So, no need to repeat them.

**Comment by larspalo** [comment]
As GO is distributed under GNU GPL v2 I think that no mention to GPL v3 should be made in any headers.

The current header layout just follows what is suggested for GPL v2 (http://www.gnu.org/licenses/old-licenses/gpl-2.0.html).

**Comment by rousseldenis** [comment]
> As GO is distributed under GNU GPL v2 I think that no mention to GPL v3 should be made in any headers.
> 
> The current header layout just follows what is suggested for GPL v2 (http://www.gnu.org/licenses/old-licenses/gpl-2.0.html).

Yes, of course, it can be adapted.

**Comment by rousseldenis** [comment]
And I remark that we need to update the root license.txt file to LICENSE file containing the GNU entire text.

https://www.gnu.org/licenses/gpl-howto.en.html

An example : https://github.com/OCA/stock-logistics-warehouse/blob/14.0/LICENSE

**Comment by larspalo** [comment]
Sure!

**Comment by rousseldenis** [comment]
@larspalo I've done a first proposition there #718. If we agree, I will go forward on other files.
