### ISSUE TITLE
Synchronise the application icon with the GitHub organisation

### ISSUE THREAD

**Issue by oleg68** [GrandOrgue/grandorgue#725]
1. @larspalo does not like current GrandOrgue icon. Maybe it is the time to change it.
2. Now there are differnent icons in the application and ont top of Github pages. They must be the same.

**Comment by Jean-Gabriel1982** [comment]
Do you talk about icon recently updated of the « old » one ?
Maybe we ça add some organ pipes and keyboard on the icon ?

**Comment by larspalo** [comment]
I attach an image comparing newer and the old icon showing how bad the new look at least on Linux. The new one we want to replace them with should be a svg version of the image, right? Should we take the question to the GO community and start a collection of suggestions, eventually leading up to a vote on the future icon?
![IconComparisonNewerOld](https://user-images.githubusercontent.com/6173941/134717662-ff3291ae-a68f-4590-a1ac-df34471299ef.png)

**Comment by oleg68** [comment]
> Should we take the question to the GO community and start a collection of suggestions, eventually leading up to a vote on the future icon?

I think, yes.

But first of all, we should enumerate requirements

1. svg format
2. 1024x1024

**Comment by larspalo** [comment]
Right! The quality of the icon is pretty poor when it's downscaled compared to the original image. Except making the .svg image with less small details that get fuzzy when the icon is created, do you know if there's any option during buildtime that will improve the output from imagemagic?

**Comment by Jean-Gabriel1982** [comment]
> Should we take the question to the GO community and start a collection of suggestions, eventually leading up to a vote on the future icon?

As @oleg68 , I think it is good idea.

**Comment by larspalo** [comment]
What place to make the announcement is most likely to get noticed by the GO community? In the General discussion forum?

**Comment by oleg68** [comment]
@larspalo

1. In the general discussion forum
2. In the [Facebook Group](https://www.facebook.com/groups/607484972705114)

**Comment by larspalo** [comment]
@oleg68 Ok, I can make a post in the general discussion forum here. As I'm not a member of the Facebook Group in question it would be nice if you announced it there - but please point to the discussion forum post here for all contributions.

**Comment by larspalo** [comment]
Announcement made in https://github.com/GrandOrgue/grandorgue/discussions/734

**Comment by oleg68** [comment]
@rousseldenis could you post the announcement in the FaceBook Group with the texe from #734 ?

**Comment by larspalo** [comment]
@oleg68 I just found out that (at least) on Ubuntu 20.04 it seems that none of the generated .png files are used as launcher icon by default but the generated .ico file instead. This .ico file is generated at 32x32 and of course won't scale nicely to 48 (that's the default). If the .ico file is generated at 64x64 then it's of course much better. The more, the merrier...

If I create a launcher with the main menu app and set the image icon to one of the .png files that's displayed in the program lists but as soon as the program is actually started it still seems like the .ico file is still used in the launcher bar. I haven't tried manually creating the .desktop file though, so I cannot say if that would change things.

Anyway, this partly explains the very poor icon quality that I've experienced with the new approach of icon creation.

**Comment by oleg68** [comment]
> 4. I've never bothered with installing GO (I rebuild it so often anyway...), I just created the menu item launcher with the .png icons from the build myself. I actually tested adding 48x48 too, but since it seems that the .ico is used in the launcher dock and the .png only for the menu pages it wasn't really that necessary as a higher resolution .png anyway looks better in the menus

``make install`` copies a lot of .png files with different size to /usr/share/icons/hicolor. Maybe after installing the launcher will use some of .png?

**Comment by oleg68** [comment]
The current icon is ot the title now.
