### ISSUE TITLE
Restoring Organ Settings to ones from ODF without losing Audio Group distribution

### ISSUE THREAD

**Issue by oleg68** [GrandOrgue/grandorgue#731]
Sometimes after modifying ODF it is necessary to forget all modifications made in the Organ settings and get these settins from the ODF. Unfortunally, it causes that settings that can not appear in ODF, for example, audio group, would also lose. It requred a big work of restoring audio group distribution.

It would be better to have capability of resetting organ setting to ODF without losing Audio Group.

**Comment by larspalo** [comment]
Just thinking aloud here. If the different settings for a specific organ would be split up into different related files (not all in the .cmb) that would be specialized for each task they perform - for instance the actual combinations in one, audio settings related in another etc - it should be easier to make such adjustments and migrations.

**Comment by oleg68** [comment]
Yes, I'd like to separate organ settings that **override** values from ODF from settings that **add** values that can not appear in ODF. Maybe separating on the file level is a good option.

**Comment by larspalo** [comment]
We should dissect the .cmb file for it's different parts and store them separately when they are not logically grouped, I think. But this is no small issue to fix. Also this can be related to the #700 issue, especially when it comes to the management of the files.

**Comment by oleg68** [comment]
@larspalo @rousseldenis 

I'm going to change the current Organ Settings `Default` button behavior: now it clears the audio group assignment, but in the future this action won't change this setting.

Do you agree with this enchancement?
