### ISSUE TITLE
Organsettings dialog is not scrollable

### ISSUE THREAD

**Issue by larspalo** [GrandOrgue/grandorgue#735]
The right part of the organsettings dialog can be invisible to users with a lower resolution screen. It should be made scrollable.

**Comment by oleg68** [comment]
Fixing this issue is important not to lose autosizing of this dialog to the optimal size (when everything fits the dialog).

Unfortunally, in wxWidgets in most layout methods OptimalSize=MinSize. Adding the scrolling reduces MinSize. It causes the dialog became too small after open.

**Comment by larspalo** [comment]
Maybe, but it's worse to not be able to see the entries at all!

**Comment by oleg68** [comment]
> Maybe, but it's worse to not be able to see the entries at all!

In case of very small screens. I doubt that such screens now exist.

So It is not a good idea to make worse in most cases for making better in a very rare case.

The right solution is to unlink OptimalSize from MinSize with a custom layout. Then dialog would be open with OptimalSize but would allow to resize it to a smaller size.

**Comment by larspalo** [comment]
I have that issue with a 1366x768 screen! Yes, it's old, but it's working and so should the dialog.

**Comment by oleg68** [comment]
> I have that issue with a 1366x768 screen! Yes, it's old, but it's working and so should the dialog.

I have such screen on my notebook and the setting dialog has a smaller size than 1366x768, so it is fully visible.

Maybe the root cause is not lack of scrolling but is the size of dialog is extremally large in your environment. In this case I'd find what tab is too large and to make this tab scrollable, but not the whole dialog.

**Comment by larspalo** [comment]
Remember I'm not talking about the general settings dialog, but the organ settings dialog where the voicing etc for each pipe resides. What's invisible is the tuning and intonation fieldset and below.
![OrganSettingsDialog](https://user-images.githubusercontent.com/6173941/135149357-fbf04912-1d4a-4611-afc8-b773b8a4f381.png)

**Comment by oleg68** [comment]
> I'm not talking about the general settings dialog, but the organ settings dialog 

Ooh, my mistake.

**Comment by larspalo** [comment]
Ok, looking at the content of the dialog code it's only the option to ignore pitch information in files that's hidden there. Thus this is not a matter of life and death. Still it's poor design somewhere down the road and could be considered a bug.
