### ISSUE TITLE
Discover ASIO license requirements

### ISSUE THREAD

**Issue by oleg68** [GrandOrgue/grandorgue#739]
This issue for finding gaps in implementing ASIO requirements in GO.

For filling these gaps separate issues have to be created - one for each gap.

**Comment by rousseldenis** [comment]
> For filling these gaps separate issues have to be created - one for each gap.

What do you mean by gaps ?

**Comment by oleg68** [comment]
> What do you mean by gaps ?

Things have to be changed in GrandOrgue for compilance with ASIO license. For example, prompting the user for ASIO agreement during install, displaying an ASIO logo at startup etc.

This issue is about enumerating those enchancements as a list of issues.

**Comment by rousseldenis** [comment]
List:

- [ ] #822

**Comment by oleg68** [comment]
@rousseldenis Seems everything has been done. May we close this issue?

**Comment by rousseldenis** [comment]
> @rousseldenis Seems everything has been done. May we close this issue?

Of course
