### ISSUE TITLE
Installing/Upgrading GO on Linux with graphic installers

### ISSUE THREAD

**Issue by oleg68** [GrandOrgue/grandorgue#741]
The [Install guide](https://github.com/GrandOrgue/grandorgue/blob/master/INSTALL.md) suggests to use a command line package manager (dnf, zypper, yum, apt-get) for installing GO on linux. But lots of users do not read this guide and try to install it just with double clicking on the rpm or deb file. The OS complains about unsatisfied dependencies and refuses to install.

The root cause is there are two packages `grandorgue` and `grandorgue-resources` that depend on each other. It requires installing them at the same time that double-click installers do not support.

My approach is

1. To break dependency grandorgue-resources -> grandorgue. It will allow to install grandorgue-resources before grandorgue
2. To let loose the dependency from grandorgue -> grandorgue-resources. Now it requires to be the same version, but in most cases `great or equal` will be sufficient. It will allow to upgrade grandorgue-resources with a double-click installer befor upgrading `grandorgue`

It will be still necessary to read some guide for knowing that resuurces should be installed first.

Another approach - not to make separate packages for grandorgue and grandorgue resources.

**Comment by Jean-Gabriel1982** [comment]
Yes at the beginning it is a bit confusing ..
I've downloaded
Grandorgue, grandorgue-ressources, and grandorgue-demo.

First, we need to install Ressources, then GrandOrgue, and finish by Demo by double-clicking on the .deb file.

Is it necessary to have 3 packages instead of only 1 ?

**Comment by oleg68** [comment]
> I've downloaded Grandorgue, grandorgue-ressources, and grandorgue-demo.

Lots of users download only grandorgue and try to install them.

> First, we need to install Ressources, then GrandOrgue, and finish by Demo by double-clicking on the .deb file.

For now, it is not possible.

> Is it necessary to have 3 packages instead of only 1 ?

For now, yes, it is.

**Comment by oleg68** [comment]
@larspalo How do you find an idea to make a singleton package `grandorgue` for linux witout separating resources and demo i own packages?

**Comment by oleg68** [comment]
@paolo2504 You like when everything is optimised. How do you find the idea when GrandOrgue Demo Organ is always installed without capability to install GrandOrgue without the demo,

**Comment by paolo2504** [comment]
Generally speaking I personally prefer not to have separate package installation for Go and GO resources. I mean, in the future I’d like to have one single install that takes care first of resources then of GO main. 

Regarding Demo, best option imho would be to be able to choose to do it or not in a graphical install; when not possibile, I do prefer to have it installed by default.

**Comment by larspalo** [comment]
@oleg68 In the long run I think it would be great to get GO into the different distributions natively, but that's not likely happening very quickly. To get a working solution now I think we perhaps could work on a few different approaches.

1. For Linux beginners an installation package, an appimage or something similar that will be more or less complete in itself
2. For normal Linux users some kind of repository that they can receive updates from - maybe only the actual releases
3. For bleeding edge testers all the builds including pre-releases more or less like it is now that require manual installation

Then to complement it I think it would be great to offer a custom live cd specialized for GO usage.

**Comment by oleg68** [comment]
@larspalo for (1) bleeding edge testers there are tar.gz packages that can be unpacked and tried without installation.

(2) and (3) are possible but they are quite complex.

In this issues I want to do some simple a quick enchancement for beginners.

After response from @paolo2504 I lean toward to make a single rpm/deb package instead of three ones. It will make life of beginners much easier.

**Comment by oleg68** [comment]
> When I get some time I'd like to tackle the appimage approach myself just to learn it also for other projects.

Could you assign #698 to youself?

One of our contributors has already tried it but without a success: GO was crached after had been launched from appimage somewhere in wxWidgets.

> I think we should keep it as simple as possible both to maintain and use.

Do you agree with a single .rpm/.deb package instead of grandorgue, grandorgue-resources and grandorgue-demo? This can be made with changing several lines in CmakeLists.txt. Double-clicking on this file will install all necessary dependencies.

**Comment by larspalo** [comment]
> Do you agree with a single .rpm/.deb package instead of grandorgue, grandorgue-resources and grandorgue-demo? This can be made with changing several lines in CmakeLists.txt. Double-clicking on it will install all necessary dependencies in all modern linux distributions.

Sure, if you feel that's the best way. We just need to document what the package will be doing so noone gets surprised by the behavior.
