### ISSUE TITLE
Is it possible to make GO open in single-window mode again?

### ISSUE THREAD

**Issue by lbssousa** [GrandOrgue/grandorgue#745]
Previous GO screenshots at Sourceforge and video demonstrations at Youtube show that it worked in single-window mode (menu, toolbar and organ image in the same window). In recent GO releases, however, the menu/toolbar and the organ image open in separate windows, which may be uncomfortable in small-resolution displays, because the organ image window may overlap the main one).

Is it possible to make it open in single-window mode again?

**Comment by rousseldenis** [comment]
Indeed, I have the same problem. I +1 about having one window for usability.

**Comment by paolo2504** [comment]
Interesting question. I remember with a netbook with small 10' screen i got the same issue.
Maybe it could be nice... Perhaps using a hidden menu that is activated by mouse-over movement or by a combination of keys
 (think for example to those apps like Remote desktops, Virtual Box, Vmware that work usually full-screen...).

**Comment by rousseldenis** [comment]
> Interesting question. I remember with a netbook with small 10' screen i got the same issue. Maybe it could be nice... Perhaps using a hidden menu that is activated by mouse-over movement or by a combination of keys (think for example to those apps like Remote desktops, Virtual Box, Vmware that work usually full-screen...).

F11 !

**Comment by larspalo** [comment]
This was a deliberate choice many years ago. Main point was that the user should be able to choose what to display and not be forced to keep a specific main window open all the time. Also it helped with positioning the different windows/dialogs according to user preferences.

**Comment by oleg68** [comment]
> may be uncomfortable in small-resolution displays, because the organ image window may overlap the main one

Especially in small-resolution displays the current behaviour might be more desirable, because there is no space for the main window controls on top of the organ.

**Comment by paolo2504** [comment]
Oleg, back once again on this… : why not enforce a new option to hide/unhide menu on mouse over ?

**Comment by oleg68** [comment]
> Oleg, back once again on this… : why not enforce a new option to hide/unhide menu on mouse over ?

It wouldn't allow user to place the main window on one screen and the organ window on another one.

Overlapping these windows on one screen gives the same capability to the user as auto-hiding.

**Comment by paolo2504** [comment]
Understood. Didn’t think on that. 
I do agree with you. thanks.

**Comment by larspalo** [comment]
I suggest we close this issue as a won't fix.

**Comment by oleg68** [comment]
@rousseldenis do you agree with closing this issue?

**Comment by lbssousa** [comment]
Any chance to make window layout switchable at least? I'm not sure if this is  doable with wxWidgets.

**Comment by oleg68** [comment]
@lbssousa It is fisible with wxWidgets, but requires a lot of coding with very doubt result.
