### ISSUE TITLE
Organs list disappeared

### ISSUE THREAD

**Issue by paolo2504** [GrandOrgue/grandorgue#786]
Issue description.
OS=W10 64bit , GO latest version 3.3.0.1
Scenario. 

I have loaded 20 Organs from disk D:\GOSampleSets where D: is a local ssd drive on my notebook. Usually I can see them in File/Load window.
Note: i NEVER changed the default Sampleset location (C:\Users\paolo\Documents\GrandOrgue\Organs) in GO Settings and, to be honest, I never wondered why i was able to see my organs in the Load window even if they were actually located in a folder (d:\samplesets) that is not set in the Settings...

Today, I decided to move the Sampleset folder from D:\GOSampleSets to G:\GOSampleSets where G: is an external ssd drive.
As expected, organs list got empty, except for the Demo organ.
I then set the new folder on disk G: in the GO Settings. Surprise: the Load window is still empty !
Then I copied just a couple of organs to D:\GOSampleSets and at this point GO was showing them.

Apparently, GO actually seems using the original folder from where organs are initially loaded the first time, while it is not using instead the Sampleset folder set in GO settings. If i am right, this seems to be a bug.

Note: i do understand that using a folder on an external drive seems not a good thing to do... Reason for doing so is that 
samplesets use many gigas on disk but are not necessary in my configuration because i prefer to cache organs. 
Only when i plan to change something, i connect the external drive to refresh cache.
Anycase, to use or not to use external disk it is not really important. What it is important is that the sampleset folder setting seems not to be used by GO. 
Actually, the same issue happens even using another folder on a local (not external) drive. I mean, saving organs originally loaded from d:\sampleset on d:\test and setting d:\test as the new sampleset directory, doing File/Load... GO still shows no organ list (except the Demo organ that is a package located in another folder).

**Comment by oleg68** [comment]
@paolo2504 The ``Sampleset directory`` is not a path where all samplesets must reside. It is just a starting directory for the File Chooser Dialog when you do `File->Open`. But you can navigate through different directories and open an organ file everywhere in the file system.

You are right. GrandOrgue remembers the path to each organ file, and changing this path doesn't affect organs already registered.

If you want to move already registered organs I'm going to add the ``Change path`` button the ``File->Settings->Organs`` dialog.

**Comment by paolo2504** [comment]
I see this issue has been removed from r3.4.2 as milestone. Does this mean this feature will not be added ?

**Comment by oleg68** [comment]
@paolo2504 I am thinking on removing the `Organs` tab from File->Settings and making a special `Manage organs` screen with additional actions (move, remove cache, delete and so on) with installing organs, but it is not easy.

Now as a workaround I suggest you
1. go to `File->Settings->Organs`
2. remove all organs having wrong paths
3. delete all cache files
4. reinstall all organs from the new path

> if true, this also cause having cache files duplicated , without the chance (according to another issue) to identify the extra cache files to be deleted… as you see, all things bound together..

You may delete all cache files. They will be recreated automatically when you open the organs,

**Comment by paolo2504** [comment]
Fine. Thank you.

**Comment by paolo2504** [comment]
> @paolo2504 I am thinking on removing the `Organs` tab from File->Settings and making a special `Manage organs` screen with additional actions (move, remove cache, delete and so on) with installing organs, but it is not easy.
> 
> Now as a workaround I suggest you
> 
>     1. go to `File->Settings->Organs`
> 
>     2. remove all organs having wrong paths
> 
>     3. delete all cache files
> 
>     4. reinstall all organs from the new path
> 
> 
> > if true, this also cause having cache files duplicated , without the chance (according to another issue) to identify the extra cache files to be deleted… as you see, all things bound together..
> 
> You may delete all cache files. They will be recreated automatically when you open the organs,

Oleg, i'm going to di like that you advise. 
Nevertheless, it is a workaround that does not solve the fact that the Sampleset parameter in the Settings is actually useless, probably not used by GO code at all. Do you plan to fix this in the future ? In addition, i wonder if some other parameters in the Settings/Default settings/Paths section are not working... Did you check on this ?
thanks.

**Comment by paolo2504** [comment]
Question: where the organs ODF Path is stored ? In the GrandOrgueSetting file under user/appdata/roaming ?

**Comment by oleg68** [comment]
The actual ODF path are stored in the GrandOrgueConfig file regardless the Samoleset folder.

This parameter is used only for initals position of the `Open Organ` dialog.

Now there is a feature `Correct Path` in the File->Settings->Organs tab.
