### ISSUE TITLE
Organ panels position not memorised

### ISSUE THREAD

**Issue by Jean-Gabriel1982** [GrandOrgue/grandorgue#787]
Hello,
I don't know if it's a grandorgue bug or a bug in my computer, but when I start grandorgue, the position of my panels is never remembered.

I am using Linux Mint with grandorgue version 3.2.0.1, and two touch screens. When the computer starts up, the two panels with stops (right jamb and left jamb) are placed on my right screen, while the main menu of grandorgue is placed on the left screen.

Systematically, I move my left panel to the left screen then I save the settings, but when restarting it is identical the two panels go back to the right screen ...

**Comment by larspalo** [comment]
@oleg68 There was a reason why maximizing of the windows were not "really" enabled earlier. We'll need to check the maximizing implementation and positioning that's currently included in GO. It was a very late addition [r2336] done by a developer doing quite a few things without any conversation or dialogue with the other developers. In essence I think the core problem could be that the actual sizes should not be stored when something is maximized but instead a flag specifying it to get the proper behaviour.

**Comment by oleg68** [comment]
@Jean-Gabriel1982 
1. Did you do `Save` after resizing before restart GO?
2. What desktop environmane do you use (gnome, kde, lxde, cinnamon etc)?

**Comment by oleg68** [comment]
> Ok i did this but when i open a terminal (root mode) i have this message

Try to do it without root mode

**Comment by Jean-Gabriel1982** [comment]
> > Ok i did this but when i open a terminal (root mode) i have this message
> 
> Try to do it without root mode

xrandr2.log
> Screen 0: minimum 320 x 200, current 2560 x 1024, maximum 16384 x 16384
HDMI-A-0 connected 1280x1024+0+0 (normal left inverted right x axis y axis) 338mm x 270mm
   1280x1024     60.02*+  75.02  
   1280x800      60.02  
   1280x720      60.02  
   1024x768      75.03    60.00  
   800x600       75.00    60.32    56.25  
   640x480       75.00    59.94  
   720x400       70.08  
DisplayPort-0 disconnected (normal left inverted right x axis y axis)
HDMI-A-1 connected 1280x1024+1280+0 (normal left inverted right x axis y axis) 338mm x 270mm
   1280x1024     60.02*+  75.02  
   1280x800      60.02  
   1280x720      60.02  
   1024x768      75.03    60.00  
   800x600       75.00    60.32    56.25  
   640x480       75.00    59.94  
   720x400       70.08  

xrandr1.log

> Screen 0: minimum 320 x 200, current 2560 x 1024, maximum 16384 x 16384
HDMI-A-0 connected 1280x1024+0+0 (normal left inverted right x axis y axis) 338mm x 270mm
   1280x1024     60.02*+  75.02  
   1280x800      60.02  
   1280x720      60.02  
   1024x768      75.03    60.00  
   800x600       75.00    60.32    56.25  
   640x480       75.00    59.94  
   720x400       70.08  
DisplayPort-0 disconnected (normal left inverted right x axis y axis)
HDMI-A-1 connected 1280x1024+1280+0 (normal left inverted right x axis y axis) 338mm x 270mm
   1280x1024     60.02*+  75.02  
   1280x800      60.02  
   1280x720      60.02  
   1024x768      75.03    60.00  
   800x600       75.00    60.32    56.25  
   640x480       75.00    59.94  
   720x400       70.08

**Comment by oleg68** [comment]
@Jean-Gabriel1982 Please make the following steps

1. Download [a GO build with additional debug enabled](https://github.com/oleg68/GrandOrgue-oficial/suites/4208229360/artifacts/108699982)
2. Extract `grandorgue-3.4.1-0.pos.linux.x86_64.tar.gz` file rom this zip archive
3. Unpack this `.tar.gz` into some directory <UnpackDir> under your home directory
4. Change the path in the ``Startup Application`` from `/bin/GrandOrgue` to the `<UnpackDir>/bin/GrandOrgue`
5. Restart you computer
6. When GO starts with the pannels at wrong positions, some debug messages will appear in the Log Window
7. Copy these log messages with a right-click menu and paste in a text file
8. Post this text file here

**Comment by Jean-Gabriel1982** [comment]
@oleg68 
 Thank you very much !
I'm on the move and could see it next Friday. I keep you informed :-)

**Comment by oleg68** [comment]
@Jean-Gabriel1982 I managed to reproduce it when the organ sattings were saved with a large screen resolution and GO starts with smaller screen resolution. Now the panel positions restored correctly in this case.

**Comment by Jean-Gabriel1982** [comment]
WoW super thank you very much !!
I am eager to try this when new update will come !!

**Comment by Jean-Gabriel1982** [comment]
@oleg68 

I've installed the new version and wahou ! That's really nice !
Thank you very much !!
