### ISSUE TITLE
Unable to load any organ settings.

### ISSUE THREAD

**Issue by oleg68** [GrandOrgue/grandorgue#813]
The intermediate build [3.4.1-0.14](https://github.com/GrandOrgue/grandorgue/actions/runs/1398020100) can't load a demo organ
![GO-3 4 1-0 14-1](https://user-images.githubusercontent.com/11586506/139526640-9fcfdc92-b4fc-408d-8483-ec6171135cc6.png)
![GO-3 4 1-0 14-2](https://user-images.githubusercontent.com/11586506/139526652-53976b42-003a-4866-807c-9e0371290b58.png)

The .cmb file exists at this path and can be successfuly load with the last release 3.4.0-1.

**Comment by larspalo** [comment]
That is a saved preset (obviously). I can confirm that no saved preset can be loaded even when created with the same version. I'll look into it!
