### ISSUE TITLE
Implement GO threading primitives over the C++11 standard ones

### ISSUE THREAD

**Issue by oleg68** [GrandOrgue/grandorgue#817]
Now there are two alternative implementation of GOMutex and GOCondition in the GO source code: with the wxWirgets classes wxMutex, wxCondition and with GOWaitQueue. The implementations are switched by WX_MUTEX compilation variable.

GOWaitQueue is not a standard primitive and itself has two alternative implementations: with wxSemaphore and with std::mutex (has been switched to std::timed_mutex as part of #784).

Now by default GOMutex uses GOWaitQueue that uses wxSemaphore.

This code is too complex and it is hard to troubleshoot. Most likely it has a bug, that causes #702

When GO was created, there were no any standard primitives std::mutex and std::condition_variable. But they appeared in C++11.

So seems the best solution is to rewrite the current implementation of GOMutex and GOCondition with std::timed_mutex and std::condition_variable without capability of switching to another impementations.

**Comment by larspalo** [comment]
Feel free to make the rewrite so we can test it. Though, I've not been able to reproduce #702 using alsa. With jack I've gotten many random hangs in different situations that I cannot reliably reproduce at will.

**Comment by oleg68** [comment]
@larspalo it is ready. You can get the intermediate build from my fork https://github.com/oleg68/GrandOrgue-oficial/actions/runs/1418196304 for testing.
