### ISSUE TITLE
Keyboard not being detected properly

### ISSUE THREAD

**Issue by WhoDaresMods** [GrandOrgue/grandorgue#835]
Greetings!

  I've been using grandorgue with almost no issues for around 2 weeks now, but yesterday when I booted the program, the sound output when I switched instruments was extremely distorted, like the audio was slowed down and there were lots of crackles and pops, making it virtually unplayable. I tried switching samples (to the standard GrandOrgue one to a few others that I had) and restarting the program several times yet the problem persisted, so I rebooted my computer since that fixed other problems I had had with the program before, but this time, when I started grandorgue, it was like I had a brand new installation. None of my settings were saved and it had an error message on startup that said something along the lines of "no audio output detected in group 1", and my MIDI keyboard wasn't being detected at all. Again, I tried closing and opening the program several times without success, so I decided to uninstall and re-install grandorgue.
  
  And then I had problems again: Now my keyboard _was_ detected in the initial midi configuration settings, but when I tried playing, no note except for the lowest C was detected, and when I pressed that it was stuck until I clicked it with my mouse. And as of writing this, I just opened grandorgue and it's working fine again...
  
  I'm sorry if this post is too vague, this all happened last night when I was extremely tired, and I'm also new to music software and music in general, so if anything needs clarification just ask me for it and I'll try to explain.

**Comment by oleg68** [comment]
@WhoDaresMods Do you still have any problems with GO? Or they were before and for now they are solved?

**Comment by WhoDaresMods** [comment]
@oleg68 Pardon me for the extremely late response, for some reason I never received an email notification of your reply. At any rate, I opened GO today again and the same low-C bug has appeared. I did install a new sample set before this, so the issue might be related, but I'm not tech-savy enough to discern precisely how.

Reading my post again I think I didn't do a good job at describing my problem. Basically, GO detects my keyboard in the "Initial MIDI Configuration" of the "Settings" page. However, once I try playing (and this happens regardless of what sample set I'm using, including the demo bundled with the program) none of the keys except for the lowest C are detected. And when I do press the lowest C, it gets stuck in-software, so in an organ sample this makes it sound like I'm holding the lowest C indefinitely. 

It fixed itself spontaneously last time, though I cannot recall whether this was due to a reinstall or just rebooting the program. I can record a video of the issue (if it doesn't fix itself again once I open GO to do so). Thanks for the help.

**Comment by oleg68** [comment]
> none of the keys except for the lowest C are detected. And when I do press the lowest C, it gets stuck in-software, so in an organ sample this makes it sound like I'm holding the lowest C indefinitely.

Please
1. `Audio/Midi->Log MIDI events`
2. Press and release different keys on your keyboard
3. Copy the content of the ``Log messages`` window with the right mouse click and past it here

**Comment by WhoDaresMods** [comment]
24/12/2021 13:09:26: 13:09:26: Warning: MIDI event: note channel: 1 key: 59 value: 100
24/12/2021 13:09:26: 13:09:26: Warning: MIDI event: note channel: 1 key: 59 value: 0
24/12/2021 13:09:28: 13:09:28: Warning: MIDI event: note channel: 1 key: 59 value: 100
24/12/2021 13:09:29: 13:09:29: Warning: MIDI event: note channel: 1 key: 62 value: 100
24/12/2021 13:09:29: 13:09:29: Warning: MIDI event: note channel: 1 key: 59 value: 0
24/12/2021 13:09:29: 13:09:29: Warning: MIDI event: note channel: 1 key: 62 value: 0
24/12/2021 13:09:29: 13:09:29: Warning: MIDI event: note channel: 1 key: 67 value: 100
24/12/2021 13:09:29: 13:09:29: Warning: MIDI event: note channel: 1 key: 67 value: 0
24/12/2021 13:09:29: 13:09:29: Warning: MIDI event: note channel: 1 key: 72 value: 100
24/12/2021 13:09:29: 13:09:29: Warning: MIDI event: note channel: 1 key: 72 value: 0
24/12/2021 13:09:29: 13:09:29: Warning: MIDI event: note channel: 1 key: 76 value: 100
24/12/2021 13:09:29: 13:09:29: Warning: MIDI event: note channel: 1 key: 76 value: 0
24/12/2021 13:09:29: 13:09:29: Warning: MIDI event: note channel: 1 key: 67 value: 100
24/12/2021 13:09:30: 13:09:30: Warning: MIDI event: note channel: 1 key: 67 value: 0
24/12/2021 13:09:30: 13:09:30: Warning: MIDI event: note channel: 1 key: 72 value: 100
24/12/2021 13:09:30: 13:09:30: Warning: MIDI event: note channel: 1 key: 76 value: 100
24/12/2021 13:09:30: 13:09:30: Warning: MIDI event: note channel: 1 key: 72 value: 0
24/12/2021 13:09:30: 13:09:30: Warning: MIDI event: note channel: 1 key: 76 value: 0
24/12/2021 13:09:55: 13:09:55: Warning: MIDI event: note channel: 1 key: 36 value: 100
24/12/2021 13:09:55: 13:09:55: Warning: MIDI event: note channel: 1 key: 36 value: 0
24/12/2021 13:09:56: 13:09:56: Warning: MIDI event: note channel: 1 key: 36 value: 100
24/12/2021 13:09:56: 13:09:56: Warning: MIDI event: note channel: 1 key: 36 value: 0

Here, the bug happened again

**Comment by oleg68** [comment]
@WhoDaresMods Merry Christmass!

Ok, when the issue happens I see only C1 note on and off.

Do I understand correctly, then at first all notes are playable, but after some time only C1 remein playable?

1. How many keyboards do you have? Are another keyboards also stuck at C1 or not?
2. After C1 stuck, please try to click `Audio/Midi->Panic`. Does the keyboard start working again?
3. If no, please restart GrandOrgue. Does the keyboard work or not?
4. If no, try to restart the computer. What's happen?

**Comment by WhoDaresMods** [comment]
I only have one keyboard and no other MIDI devices plugged in. But I don't think the log is accurate because other keys are detected in the log, but they do no translate into the program. i.e. they don't play except for C, which doesn't go on an off, it simply gets stuck as if I was holding it down.

The bug fixed itself spontaneously again after I repeatedly enabled and disabled the keyboard in the "Initial MIDI configuration" page. Before that I tried restarting GO, my computer, and even reinstalling GO but nothing worked. I never tried the panic function because I wasn't quite sure what it was meant to do. 

If my description is not clear enough, I have made a video detailing the problem:

https://www.youtube.com/watch?v=nIWHnx5KRog

I am using a haprsichord sample set but this bug also happens to all other samples, including the one bundled with GO.

**Comment by oleg68** [comment]
@WhoDaresMods Please repeat your video with `Audio/Midi->Log MIDI events`.

**Comment by oleg68** [comment]
@WhoDaresMods I'm sorry, I cann't help you without an additional information I've requested.

Please feel free of opening a new issue if the problem arrives again.

**Comment by OomCarl** [comment]
My problem with GrandOrgue is not being able to get my second M-Audio Keystation 61 recognized. This problem does not occur in Hauptwerk (4.2) but is sofar unsolvable in GrandOrgue. My computer is an iMac Retina 5K, 27 inch 2017 Intel Core 15. Both Keystations are plugged into the USB ports of the computer. GrandOrgue only recognizes one or the other of them. I've tried all the suggestions for activating the keyboards, but without success. Anybody else had this issue and solved it?
