### ISSUE TITLE
Crash to desktop Win10 large registration

### ISSUE THREAD

**Issue by mutti-wilson** [GrandOrgue/grandorgue#847]
@oleg68 asked for a crashdump to see what's going on. Crashes after playing large registration.

I'm using the latest 3.4.2-0.2 build by @oleg68

[GrandOrgue.exe.8792.zip](https://github.com/GrandOrgue/grandorgue/files/7533203/GrandOrgue.exe.8792.zip)

**Comment by oleg68** [comment]
@mutti-wilson Please try to use https://drive.google.com/file/d/1vlak-ZYcVHXUYTADA54FTitCt6qRCMV5/view?usp=sharing
(without installation; just unpack it to some directory and run `bin\GrandOrgue.exe`) and post here the new crash dump from this version.

**Comment by mutti-wilson** [comment]
Here are 2 crash dumps. I don't know why they have a duplicate file name since the time generated is the same but they are slightly different sized so I thought sending both would be wis
[CrashDumps.zip](https://github.com/GrandOrgue/grandorgue/files/7536139/CrashDumps.zip)
e.

**Comment by mutti-wilson** [comment]
So if it matters I have a little info to add as well as another crash dump. The first crash was using WDM drivers, second was ASIO and this crash was using Direct Sound. Direct sound lasted the longest before crashing. If you need any other background let me know and I'll do what I can to answer. Thanks for digging in on this.

[CrashDumps.zip](https://github.com/GrandOrgue/grandorgue/files/7543688/CrashDumps.zip)

**Comment by oleg68** [comment]
Thank you, @mutti-wilson I will discover your crash dumps.

**Comment by oleg68** [comment]
Asio:
```
   ExceptionCode: c0000005 (Access violation)
Attempt to read from address 000000000000008c

00000000`008ff0a8 00000000`004afc6b : 00000000`0fa17860 00000000`0000000e 00000000`00000000 00000000`0000000f : GrandOrgue!GetVelocityVolume+0xb
00000000`008ff0b0 00000000`0fa17860 : 00000000`0000000e 00000000`00000000 00000000`0000000f 00000000`0fa17860 : GrandOrgue!UpdateVelocity+0x1b
```

**Comment by oleg68** [comment]
DirectSound:

```
00000000`008ff0a8 00000000`004afc6b : 00000000`0fa17860 00000000`0000000e 00000000`00000000 00000000`0000000f : GrandOrgue!GetVelocityVolume+0xb
00000000`008ff0b0 00000000`0fa17860 : 00000000`0000000e 00000000`00000000 00000000`0000000f 00000000`0fa17860 : GrandOrgue!UpdateVelocity+0x1b
```

- The same as asio.

So this problem seems does not relate to the sound driver

**Comment by mutti-wilson** [comment]
@oleg68 I am using Friesach. I've never used the metronome. I remember poking around in the ODF for some reason but I don't think I made any changes. I will check and see if the metronome got switched on somehow. I'll dig around and try out the new version tonight as well. Does the debug log point to any pipe specifically?

**Comment by mutti-wilson** [comment]
@oleg68 I used the new build and played for almost 2 hours with all stops and couplers pulled and experienced no crashes. I changed back to ASIO because I feel like the latency is superior and knowing that it crashed often using ASIO I thought that would be a good test. Seems like it's fixed. I have an untouched ODF of Friesach that I did not try as it would be too many variables and harder to pin down what actually fixed it.

**Comment by oleg68** [comment]
@mutti-wilson Thank you for your test. It is not a final fix yet, but I'll work on it for the official version.

**Comment by oleg68** [comment]
@mutti-wilson please try the [official intermediate build](https://github.com/GrandOrgue/grandorgue/actions/runs/1472692697) with fixing this issue

**Comment by mutti-wilson** [comment]
@oleg68 I will install this when I get home this evening.

**Comment by mutti-wilson** [comment]
@oleg68 This build worked great. No crashes at all. Thanks so much. I'm back in business and hopefully others will benefit from this fix as well.
