### ISSUE TITLE
Can you make it compatible with OSX 10.11.6 El Capitan?

### ISSUE THREAD

**Issue by SuperMitic** [GrandOrgue/grandorgue#865]
I ask you if you can make this app compatible with MacOS 10.11.6 El Capitan. Now it crashes as soon as i open it.

**Comment by oleg68** [comment]
Please post the crash report here.

**Comment by oleg68** [comment]
It is imposible with build on GitHub. But you can build GO from sources on your mac.

**Comment by oleg68** [comment]
See also #789
