### ISSUE TITLE
Midi keyboard identifications are not persistent 

### ISSUE THREAD

**Issue by pmwisse** [GrandOrgue/grandorgue#885]
I've recently switched from the old Sourceforge version to this one and most is a tremendous improvement, for which I am very grateful. The names of the midi devices changed, but another problem went along with it, which is that the names are no longer persistent after restarts of Ubuntu. I use Ubuntu 21.10 and 3.4.2-1 with three UMX-61 keyboards. After I added a Bluetooth headphone to my Linux install, the names of the devices changed so I screwed up all the settings in my organs. I'm not sure this is a problem in GrandOrgue, but this was a problem that did not exist in the last versions of the Sourceforge Grandorgue.

**Comment by oleg68** [comment]
Will be fixed in #703

**Comment by pmwisse** [comment]
OK, thanks! I'll wait patiently! So happy to see active development on this precious piece of software!

**Comment by oleg68** [comment]
I'm reopening this issues because the code modifications for #703 became very large.

Enchancement of midi device matching will be done in this issue

**Comment by oleg68** [comment]
- [ ] Allow to match device names by regex
- [ ] Introduce the Matching button for changing regex for the device
- [ ] Midi events configured for the device should continue to work if the device changes it's name but is still existing
