### ISSUE TITLE
GrandorgueTool in Window

### ISSUE THREAD

**Issue by paolo2504** [GrandOrgue/grandorgue#949]
I just found that the GrandOrgueTool that comes with GO installation apparently doesn't work. It does no action. Tried also "grandorguetool -h" to get help.
At first i tried with winrar and 7z to compress an organ folder setting compression ratio to 0 (store) and renaming the file with .orgue. With File/install organ package GO does try to open the file but after a while it returns the error "no end record found".
Samplesets found on the net are usually compressed with normal level; GO does recognize them (after renaming to .orgue) but in this case the returned error is "only stored compression supported".
This to explain why i finally came to GrandOrgueTool, unfortunately discovering that it does not work...
thanks for help.

<from Discussion>
I know that organ packages are just compressed archives that can be opened with zip/rar tools. They are loaded in GO using file/install package. This is fine but I don’t see anywhere the uncompressed organs so I wonder how they are managed. I mean: I don’t believe they are uncompressed on the fly (in temp dir ?) and then deleted on close…
I post this question to understand if it would be better having only compressed samplesets just changing the file extension. 
note: after some search i found interesting posts by Lars Palo on the GO Tool included in the installation. I'm looking at it; however, at first sight it does not answer a basic Q: most samplesets com in .zip or .rar format. They are recognized by GO as packages but they fall in error because the compression ratio/method is usually not set to 0 (GO returns the error "only stored compression supported").
The GOTool i suppose is able to compress and generate organ packages from folder and subfolders: ok, but this means one has to uncompress samplesets downloaded from internet before submitting them to GO tool...
Question is at this point: what is the reald advantage of using Install Organ Package ? Size is the same... organ are loaded into ram no matter they are in folder structures or in one compressed file...
just to understand better. thanks.

![errore no end record found](https://user-images.githubusercontent.com/50132661/148430902-54f18e02-adc1-4e9a-91c9-d4108800297e.jpg)
![errore only stored compression supported](https://user-images.githubusercontent.com/50132661/148430906-fb1cb7cf-60b8-48b5-ac8a-97c0504db3b9.jpg)

_Originally posted by @paolo2504 in https://github.com/GrandOrgue/grandorgue/discussions/944_

**Comment by paolo2504** [comment]
i've just looked at post #915 and now from Lars's words i understand much more. I see this is something that can be improved but not for the moment..

<However, i would appreciate to know if there is some way to make grandorguetool work under Windows. thanks.>

**Comment by paolo2504** [comment]
Just to notice: i was able to use wavpack to recursively pack sampleset and create working .orgue package un der Windows.
I also tested GrandogueTool under Linux (Raspbian, raspberry pi3b+). It works perfectly but it really slow if compared to wavpack under Windows.

**Comment by ChasFW** [comment]
To fix the "No end record found" error, just select "Archive format" to "zip" in the dropdown box in 7-zip (as well as compression level to 0-store).

**Comment by paolo2504** [comment]
Thanks ChasFW but I already fixed everything. I have opened a new post and published a log file to show the results on some samplesets.
