### ISSUE TITLE
Midi Matching and event detection

### ISSUE THREAD

**Issue by tocchetti** [GrandOrgue/grandorgue#953]
I do appreciate the new midi matching feature and I started to use it as it was available (thanks Oleg for the advice on FB).

I'm afraid I need some help as since I've mapped my 4 devices with 4 different logical names and 4 different matching regex expressions, the "Listen for Event" feature (I tested it in "Generals") started mapping some devices as "Any device".
 
I tried to find a workaround by manually selecting the device and
1) I can't find the logical names but instead I see the regex expressions (this can be ok but it's a bit weird)
2) I can't find the physical device names of the devices (this can be ok)
3) Even if I assign the event to a specific device selecting its regex expression from the dropdown menu, the same event is not recognized when I play the organ.

**Comment by oleg68** [comment]
``Listen for Event`` should use ``Logical Name``, not regex

**Comment by tocchetti** [comment]
> `Listen for Event` should use `Logical Name`, not regex

I totally agree, I mean that 'Listen for Event' should match the 'Physical Name' of the "listened" device to match the regex and finally use the related 'Logical Name'. But I'm afraid it does not work properly. 
I tested this new function quite extensively, so my configuration file could be a bit messed up. Where can I go to check or delete it? I'm currently using windows.

**Comment by oleg68** [comment]
> Where can I go to check or delete it? I'm currently using windows.

Please delete the ``<User home directory>\AppData\Roaming\GrandOrgueConfig`` file for making a new clean configuration.

GrandOrgue 3.5.0-1 detects all midi devices and automatically creates default logical names and regex for them.

Under windows the physical name should look like ``winmm: Device Name DevNum``, but the logical names and the regex will be ``winmm: Device Name`` (the same as the physical name but without DevNum). You may leave the logical names unchanged, but also you may give them some meaningful names, ex. `Pedal`, `Manual 1`, etc.

After exiting from the config, you are able to see the logical names in the ``Listen for Event`` dialog. By default the logical names and regexes are the same, but if you have changed logical names, you will see only logical names here. 

> I mean that the 'Listen for Event' should match the 'Physical Name' of the "listened" device to match the regex and finally use the related 'Logical Name'.

GrandOrgue itself makes all matching. 'Listen for Event' knows only logical names.

When you change logical names for a device the old event assignment stops working. You have to select the new logical name in the ``Listen for Event`` manually.

If something goes wrong, please post here the screenshots of your ``Matching`` and ``Listen for Event`` windows.

**Comment by tocchetti** [comment]
Many thanks for your support, now it works properly.
