### ISSUE TITLE
Load dialog resized null on raspberry

### ISSUE THREAD

**Issue by paolo2504** [GrandOrgue/grandorgue#963]
I've just created a .orgue package under raspberry and i noticed two issues:

a) doing "Install organ package" the folder GrandOrgue/Organs is opened instead of GrandOrgue/Organ packages
b) after registration, doing File/Load the dialog is opened with "0 size": it appears as a small vertical line in the middle of the GO window just over the text "Max". see screenshots below. A manual resize is needed to open dialog and see its content. 
Note that after resize, dialog settings are maintained only in the current session. Closing and restarting GO the size settings again come to 0.

![2022-01-15-012027_1360x768_scrot](https://user-images.githubusercontent.com/50132661/149601261-eb8c0276-6dfa-4219-82dc-29fb140ba8c3.png)
![2022-01-15-012056_1360x768_scrot](https://user-images.githubusercontent.com/50132661/149601286-96a2180b-4a0d-496b-8265-62b1a319851f.png)

**Comment by oleg68** [comment]
> a) doing "Install organ package" the folder GrandOrgue/Organs is opened instead of GrandOrgue/Organ packages

Looking at the source code, the directory ``GrandOrgue/Organ packages`` is used not for opening new packages, but it's content is scanned automatically every time when GO starts.

@larspalo is it an the desired behavior? If so, we should update the documentation.

**Comment by oleg68** [comment]
@paolo2504 could you try the intermediate build from https://github.com/oleg68/GrandOrgue-official/actions/runs/1725374872

Does it solve the dialog size problem?

**Comment by larspalo** [comment]
@oleg68 Yes, this is a fairly well documented behavior that I've tried to explain many times over and over. You have it in the wiki second line on https://github.com/GrandOrgue/grandorgue/wiki/Organ-package-creation-(GrandOrgueTool) and also in the fourth point of the quickstart guide. And it's very well documented in the GO help. But if you have any idea for how to improve the already available information - please go for it.

I take it one more time though: 

1. The "Organ packages" path is the directory where the user can just drop an organ package and it will be recognized by GO at next startup. So, yes, it's scanned by GO at every startup!
2. The "Install organ package" menu item is **only** for if the user for whatever unspecified reason doesn't want to put the organ package at previously said directory but elsewhere. Then the program opens a dialog for user choice that have to start somewhere, right, and what's more logical than in the same directory that old style organs are normally opened from? But it of course doesn't make sense to start looking in a directory that GO itself would have already scanned!

**Comment by paolo2504** [comment]
> > a) doing "Install organ package" the folder GrandOrgue/Organs is opened instead of GrandOrgue/Organ packages
> 
> Looking at the source code, the directory `GrandOrgue/Organ packages` is used not for opening new packages, but it's content is scanned automatically every time when GO starts.
> 
> @larspalo is it an the desired behavior? If so, we should update the documentation.

Thanks Oleg. 
this is not a big issue any case..
IMHO, it’s more logical and intuitive having organs in “organs” folder and “packages” in organ packages. Lars correctly refers to documentation. I read it in the past carefully and I understand it. I know Go “remembers” the path an organ is installed first (no matter it is organ or package) but I remind that this also cause problem if user changes the samplesets path later on (see my previous post on this issue).
Anyway feel free to close the issue  if you like. Thanks.
