### ISSUE TITLE
GrandOrgue crashes when Convolution Reverb is activated while the organ is still running

### ISSUE THREAD

**Issue by matheus-j-ressurreicao** [GrandOrgue/grandorgue#983]
I would very much like to report what could be a possible GrandOrgue error. Let's see. I went to perform a test with the convulation reverb feature enabled. It seems to work normally, provided that a valid impulse response has been selected. What happens, however, is that if the user changes any impulse response file or even turns the feature on or off when the organ is still running, it seems to me that GrandOrgue starts crashing and showing a lot of instability, with strong bursts in the audio that are only resolved either by closing the program or sometimes by pressing the "panic" button. I ask, in this spirit, if this could be some bug in the program or if the convolution reverb should not be changed when the organ is still running?

**Comment by oleg68** [comment]
@matheus-j-ressurreicao I cann't reproduce this issue.

Could you provide more information: what operating system and what version of GO are you using?

Could you explain ``turns the feature on or off when the organ is still running`` step-by step?

**Comment by matheus-j-ressurreicao** [comment]
@oleg68, I found out what was going on. I will specify a step-by-step procedure so that you can reproduce the problem. What happened was the following: for lack of technical knowledge about how convolution reverb works, I simply selected the directory for an impulse response file without changing the other settings (delay, start offset, length, channel, gain etc.). The result was a big burst in the audio and, I believe, some problem with the audio output. When pressing a note on the demo organ included in GrandOrgue, the result was more burst and more problems with the audio output. I am guessing, based on what I have reported here and the disccussion started in #975, that the problem lies in the specific convolution reverb setting (in terms of delay, start offset, length, channel, gain etc.) for that impulse response file. It seems to me that when an impulse response file is selected, GrandOrgue automatically changes "length", but does not change the other parameters. In this sense I believe that the crash was a consequence of the large bursts caused by the audio output of the notes and records that were running when GrandOrgue processed that impulse response file. When trying to reproduce the problem again, the bursts in the audio output occurred again, but there was not a crash of the program due to overloading the computational resources. I ask, in this spirit, if there is a possibility of a revision of the operation of the convolution reverb in the sense that it automatically changes these parameters when some impulse response file is selected, as it happens with "length", or if it should be stated in the documentation that, in some impulse response files, if these parameters are not changed, this problem of bursts in the audio output may occur, which I believe should not occur under normal conditions of the operation of the program. @oleg68 , in order for you to reproduce this suspected problem I will do the following: I will attach below (in a compressed file, since GitHub does not allow uploading the .wav file directly) the impulse response file that caused this problem. Try leaving a few notes pressed down on any GrandOrgue organ (I am using the demo one, for testing purposes), enable the convolution reverb setting and select this impulse response file. Complete and setup and see if those bursts appear. Please see how GrandOrgue behaves regarding the use of computer resources (CPU, RAM, etc., as I believe the crash was a consequence of the audio processing performed by the convolution reverb). Please lower the volume / intesity of the audio output as much as you can, as I did not have a good experience when this happened... For the sake of clarity I will leave the parameter values that were selected when the problem occurred: 

delay (ms): 0 
Start offset: 0
Length: 15672
Channel: 1
Gain: 1

Direct Sound: add dirac pulse (the setting was selected)

I was running GrandOrgue version 3.6.0-1 on Windows 10 Version 21H2 Build 19044.1499) at the time of this problem. Below is the impulse response file that caused this problem.

Oleg, thank you very much. Anything at all, please just let me know. 

[Impulse Response File.zip](https://github.com/GrandOrgue/grandorgue/files/7964232/Impulse.Response.File.zip)

**Comment by oleg68** [comment]
@matheus-j-ressurreicao I've just repeated the following steps:

1. Ran Windows 10
2. Unpacked the impulse response file you provided
3. Unpacked GrandOrgue 3.6.1 from here https://github.com/GrandOrgue/grandorgue/releases/download/3.6.1-1/grandorgue-3.6.1-1.windows.x86_64.zip
4. Ran GrandOrgue with the demo organ
5. Switched on the ``Montre 8`` stop
6. Pressed a C-moll chord (G3 + C4 + Eb4) with a mouse
7. Opened the Settings Dialog
8. Went to the Reverb tab
9. Checked the ``Enable Convolution Reverb``
10. After the warning that it is not supported, chose the impulse response file you provided
11. Pressed on the OK button
12. The sound stopped playing. But I'm still able to press keys with a mouse and the sound plays correctly

Is these steps correct? Could you repeat them? What is the result?

**Comment by matheus-j-ressurreicao** [comment]
@oleg68 , all steps are correct. The mistake was on my part: I sent a response file to the wrong impulse. I have retraced the same steps here several times and it seems to me that there is nothing wrong with the convolution reverb system, so that the cause of the crash I suffered was an overload of computational resources due to this particular impulse response file... @oleg68, here is the correct file below, and sorry for the inconvenience. 

[Correct Impulse Response File.zip](https://github.com/GrandOrgue/grandorgue/files/7966434/Correct.Impulse.Response.File.zip)

**Comment by oleg68** [comment]
I tried the same steps with the new response file and I still did not find any problems.

Let us know, is your crash ever related with the reverb or not.

Try to press some keys, to open Settings and to close them with the OK button without any changes. What happens? Does the crash occure or not?

**Comment by matheus-j-ressurreicao** [comment]
@oleg68 , I tried to record a video to demosntrate the problem, but without success, because it captures only the organ window... I tested this impulse response file again and the problem really happens... The audio output remains distorted even after the program closes for a while Please try to follow all these steps again, as that is what I did to make this problem occur. Make sure that the add dirac pulse option is enabled and that all parameters follow as I reported above. The audio burst happens and continues indefinitely, only stopping a while after the organ is closed. When the file is added in settings before the organ is opened, the said instability happens just after when the organ is opened. I will keep trying to record a video. Please let me know if you manage to play it back.

**Comment by oleg68** [comment]
@matheus-j-ressurreicao I've tried to reproduce it many times but without a success.

1. Could you try to open and to close the setting dialog with OK (Not with Cancel) without impulse responce. Does the crash occure?
2. Are you ready to run GrandOrgue with debug enabled and send me the crash file?

**Comment by matheus-j-ressurreicao** [comment]
@oleg68, I'm looking to record a video to demonstrate this problem. Regarding question 1, the crash does not occur if this impulse response file is not selected. Regarding question 02, I will debug the application and send it to you as soon as possible. This message is to communicate that I am already aware of the request. Thank you very much, Oleg.

**Comment by oleg68** [comment]
@matheus-j-ressurreicao please try [the intermediate build](https://drive.google.com/file/d/15whngJGwYC1sq11WwCkVzs8pDXYLJ3b_/view?usp=sharing)

When GO crashes, please post the last crashdump file from `AppData\Local\CrashDumps` here.

**Comment by matheus-j-ressurreicao** [comment]
@oleg68, since my last comment, I have repeatedly tried to repeat the problem that I had first reported. So, based on what I found out, I would like to make some corrections and ponderings. Let's see. I had mentioned that GrandOrgue crashes when Convolution Reverb is activated while the organ is running. Actually, as I corrected in the comments I made after reporting this problem, this is not a crash, but an audio distortion. I put that it was a crash because the first time this problem happened GrandOrgue crashed and, from what I saw here, I have that crashdump saved in the folder you indicated, the one I would like to send. Oleg, do you remember that you had mentioned that sometimes I was able to relay the problem and other times I couldn't? Let me explain why. Please note in the video I recorded that audio distortion does occur. However, what I had not realized until then is that it occurs when I already leave the convolution reverb on in another session of using GrandOrgue. You see, in the video, before opening the organ, convolution reverb was already active (saved as a preset from a previous session) and distortion occurs when I open the organ and continues even when I close it and select the same impulse response file again. The only way for the distortion to stop is to close the organ, disable convolution reverb, close GrandOrgue, open it again, and enable reverb only after the program is started. In other words, when I reported the problem and there was the succession of facts that I reported earlier, I had not even cited the causes of the problem, but its consequences. I could be wrong, but it seems to me that there is some problem in retrieving the configuration information that has been saved for the user, right? Also, it seems to me that GrandOrgue activates the convolution reverb function "twice" when it opens. Take a look: try to activate the function in a previous session and do not select any impulse response files. An error message will appear. Close GrandOrgue and keep the feature enabled. When you open the program again, the error message that a valid impulse response file has not been added will appear twice. This seems to indicate to me that there is either an error with displaying the message or with retrieving the user information saved in settings, including the reverb, and therein a possible cause of the distortion. Please Oleg, try to reproduce the problem by doing this: open GrandOrgue, enable reverb, select the impulse response file I sent you earlier, close GrandOrgue, open GrandOrgue again, open the organ and see if distortion occurs, please. I was not able to run a debug on the program, as per. Anything, I can try to do that with an indication of how to proceed. Below is the crashdump file and the link to the video. Maybe a better name for this problem is the following: GrandOrgue distorts the audio output when the convolution reverb feature remains enabled for more than one session. Anyway, I believe this is something to investigate. Oleg, anything at all, please, just let me know. 

Youtube Video Link: https://www.youtube.com/watch?v=FNV2hQK2GZ4
[GrandOrgue.exe.8184 CrashDump.zip](https://github.com/GrandOrgue/grandorgue/files/8006992/GrandOrgue.exe.8184.CrashDump.zip)

**Comment by oleg68** [comment]
@matheus-j-ressurreicao Please post the screenshot of the File->Settings->Audio tab

**Comment by oleg68** [comment]
@matheus-j-ressurreicao Unfortunally I can only analyze the crash report from the debugging version

**Comment by matheus-j-ressurreicao** [comment]
@oleg68, below is a screenshot of the audio tab. I did not know about this issue. By the way, how could I access GrandOrgue in the debugging version? Based on what I reported earlier, it seems to me that the crash was caused by a succession of events other than necessarily this convolution reverb problem... So much so that it did not happen again, despite the audio distortion. Oleg, please, anything, you can let me know. If you need any more information, just let me know. Thanks. 
![image](https://user-images.githubusercontent.com/70448819/152648730-15d9a868-9b76-4e90-9e4b-ad00aa138c0f.png)

**Comment by oleg68** [comment]
1. Could you try to set Gain: 0.1? Does this issue occure?
2. Could you post here the screenshot of `Options` screen?

**Comment by matheus-j-ressurreicao** [comment]
@oleg68, regarding 1., yes distortion still occurs when I set the gain to 0.1. The audio bursts still occur when "pulling" any register on the organ and during the pressing of any note. The distortion, however, changes shape. It is funny because this same distortion, supposedly caused by this particular impulse response file, does not occur when the reverb does not remain activated for more than one session. Could it be that the problem is not the loading of some incorrectly done code, in view of this duplication that occurs when reverb remains activated for more than one session? Oleg, check out a question that may be related. Follow these steps: open GrandOrgue, select a valid impulse response file in some directory, press OK, close GrandOrgue, go to that directory where the impulse response file was selected and delete the impulse response file, open GrandOrgue again. Notice that the message that the impulse response file cannot be opened appears three times, which leads me to think that the GrandOrgue code is looping when activating this functionality by reading the user's saved settings. Below I send you a printout of the "Log messages" screen that appears when you follow these steps and of the "Options" screen. If you have any problems, please let me know. Thanks again. 


![image](https://user-images.githubusercontent.com/70448819/152699164-a20ad524-d51f-4173-b6f8-2c00e2783b38.png)



![image](https://user-images.githubusercontent.com/70448819/152699141-0b32e95e-a66f-463d-a9d4-227b00b50131.png)

**Comment by oleg68** [comment]
I managed to reproduce this problem on windows. Unfortunally, the reproducing is very unstable. I was not able to reproduce it on linux.

When this issue occures, decreasing the length of reverb to 51000 resolves this issue. I suggest you to use it as a workaround.

**Comment by matheus-j-ressurreicao** [comment]
@oleg68 , thank you very much. I opened this issue to bring it to your attention, as I thought it might be some bug related to the way convolution reverb is programmed (see that in my last message I put the printout of the log screen when an impulse response file is previously selected and deleted when starting a new "session" in GrandOrgue, so to speak. The messages appear duplicated). Yes, indeed, the playback is very unstable. The alternative solution and it worked! Anything I can help with, please feel free to let me know. Again, thanks!

**Comment by oleg68** [comment]
@matheus-j-ressurreicao 

There are two different problems:
1. Sound boost when IR is used with "Length: 51705" and 48000 sample rate.
2. GO hangs when resetting the sound system (panic, exit from settings etc.)

Could you test [the intermediate version](https://github.com/oleg68/GrandOrgue-official/actions/runs/1974203126): whether it solves the first problem?

I know that the second problem still persists in this version and I'm working on it.

**Comment by matheus-j-ressurreicao** [comment]
@oleg68, sorry for the delay in returning feedback. Look, I did the test with the intermediate version and the first problem also remains...

**Comment by oleg68** [comment]
@matheus-j-ressurreicao does setting the length to 51000 solve the first problem?

**Comment by matheus-j-ressurreicao** [comment]
@oleg68 yes, it seems to me that setting the length to 51000 solves the first problem. Oleg, thank you very much. I see that you have discovered the ZitaConvolver module issue. In fact, the main problem was with the panic button, getting out of the settings, in short, something in this submodule... Thank you!!!
